// Code generated by protoc-gen-go. DO NOT EDIT.
// source: home.proto

package protodef

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//存档保存
type ReqSaveArchive struct {
	Archive              *ArchiveEntity `protobuf:"bytes,1,opt,name=archive,proto3" json:"archive,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *ReqSaveArchive) Reset()         { *m = ReqSaveArchive{} }
func (m *ReqSaveArchive) String() string { return proto.CompactTextString(m) }
func (*ReqSaveArchive) ProtoMessage()    {}
func (*ReqSaveArchive) Descriptor() ([]byte, []int) {
	return fileDescriptor_711cc65aaf7510e9, []int{0}
}

func (m *ReqSaveArchive) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSaveArchive.Unmarshal(m, b)
}
func (m *ReqSaveArchive) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSaveArchive.Marshal(b, m, deterministic)
}
func (m *ReqSaveArchive) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSaveArchive.Merge(m, src)
}
func (m *ReqSaveArchive) XXX_Size() int {
	return xxx_messageInfo_ReqSaveArchive.Size(m)
}
func (m *ReqSaveArchive) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSaveArchive.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSaveArchive proto.InternalMessageInfo

func (m *ReqSaveArchive) GetArchive() *ArchiveEntity {
	if m != nil {
		return m.Archive
	}
	return nil
}

//获取用户信息
type ReqPlayerInfo struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqPlayerInfo) Reset()         { *m = ReqPlayerInfo{} }
func (m *ReqPlayerInfo) String() string { return proto.CompactTextString(m) }
func (*ReqPlayerInfo) ProtoMessage()    {}
func (*ReqPlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_711cc65aaf7510e9, []int{1}
}

func (m *ReqPlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqPlayerInfo.Unmarshal(m, b)
}
func (m *ReqPlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqPlayerInfo.Marshal(b, m, deterministic)
}
func (m *ReqPlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqPlayerInfo.Merge(m, src)
}
func (m *ReqPlayerInfo) XXX_Size() int {
	return xxx_messageInfo_ReqPlayerInfo.Size(m)
}
func (m *ReqPlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqPlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReqPlayerInfo proto.InternalMessageInfo

type NtfPlayerInfo struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NtfPlayerInfo) Reset()         { *m = NtfPlayerInfo{} }
func (m *NtfPlayerInfo) String() string { return proto.CompactTextString(m) }
func (*NtfPlayerInfo) ProtoMessage()    {}
func (*NtfPlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_711cc65aaf7510e9, []int{2}
}

func (m *NtfPlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NtfPlayerInfo.Unmarshal(m, b)
}
func (m *NtfPlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NtfPlayerInfo.Marshal(b, m, deterministic)
}
func (m *NtfPlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NtfPlayerInfo.Merge(m, src)
}
func (m *NtfPlayerInfo) XXX_Size() int {
	return xxx_messageInfo_NtfPlayerInfo.Size(m)
}
func (m *NtfPlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_NtfPlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_NtfPlayerInfo proto.InternalMessageInfo

//设置玩家信息
type ReqSetPlayerInfo struct {
	PlayerName           string   `protobuf:"bytes,1,opt,name=playerName,proto3" json:"playerName,omitempty"`
	Gold                 int32    `protobuf:"varint,2,opt,name=gold,proto3" json:"gold,omitempty"`
	Gem                  int32    `protobuf:"varint,3,opt,name=gem,proto3" json:"gem,omitempty"`
	Exp                  int32    `protobuf:"varint,4,opt,name=exp,proto3" json:"exp,omitempty"`
	Level                int32    `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	AircraftId           int32    `protobuf:"varint,6,opt,name=aircraftId,proto3" json:"aircraftId,omitempty"`
	RoleId               int32    `protobuf:"varint,7,opt,name=roleId,proto3" json:"roleId,omitempty"`
	SkinIdx              int32    `protobuf:"varint,8,opt,name=skinIdx,proto3" json:"skinIdx,omitempty"`
	Flag                 string   `protobuf:"bytes,9,opt,name=flag,proto3" json:"flag,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSetPlayerInfo) Reset()         { *m = ReqSetPlayerInfo{} }
func (m *ReqSetPlayerInfo) String() string { return proto.CompactTextString(m) }
func (*ReqSetPlayerInfo) ProtoMessage()    {}
func (*ReqSetPlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_711cc65aaf7510e9, []int{3}
}

func (m *ReqSetPlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSetPlayerInfo.Unmarshal(m, b)
}
func (m *ReqSetPlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSetPlayerInfo.Marshal(b, m, deterministic)
}
func (m *ReqSetPlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSetPlayerInfo.Merge(m, src)
}
func (m *ReqSetPlayerInfo) XXX_Size() int {
	return xxx_messageInfo_ReqSetPlayerInfo.Size(m)
}
func (m *ReqSetPlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSetPlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSetPlayerInfo proto.InternalMessageInfo

func (m *ReqSetPlayerInfo) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *ReqSetPlayerInfo) GetGold() int32 {
	if m != nil {
		return m.Gold
	}
	return 0
}

func (m *ReqSetPlayerInfo) GetGem() int32 {
	if m != nil {
		return m.Gem
	}
	return 0
}

func (m *ReqSetPlayerInfo) GetExp() int32 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *ReqSetPlayerInfo) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *ReqSetPlayerInfo) GetAircraftId() int32 {
	if m != nil {
		return m.AircraftId
	}
	return 0
}

func (m *ReqSetPlayerInfo) GetRoleId() int32 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *ReqSetPlayerInfo) GetSkinIdx() int32 {
	if m != nil {
		return m.SkinIdx
	}
	return 0
}

func (m *ReqSetPlayerInfo) GetFlag() string {
	if m != nil {
		return m.Flag
	}
	return ""
}

type RspSetPlayerInfo struct {
	PlayerName           string   `protobuf:"bytes,1,opt,name=playerName,proto3" json:"playerName,omitempty"`
	Gold                 int32    `protobuf:"varint,2,opt,name=gold,proto3" json:"gold,omitempty"`
	Gem                  int32    `protobuf:"varint,3,opt,name=gem,proto3" json:"gem,omitempty"`
	Exp                  int32    `protobuf:"varint,4,opt,name=exp,proto3" json:"exp,omitempty"`
	Level                int32    `protobuf:"varint,5,opt,name=level,proto3" json:"level,omitempty"`
	AircraftId           int32    `protobuf:"varint,6,opt,name=aircraftId,proto3" json:"aircraftId,omitempty"`
	RoleId               int32    `protobuf:"varint,7,opt,name=roleId,proto3" json:"roleId,omitempty"`
	SkinIdx              int32    `protobuf:"varint,8,opt,name=skinIdx,proto3" json:"skinIdx,omitempty"`
	Flag                 string   `protobuf:"bytes,9,opt,name=flag,proto3" json:"flag,omitempty"`
	ErrorCode            int32    `protobuf:"varint,10,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspSetPlayerInfo) Reset()         { *m = RspSetPlayerInfo{} }
func (m *RspSetPlayerInfo) String() string { return proto.CompactTextString(m) }
func (*RspSetPlayerInfo) ProtoMessage()    {}
func (*RspSetPlayerInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_711cc65aaf7510e9, []int{4}
}

func (m *RspSetPlayerInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspSetPlayerInfo.Unmarshal(m, b)
}
func (m *RspSetPlayerInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspSetPlayerInfo.Marshal(b, m, deterministic)
}
func (m *RspSetPlayerInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspSetPlayerInfo.Merge(m, src)
}
func (m *RspSetPlayerInfo) XXX_Size() int {
	return xxx_messageInfo_RspSetPlayerInfo.Size(m)
}
func (m *RspSetPlayerInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_RspSetPlayerInfo.DiscardUnknown(m)
}

var xxx_messageInfo_RspSetPlayerInfo proto.InternalMessageInfo

func (m *RspSetPlayerInfo) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *RspSetPlayerInfo) GetGold() int32 {
	if m != nil {
		return m.Gold
	}
	return 0
}

func (m *RspSetPlayerInfo) GetGem() int32 {
	if m != nil {
		return m.Gem
	}
	return 0
}

func (m *RspSetPlayerInfo) GetExp() int32 {
	if m != nil {
		return m.Exp
	}
	return 0
}

func (m *RspSetPlayerInfo) GetLevel() int32 {
	if m != nil {
		return m.Level
	}
	return 0
}

func (m *RspSetPlayerInfo) GetAircraftId() int32 {
	if m != nil {
		return m.AircraftId
	}
	return 0
}

func (m *RspSetPlayerInfo) GetRoleId() int32 {
	if m != nil {
		return m.RoleId
	}
	return 0
}

func (m *RspSetPlayerInfo) GetSkinIdx() int32 {
	if m != nil {
		return m.SkinIdx
	}
	return 0
}

func (m *RspSetPlayerInfo) GetFlag() string {
	if m != nil {
		return m.Flag
	}
	return ""
}

func (m *RspSetPlayerInfo) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

//内购验证
type ReqIapVerify struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqIapVerify) Reset()         { *m = ReqIapVerify{} }
func (m *ReqIapVerify) String() string { return proto.CompactTextString(m) }
func (*ReqIapVerify) ProtoMessage()    {}
func (*ReqIapVerify) Descriptor() ([]byte, []int) {
	return fileDescriptor_711cc65aaf7510e9, []int{5}
}

func (m *ReqIapVerify) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqIapVerify.Unmarshal(m, b)
}
func (m *ReqIapVerify) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqIapVerify.Marshal(b, m, deterministic)
}
func (m *ReqIapVerify) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqIapVerify.Merge(m, src)
}
func (m *ReqIapVerify) XXX_Size() int {
	return xxx_messageInfo_ReqIapVerify.Size(m)
}
func (m *ReqIapVerify) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqIapVerify.DiscardUnknown(m)
}

var xxx_messageInfo_ReqIapVerify proto.InternalMessageInfo

//请求排行榜
type ReqRankData struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqRankData) Reset()         { *m = ReqRankData{} }
func (m *ReqRankData) String() string { return proto.CompactTextString(m) }
func (*ReqRankData) ProtoMessage()    {}
func (*ReqRankData) Descriptor() ([]byte, []int) {
	return fileDescriptor_711cc65aaf7510e9, []int{6}
}

func (m *ReqRankData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqRankData.Unmarshal(m, b)
}
func (m *ReqRankData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqRankData.Marshal(b, m, deterministic)
}
func (m *ReqRankData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqRankData.Merge(m, src)
}
func (m *ReqRankData) XXX_Size() int {
	return xxx_messageInfo_ReqRankData.Size(m)
}
func (m *ReqRankData) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqRankData.DiscardUnknown(m)
}

var xxx_messageInfo_ReqRankData proto.InternalMessageInfo

func (m *ReqRankData) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ReqRankData) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

//请求我的排行数据
type ReqMyRankData struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqMyRankData) Reset()         { *m = ReqMyRankData{} }
func (m *ReqMyRankData) String() string { return proto.CompactTextString(m) }
func (*ReqMyRankData) ProtoMessage()    {}
func (*ReqMyRankData) Descriptor() ([]byte, []int) {
	return fileDescriptor_711cc65aaf7510e9, []int{7}
}

func (m *ReqMyRankData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqMyRankData.Unmarshal(m, b)
}
func (m *ReqMyRankData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqMyRankData.Marshal(b, m, deterministic)
}
func (m *ReqMyRankData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqMyRankData.Merge(m, src)
}
func (m *ReqMyRankData) XXX_Size() int {
	return xxx_messageInfo_ReqMyRankData.Size(m)
}
func (m *ReqMyRankData) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqMyRankData.DiscardUnknown(m)
}

var xxx_messageInfo_ReqMyRankData proto.InternalMessageInfo

//请求赛季数据
type ReqSeasonData struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSeasonData) Reset()         { *m = ReqSeasonData{} }
func (m *ReqSeasonData) String() string { return proto.CompactTextString(m) }
func (*ReqSeasonData) ProtoMessage()    {}
func (*ReqSeasonData) Descriptor() ([]byte, []int) {
	return fileDescriptor_711cc65aaf7510e9, []int{8}
}

func (m *ReqSeasonData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSeasonData.Unmarshal(m, b)
}
func (m *ReqSeasonData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSeasonData.Marshal(b, m, deterministic)
}
func (m *ReqSeasonData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSeasonData.Merge(m, src)
}
func (m *ReqSeasonData) XXX_Size() int {
	return xxx_messageInfo_ReqSeasonData.Size(m)
}
func (m *ReqSeasonData) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSeasonData.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSeasonData proto.InternalMessageInfo

//请求重置赛季
type ReqResetSeason struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqResetSeason) Reset()         { *m = ReqResetSeason{} }
func (m *ReqResetSeason) String() string { return proto.CompactTextString(m) }
func (*ReqResetSeason) ProtoMessage()    {}
func (*ReqResetSeason) Descriptor() ([]byte, []int) {
	return fileDescriptor_711cc65aaf7510e9, []int{9}
}

func (m *ReqResetSeason) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqResetSeason.Unmarshal(m, b)
}
func (m *ReqResetSeason) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqResetSeason.Marshal(b, m, deterministic)
}
func (m *ReqResetSeason) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqResetSeason.Merge(m, src)
}
func (m *ReqResetSeason) XXX_Size() int {
	return xxx_messageInfo_ReqResetSeason.Size(m)
}
func (m *ReqResetSeason) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqResetSeason.DiscardUnknown(m)
}

var xxx_messageInfo_ReqResetSeason proto.InternalMessageInfo

//请求活动数据
type ReqActiveData struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqActiveData) Reset()         { *m = ReqActiveData{} }
func (m *ReqActiveData) String() string { return proto.CompactTextString(m) }
func (*ReqActiveData) ProtoMessage()    {}
func (*ReqActiveData) Descriptor() ([]byte, []int) {
	return fileDescriptor_711cc65aaf7510e9, []int{10}
}

func (m *ReqActiveData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqActiveData.Unmarshal(m, b)
}
func (m *ReqActiveData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqActiveData.Marshal(b, m, deterministic)
}
func (m *ReqActiveData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqActiveData.Merge(m, src)
}
func (m *ReqActiveData) XXX_Size() int {
	return xxx_messageInfo_ReqActiveData.Size(m)
}
func (m *ReqActiveData) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqActiveData.DiscardUnknown(m)
}

var xxx_messageInfo_ReqActiveData proto.InternalMessageInfo

//请求保存活动数据
type ReqSaveActiveInfo struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSaveActiveInfo) Reset()         { *m = ReqSaveActiveInfo{} }
func (m *ReqSaveActiveInfo) String() string { return proto.CompactTextString(m) }
func (*ReqSaveActiveInfo) ProtoMessage()    {}
func (*ReqSaveActiveInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_711cc65aaf7510e9, []int{11}
}

func (m *ReqSaveActiveInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSaveActiveInfo.Unmarshal(m, b)
}
func (m *ReqSaveActiveInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSaveActiveInfo.Marshal(b, m, deterministic)
}
func (m *ReqSaveActiveInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSaveActiveInfo.Merge(m, src)
}
func (m *ReqSaveActiveInfo) XXX_Size() int {
	return xxx_messageInfo_ReqSaveActiveInfo.Size(m)
}
func (m *ReqSaveActiveInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSaveActiveInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSaveActiveInfo proto.InternalMessageInfo

//获取大转盘数据
type ReqLuckywheelData struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqLuckywheelData) Reset()         { *m = ReqLuckywheelData{} }
func (m *ReqLuckywheelData) String() string { return proto.CompactTextString(m) }
func (*ReqLuckywheelData) ProtoMessage()    {}
func (*ReqLuckywheelData) Descriptor() ([]byte, []int) {
	return fileDescriptor_711cc65aaf7510e9, []int{12}
}

func (m *ReqLuckywheelData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqLuckywheelData.Unmarshal(m, b)
}
func (m *ReqLuckywheelData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqLuckywheelData.Marshal(b, m, deterministic)
}
func (m *ReqLuckywheelData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqLuckywheelData.Merge(m, src)
}
func (m *ReqLuckywheelData) XXX_Size() int {
	return xxx_messageInfo_ReqLuckywheelData.Size(m)
}
func (m *ReqLuckywheelData) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqLuckywheelData.DiscardUnknown(m)
}

var xxx_messageInfo_ReqLuckywheelData proto.InternalMessageInfo

//请求转盘奖励
type ReqRaffleLuckywheel struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqRaffleLuckywheel) Reset()         { *m = ReqRaffleLuckywheel{} }
func (m *ReqRaffleLuckywheel) String() string { return proto.CompactTextString(m) }
func (*ReqRaffleLuckywheel) ProtoMessage()    {}
func (*ReqRaffleLuckywheel) Descriptor() ([]byte, []int) {
	return fileDescriptor_711cc65aaf7510e9, []int{13}
}

func (m *ReqRaffleLuckywheel) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqRaffleLuckywheel.Unmarshal(m, b)
}
func (m *ReqRaffleLuckywheel) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqRaffleLuckywheel.Marshal(b, m, deterministic)
}
func (m *ReqRaffleLuckywheel) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqRaffleLuckywheel.Merge(m, src)
}
func (m *ReqRaffleLuckywheel) XXX_Size() int {
	return xxx_messageInfo_ReqRaffleLuckywheel.Size(m)
}
func (m *ReqRaffleLuckywheel) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqRaffleLuckywheel.DiscardUnknown(m)
}

var xxx_messageInfo_ReqRaffleLuckywheel proto.InternalMessageInfo

//请求签到数据
type ReqDailysignData struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqDailysignData) Reset()         { *m = ReqDailysignData{} }
func (m *ReqDailysignData) String() string { return proto.CompactTextString(m) }
func (*ReqDailysignData) ProtoMessage()    {}
func (*ReqDailysignData) Descriptor() ([]byte, []int) {
	return fileDescriptor_711cc65aaf7510e9, []int{14}
}

func (m *ReqDailysignData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqDailysignData.Unmarshal(m, b)
}
func (m *ReqDailysignData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqDailysignData.Marshal(b, m, deterministic)
}
func (m *ReqDailysignData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqDailysignData.Merge(m, src)
}
func (m *ReqDailysignData) XXX_Size() int {
	return xxx_messageInfo_ReqDailysignData.Size(m)
}
func (m *ReqDailysignData) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqDailysignData.DiscardUnknown(m)
}

var xxx_messageInfo_ReqDailysignData proto.InternalMessageInfo

//请求签到奖励
type ReqSignIn struct {
	UserId               int32    `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Addition             int32    `protobuf:"varint,2,opt,name=addition,proto3" json:"addition,omitempty"`
	TimeOffset           int32    `protobuf:"varint,3,opt,name=time_offset,json=timeOffset,proto3" json:"time_offset,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSignIn) Reset()         { *m = ReqSignIn{} }
func (m *ReqSignIn) String() string { return proto.CompactTextString(m) }
func (*ReqSignIn) ProtoMessage()    {}
func (*ReqSignIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_711cc65aaf7510e9, []int{15}
}

func (m *ReqSignIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSignIn.Unmarshal(m, b)
}
func (m *ReqSignIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSignIn.Marshal(b, m, deterministic)
}
func (m *ReqSignIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSignIn.Merge(m, src)
}
func (m *ReqSignIn) XXX_Size() int {
	return xxx_messageInfo_ReqSignIn.Size(m)
}
func (m *ReqSignIn) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSignIn.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSignIn proto.InternalMessageInfo

func (m *ReqSignIn) GetUserId() int32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *ReqSignIn) GetAddition() int32 {
	if m != nil {
		return m.Addition
	}
	return 0
}

func (m *ReqSignIn) GetTimeOffset() int32 {
	if m != nil {
		return m.TimeOffset
	}
	return 0
}

//请求视频列表
type ReqVideoList struct {
	VideoType            int32    `protobuf:"varint,1,opt,name=videoType,proto3" json:"videoType,omitempty"`
	Page                 int32    `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize             int32    `protobuf:"varint,3,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	Language             string   `protobuf:"bytes,4,opt,name=language,proto3" json:"language,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqVideoList) Reset()         { *m = ReqVideoList{} }
func (m *ReqVideoList) String() string { return proto.CompactTextString(m) }
func (*ReqVideoList) ProtoMessage()    {}
func (*ReqVideoList) Descriptor() ([]byte, []int) {
	return fileDescriptor_711cc65aaf7510e9, []int{16}
}

func (m *ReqVideoList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqVideoList.Unmarshal(m, b)
}
func (m *ReqVideoList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqVideoList.Marshal(b, m, deterministic)
}
func (m *ReqVideoList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqVideoList.Merge(m, src)
}
func (m *ReqVideoList) XXX_Size() int {
	return xxx_messageInfo_ReqVideoList.Size(m)
}
func (m *ReqVideoList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqVideoList.DiscardUnknown(m)
}

var xxx_messageInfo_ReqVideoList proto.InternalMessageInfo

func (m *ReqVideoList) GetVideoType() int32 {
	if m != nil {
		return m.VideoType
	}
	return 0
}

func (m *ReqVideoList) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ReqVideoList) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

func (m *ReqVideoList) GetLanguage() string {
	if m != nil {
		return m.Language
	}
	return ""
}

//请求视频播放
type ReqVideoPlay struct {
	VideoId              int32    `protobuf:"varint,1,opt,name=videoId,proto3" json:"videoId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqVideoPlay) Reset()         { *m = ReqVideoPlay{} }
func (m *ReqVideoPlay) String() string { return proto.CompactTextString(m) }
func (*ReqVideoPlay) ProtoMessage()    {}
func (*ReqVideoPlay) Descriptor() ([]byte, []int) {
	return fileDescriptor_711cc65aaf7510e9, []int{17}
}

func (m *ReqVideoPlay) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqVideoPlay.Unmarshal(m, b)
}
func (m *ReqVideoPlay) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqVideoPlay.Marshal(b, m, deterministic)
}
func (m *ReqVideoPlay) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqVideoPlay.Merge(m, src)
}
func (m *ReqVideoPlay) XXX_Size() int {
	return xxx_messageInfo_ReqVideoPlay.Size(m)
}
func (m *ReqVideoPlay) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqVideoPlay.DiscardUnknown(m)
}

var xxx_messageInfo_ReqVideoPlay proto.InternalMessageInfo

func (m *ReqVideoPlay) GetVideoId() int32 {
	if m != nil {
		return m.VideoId
	}
	return 0
}

//请求视频奖励
type ReqVideoReward struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqVideoReward) Reset()         { *m = ReqVideoReward{} }
func (m *ReqVideoReward) String() string { return proto.CompactTextString(m) }
func (*ReqVideoReward) ProtoMessage()    {}
func (*ReqVideoReward) Descriptor() ([]byte, []int) {
	return fileDescriptor_711cc65aaf7510e9, []int{18}
}

func (m *ReqVideoReward) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqVideoReward.Unmarshal(m, b)
}
func (m *ReqVideoReward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqVideoReward.Marshal(b, m, deterministic)
}
func (m *ReqVideoReward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqVideoReward.Merge(m, src)
}
func (m *ReqVideoReward) XXX_Size() int {
	return xxx_messageInfo_ReqVideoReward.Size(m)
}
func (m *ReqVideoReward) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqVideoReward.DiscardUnknown(m)
}

var xxx_messageInfo_ReqVideoReward proto.InternalMessageInfo

//连胜保护
type ReqProtectWinStreak struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqProtectWinStreak) Reset()         { *m = ReqProtectWinStreak{} }
func (m *ReqProtectWinStreak) String() string { return proto.CompactTextString(m) }
func (*ReqProtectWinStreak) ProtoMessage()    {}
func (*ReqProtectWinStreak) Descriptor() ([]byte, []int) {
	return fileDescriptor_711cc65aaf7510e9, []int{19}
}

func (m *ReqProtectWinStreak) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqProtectWinStreak.Unmarshal(m, b)
}
func (m *ReqProtectWinStreak) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqProtectWinStreak.Marshal(b, m, deterministic)
}
func (m *ReqProtectWinStreak) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqProtectWinStreak.Merge(m, src)
}
func (m *ReqProtectWinStreak) XXX_Size() int {
	return xxx_messageInfo_ReqProtectWinStreak.Size(m)
}
func (m *ReqProtectWinStreak) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqProtectWinStreak.DiscardUnknown(m)
}

var xxx_messageInfo_ReqProtectWinStreak proto.InternalMessageInfo

//获取友情福利数据
type ReqFriendRewardData struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqFriendRewardData) Reset()         { *m = ReqFriendRewardData{} }
func (m *ReqFriendRewardData) String() string { return proto.CompactTextString(m) }
func (*ReqFriendRewardData) ProtoMessage()    {}
func (*ReqFriendRewardData) Descriptor() ([]byte, []int) {
	return fileDescriptor_711cc65aaf7510e9, []int{20}
}

func (m *ReqFriendRewardData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqFriendRewardData.Unmarshal(m, b)
}
func (m *ReqFriendRewardData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqFriendRewardData.Marshal(b, m, deterministic)
}
func (m *ReqFriendRewardData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqFriendRewardData.Merge(m, src)
}
func (m *ReqFriendRewardData) XXX_Size() int {
	return xxx_messageInfo_ReqFriendRewardData.Size(m)
}
func (m *ReqFriendRewardData) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqFriendRewardData.DiscardUnknown(m)
}

var xxx_messageInfo_ReqFriendRewardData proto.InternalMessageInfo

//请求存档友情福利
type ReqSaveFriendReward struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSaveFriendReward) Reset()         { *m = ReqSaveFriendReward{} }
func (m *ReqSaveFriendReward) String() string { return proto.CompactTextString(m) }
func (*ReqSaveFriendReward) ProtoMessage()    {}
func (*ReqSaveFriendReward) Descriptor() ([]byte, []int) {
	return fileDescriptor_711cc65aaf7510e9, []int{21}
}

func (m *ReqSaveFriendReward) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSaveFriendReward.Unmarshal(m, b)
}
func (m *ReqSaveFriendReward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSaveFriendReward.Marshal(b, m, deterministic)
}
func (m *ReqSaveFriendReward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSaveFriendReward.Merge(m, src)
}
func (m *ReqSaveFriendReward) XXX_Size() int {
	return xxx_messageInfo_ReqSaveFriendReward.Size(m)
}
func (m *ReqSaveFriendReward) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSaveFriendReward.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSaveFriendReward proto.InternalMessageInfo

//请求友情福利 抽奖
type ReqLotteryFriendReward struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqLotteryFriendReward) Reset()         { *m = ReqLotteryFriendReward{} }
func (m *ReqLotteryFriendReward) String() string { return proto.CompactTextString(m) }
func (*ReqLotteryFriendReward) ProtoMessage()    {}
func (*ReqLotteryFriendReward) Descriptor() ([]byte, []int) {
	return fileDescriptor_711cc65aaf7510e9, []int{22}
}

func (m *ReqLotteryFriendReward) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqLotteryFriendReward.Unmarshal(m, b)
}
func (m *ReqLotteryFriendReward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqLotteryFriendReward.Marshal(b, m, deterministic)
}
func (m *ReqLotteryFriendReward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqLotteryFriendReward.Merge(m, src)
}
func (m *ReqLotteryFriendReward) XXX_Size() int {
	return xxx_messageInfo_ReqLotteryFriendReward.Size(m)
}
func (m *ReqLotteryFriendReward) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqLotteryFriendReward.DiscardUnknown(m)
}

var xxx_messageInfo_ReqLotteryFriendReward proto.InternalMessageInfo

//请求大师赛排行榜数据
type ReqMasterRankData struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqMasterRankData) Reset()         { *m = ReqMasterRankData{} }
func (m *ReqMasterRankData) String() string { return proto.CompactTextString(m) }
func (*ReqMasterRankData) ProtoMessage()    {}
func (*ReqMasterRankData) Descriptor() ([]byte, []int) {
	return fileDescriptor_711cc65aaf7510e9, []int{23}
}

func (m *ReqMasterRankData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqMasterRankData.Unmarshal(m, b)
}
func (m *ReqMasterRankData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqMasterRankData.Marshal(b, m, deterministic)
}
func (m *ReqMasterRankData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqMasterRankData.Merge(m, src)
}
func (m *ReqMasterRankData) XXX_Size() int {
	return xxx_messageInfo_ReqMasterRankData.Size(m)
}
func (m *ReqMasterRankData) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqMasterRankData.DiscardUnknown(m)
}

var xxx_messageInfo_ReqMasterRankData proto.InternalMessageInfo

func (m *ReqMasterRankData) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ReqMasterRankData) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

//请求大师赛我的排行
type ReqMasterMyRank struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqMasterMyRank) Reset()         { *m = ReqMasterMyRank{} }
func (m *ReqMasterMyRank) String() string { return proto.CompactTextString(m) }
func (*ReqMasterMyRank) ProtoMessage()    {}
func (*ReqMasterMyRank) Descriptor() ([]byte, []int) {
	return fileDescriptor_711cc65aaf7510e9, []int{24}
}

func (m *ReqMasterMyRank) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqMasterMyRank.Unmarshal(m, b)
}
func (m *ReqMasterMyRank) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqMasterMyRank.Marshal(b, m, deterministic)
}
func (m *ReqMasterMyRank) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqMasterMyRank.Merge(m, src)
}
func (m *ReqMasterMyRank) XXX_Size() int {
	return xxx_messageInfo_ReqMasterMyRank.Size(m)
}
func (m *ReqMasterMyRank) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqMasterMyRank.DiscardUnknown(m)
}

var xxx_messageInfo_ReqMasterMyRank proto.InternalMessageInfo

//请求清除大师赛老数据
type ReqMasterCleanOld struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqMasterCleanOld) Reset()         { *m = ReqMasterCleanOld{} }
func (m *ReqMasterCleanOld) String() string { return proto.CompactTextString(m) }
func (*ReqMasterCleanOld) ProtoMessage()    {}
func (*ReqMasterCleanOld) Descriptor() ([]byte, []int) {
	return fileDescriptor_711cc65aaf7510e9, []int{25}
}

func (m *ReqMasterCleanOld) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqMasterCleanOld.Unmarshal(m, b)
}
func (m *ReqMasterCleanOld) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqMasterCleanOld.Marshal(b, m, deterministic)
}
func (m *ReqMasterCleanOld) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqMasterCleanOld.Merge(m, src)
}
func (m *ReqMasterCleanOld) XXX_Size() int {
	return xxx_messageInfo_ReqMasterCleanOld.Size(m)
}
func (m *ReqMasterCleanOld) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqMasterCleanOld.DiscardUnknown(m)
}

var xxx_messageInfo_ReqMasterCleanOld proto.InternalMessageInfo

//请求钻石消耗数量
type ReqDiamondConsume struct {
	Count                int32    `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqDiamondConsume) Reset()         { *m = ReqDiamondConsume{} }
func (m *ReqDiamondConsume) String() string { return proto.CompactTextString(m) }
func (*ReqDiamondConsume) ProtoMessage()    {}
func (*ReqDiamondConsume) Descriptor() ([]byte, []int) {
	return fileDescriptor_711cc65aaf7510e9, []int{26}
}

func (m *ReqDiamondConsume) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqDiamondConsume.Unmarshal(m, b)
}
func (m *ReqDiamondConsume) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqDiamondConsume.Marshal(b, m, deterministic)
}
func (m *ReqDiamondConsume) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqDiamondConsume.Merge(m, src)
}
func (m *ReqDiamondConsume) XXX_Size() int {
	return xxx_messageInfo_ReqDiamondConsume.Size(m)
}
func (m *ReqDiamondConsume) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqDiamondConsume.DiscardUnknown(m)
}

var xxx_messageInfo_ReqDiamondConsume proto.InternalMessageInfo

func (m *ReqDiamondConsume) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

//请求上传fcm.token
type ReqUploadFcmToken struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqUploadFcmToken) Reset()         { *m = ReqUploadFcmToken{} }
func (m *ReqUploadFcmToken) String() string { return proto.CompactTextString(m) }
func (*ReqUploadFcmToken) ProtoMessage()    {}
func (*ReqUploadFcmToken) Descriptor() ([]byte, []int) {
	return fileDescriptor_711cc65aaf7510e9, []int{27}
}

func (m *ReqUploadFcmToken) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqUploadFcmToken.Unmarshal(m, b)
}
func (m *ReqUploadFcmToken) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqUploadFcmToken.Marshal(b, m, deterministic)
}
func (m *ReqUploadFcmToken) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqUploadFcmToken.Merge(m, src)
}
func (m *ReqUploadFcmToken) XXX_Size() int {
	return xxx_messageInfo_ReqUploadFcmToken.Size(m)
}
func (m *ReqUploadFcmToken) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqUploadFcmToken.DiscardUnknown(m)
}

var xxx_messageInfo_ReqUploadFcmToken proto.InternalMessageInfo

func (m *ReqUploadFcmToken) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func init() {
	proto.RegisterType((*ReqSaveArchive)(nil), "home.req_save_archive")
	proto.RegisterType((*ReqPlayerInfo)(nil), "home.req_player_info")
	proto.RegisterType((*NtfPlayerInfo)(nil), "home.ntf_player_info")
	proto.RegisterType((*ReqSetPlayerInfo)(nil), "home.req_set_player_info")
	proto.RegisterType((*RspSetPlayerInfo)(nil), "home.rsp_set_player_info")
	proto.RegisterType((*ReqIapVerify)(nil), "home.req_iap_verify")
	proto.RegisterType((*ReqRankData)(nil), "home.req_rank_data")
	proto.RegisterType((*ReqMyRankData)(nil), "home.req_my_rank_data")
	proto.RegisterType((*ReqSeasonData)(nil), "home.req_season_data")
	proto.RegisterType((*ReqResetSeason)(nil), "home.req_reset_season")
	proto.RegisterType((*ReqActiveData)(nil), "home.req_active_data")
	proto.RegisterType((*ReqSaveActiveInfo)(nil), "home.req_save_active_info")
	proto.RegisterType((*ReqLuckywheelData)(nil), "home.req_luckywheel_data")
	proto.RegisterType((*ReqRaffleLuckywheel)(nil), "home.req_raffle_luckywheel")
	proto.RegisterType((*ReqDailysignData)(nil), "home.req_dailysign_data")
	proto.RegisterType((*ReqSignIn)(nil), "home.req_sign_in")
	proto.RegisterType((*ReqVideoList)(nil), "home.req_video_list")
	proto.RegisterType((*ReqVideoPlay)(nil), "home.req_video_play")
	proto.RegisterType((*ReqVideoReward)(nil), "home.req_video_reward")
	proto.RegisterType((*ReqProtectWinStreak)(nil), "home.req_protect_win_streak")
	proto.RegisterType((*ReqFriendRewardData)(nil), "home.req_friend_reward_data")
	proto.RegisterType((*ReqSaveFriendReward)(nil), "home.req_save_friend_reward")
	proto.RegisterType((*ReqLotteryFriendReward)(nil), "home.req_lottery_friend_reward")
	proto.RegisterType((*ReqMasterRankData)(nil), "home.req_master_rank_data")
	proto.RegisterType((*ReqMasterMyRank)(nil), "home.req_master_my_rank")
	proto.RegisterType((*ReqMasterCleanOld)(nil), "home.req_master_clean_old")
	proto.RegisterType((*ReqDiamondConsume)(nil), "home.req_diamond_consume")
	proto.RegisterType((*ReqUploadFcmToken)(nil), "home.req_upload_fcm_token")
}

func init() { proto.RegisterFile("home.proto", fileDescriptor_711cc65aaf7510e9) }

var fileDescriptor_711cc65aaf7510e9 = []byte{
	// 638 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe4, 0x54, 0x4f, 0x6f, 0x13, 0x3f,
	0x10, 0x55, 0xda, 0xa4, 0x4d, 0xa6, 0xbf, 0x1f, 0x14, 0xb7, 0x0d, 0x4b, 0xf9, 0x57, 0xed, 0xa9,
	0x02, 0x54, 0x21, 0x38, 0x71, 0x43, 0xc0, 0x25, 0x17, 0x90, 0x02, 0x27, 0x2e, 0x96, 0xbb, 0x9e,
	0x4d, 0xad, 0x78, 0xed, 0xc5, 0xeb, 0xa4, 0xdd, 0x7e, 0x02, 0xbe, 0x2a, 0xdf, 0x02, 0x79, 0xec,
	0x4d, 0xb6, 0x1c, 0xb9, 0x72, 0xda, 0x79, 0xef, 0x8d, 0xc7, 0x9e, 0x99, 0xa7, 0x05, 0xb8, 0xb2,
	0x15, 0x5e, 0xd4, 0xce, 0x7a, 0xcb, 0x86, 0x21, 0x3e, 0xfd, 0xaf, 0xb0, 0x55, 0x65, 0x4d, 0xe4,
	0xf2, 0x4f, 0x70, 0xe8, 0xf0, 0x07, 0x6f, 0xc4, 0x1a, 0xb9, 0x70, 0xc5, 0x95, 0x5a, 0x23, 0x7b,
	0x0d, 0xfb, 0x29, 0xcc, 0x06, 0x67, 0x83, 0xf3, 0x83, 0x37, 0xd3, 0x8b, 0x74, 0x26, 0xd1, 0x1c,
	0x8d, 0x57, 0xbe, 0x9d, 0x77, 0x69, 0xf9, 0x03, 0xb8, 0x1f, 0xaa, 0xd4, 0x5a, 0xb4, 0xe8, 0xb8,
	0x32, 0xa5, 0x0d, 0x94, 0xf1, 0xe5, 0x1d, 0xea, 0xd7, 0x00, 0x8e, 0xe8, 0x32, 0xf4, 0x7d, 0x9e,
	0x3d, 0x03, 0x88, 0xf0, 0xb3, 0xa8, 0xe2, 0x95, 0x93, 0x79, 0x8f, 0x61, 0x0c, 0x86, 0x0b, 0xab,
	0x65, 0xb6, 0x73, 0x36, 0x38, 0x1f, 0xcd, 0x29, 0x66, 0x87, 0xb0, 0xbb, 0xc0, 0x2a, 0xdb, 0x25,
	0x2a, 0x84, 0x81, 0xc1, 0x9b, 0x3a, 0x1b, 0x46, 0x06, 0x6f, 0x6a, 0x76, 0x0c, 0x23, 0x8d, 0x6b,
	0xd4, 0xd9, 0x88, 0xb8, 0x08, 0xc2, 0x6d, 0x42, 0xb9, 0xc2, 0x89, 0xd2, 0xcf, 0x64, 0xb6, 0x47,
	0x52, 0x8f, 0x61, 0x53, 0xd8, 0x73, 0x56, 0xe3, 0x4c, 0x66, 0xfb, 0xa4, 0x25, 0xc4, 0x32, 0xd8,
	0x6f, 0x96, 0xca, 0xcc, 0xe4, 0x4d, 0x36, 0x26, 0xa1, 0x83, 0xe1, 0x7d, 0xa5, 0x16, 0x8b, 0x6c,
	0x42, 0x2f, 0xa7, 0x38, 0xff, 0xb9, 0x03, 0x47, 0xae, 0xa9, 0xff, 0x85, 0x5e, 0xd9, 0x53, 0x00,
	0x74, 0xce, 0x3a, 0x5e, 0x58, 0x89, 0x19, 0xd0, 0x81, 0x09, 0x31, 0x1f, 0xad, 0xc4, 0xfc, 0x10,
	0xee, 0x85, 0xad, 0x2b, 0x51, 0xf3, 0x35, 0x3a, 0x55, 0xb6, 0xf9, 0x3b, 0xf8, 0x3f, 0x30, 0x4e,
	0x98, 0x25, 0x97, 0xc2, 0x8b, 0x50, 0xb5, 0x16, 0x8b, 0x38, 0x8f, 0xd1, 0x9c, 0xe2, 0xd0, 0x51,
	0x61, 0x57, 0xc6, 0xa7, 0x51, 0x44, 0x90, 0xb3, 0xe8, 0xd7, 0xaa, 0xdd, 0x9e, 0xee, 0xdc, 0xd7,
	0xa0, 0x68, 0xac, 0x89, 0x54, 0x4a, 0x73, 0x18, 0xe6, 0x1f, 0x85, 0x2e, 0x4d, 0x14, 0x3e, 0x58,
	0x98, 0xd2, 0xa6, 0x70, 0xbc, 0x75, 0x7f, 0xe4, 0xc9, 0xa9, 0x27, 0xd1, 0xa8, 0x7a, 0x55, 0x2c,
	0xdb, 0xeb, 0x2b, 0x44, 0x1d, 0xd3, 0x1f, 0xc2, 0x49, 0x7c, 0x77, 0x59, 0x6a, 0xec, 0xa9, 0xf9,
	0x31, 0xb0, 0x20, 0x48, 0xa1, 0x74, 0xdb, 0xa8, 0x45, 0x7a, 0xc4, 0x25, 0x1c, 0x50, 0xf5, 0x40,
	0x28, 0x13, 0x86, 0xbd, 0x6a, 0xd0, 0xcd, 0x64, 0x6a, 0x33, 0x21, 0x76, 0x0a, 0x63, 0x21, 0xa5,
	0xf2, 0xca, 0x9a, 0xd4, 0xeb, 0x06, 0xb3, 0xe7, 0x70, 0xe0, 0x55, 0x85, 0xdc, 0x96, 0x65, 0x83,
	0x3e, 0x59, 0x00, 0x02, 0xf5, 0x85, 0x98, 0xfc, 0x36, 0x0e, 0x77, 0xad, 0x24, 0x5a, 0xae, 0x55,
	0xe3, 0xd9, 0x13, 0x98, 0x10, 0xfa, 0xd6, 0xd6, 0xdd, 0x40, 0xb7, 0xc4, 0x66, 0xd2, 0x3b, 0xbd,
	0x49, 0x9f, 0xc2, 0x38, 0x7c, 0xbf, 0xaa, 0x5b, 0x4c, 0x37, 0x6c, 0x70, 0xd0, 0xb4, 0x30, 0x8b,
	0x55, 0x38, 0x33, 0xa4, 0x9d, 0x6f, 0x70, 0xfe, 0xa2, 0x7f, 0x77, 0xf0, 0x70, 0xf0, 0x0d, 0xa1,
	0x4d, 0x8f, 0x1d, 0xec, 0x16, 0x12, 0x73, 0x1d, 0x5e, 0x0b, 0x27, 0xf3, 0x0c, 0xa6, 0xf4, 0xd7,
	0x70, 0xd6, 0x63, 0xe1, 0xf9, 0xb5, 0x32, 0xbc, 0xf1, 0x0e, 0xc5, 0xb2, 0x53, 0x4a, 0xa7, 0xd0,
	0xc8, 0x94, 0x1e, 0x67, 0x9a, 0x14, 0xda, 0xd8, 0x1d, 0x39, 0x7f, 0x0c, 0x8f, 0x68, 0x67, 0xd6,
	0x7b, 0x74, 0xed, 0x1f, 0xe2, 0xfb, 0xb8, 0xe8, 0x4a, 0x34, 0x1e, 0xdd, 0x5f, 0x19, 0x2f, 0xad,
	0x38, 0x55, 0x48, 0xfe, 0xeb, 0x0c, 0x94, 0xd8, 0x42, 0xa3, 0x30, 0xdc, 0x6a, 0x99, 0xbf, 0x8c,
	0x06, 0x92, 0x4a, 0x54, 0xd6, 0x48, 0x5e, 0x58, 0xd3, 0xac, 0xaa, 0x5e, 0xe9, 0x41, 0xbf, 0xf4,
	0xab, 0x58, 0x64, 0x55, 0x6b, 0x2b, 0x24, 0x2f, 0x8b, 0x8a, 0x7b, 0xbb, 0x44, 0x13, 0xb2, 0x29,
	0x48, 0xbf, 0x89, 0x08, 0x3e, 0xc0, 0xf7, 0x31, 0xfd, 0xba, 0x25, 0x96, 0x97, 0x7b, 0x14, 0xbd,
	0xfd, 0x1d, 0x00, 0x00, 0xff, 0xff, 0xae, 0xce, 0x4a, 0x18, 0xe6, 0x05, 0x00, 0x00,
}
