// Code generated by protoc-gen-go. DO NOT EDIT.
// source: league.proto

package protodef

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//创建工会
type ReqCreateLeague struct {
	LeagueName           string   `protobuf:"bytes,1,opt,name=league_name,json=leagueName,proto3" json:"league_name,omitempty"`
	LeagueDesc           string   `protobuf:"bytes,2,opt,name=league_desc,json=leagueDesc,proto3" json:"league_desc,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqCreateLeague) Reset()         { *m = ReqCreateLeague{} }
func (m *ReqCreateLeague) String() string { return proto.CompactTextString(m) }
func (*ReqCreateLeague) ProtoMessage()    {}
func (*ReqCreateLeague) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdb9cfffc57d92f0, []int{0}
}

func (m *ReqCreateLeague) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCreateLeague.Unmarshal(m, b)
}
func (m *ReqCreateLeague) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCreateLeague.Marshal(b, m, deterministic)
}
func (m *ReqCreateLeague) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCreateLeague.Merge(m, src)
}
func (m *ReqCreateLeague) XXX_Size() int {
	return xxx_messageInfo_ReqCreateLeague.Size(m)
}
func (m *ReqCreateLeague) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCreateLeague.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCreateLeague proto.InternalMessageInfo

func (m *ReqCreateLeague) GetLeagueName() string {
	if m != nil {
		return m.LeagueName
	}
	return ""
}

func (m *ReqCreateLeague) GetLeagueDesc() string {
	if m != nil {
		return m.LeagueDesc
	}
	return ""
}

type NtfCreateLeague struct {
	League               *LeagueEntity   `protobuf:"bytes,1,opt,name=league,proto3" json:"league,omitempty"`
	Players              []*LeaguePlayer `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	ErrorCode            int32           `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *NtfCreateLeague) Reset()         { *m = NtfCreateLeague{} }
func (m *NtfCreateLeague) String() string { return proto.CompactTextString(m) }
func (*NtfCreateLeague) ProtoMessage()    {}
func (*NtfCreateLeague) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdb9cfffc57d92f0, []int{1}
}

func (m *NtfCreateLeague) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NtfCreateLeague.Unmarshal(m, b)
}
func (m *NtfCreateLeague) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NtfCreateLeague.Marshal(b, m, deterministic)
}
func (m *NtfCreateLeague) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NtfCreateLeague.Merge(m, src)
}
func (m *NtfCreateLeague) XXX_Size() int {
	return xxx_messageInfo_NtfCreateLeague.Size(m)
}
func (m *NtfCreateLeague) XXX_DiscardUnknown() {
	xxx_messageInfo_NtfCreateLeague.DiscardUnknown(m)
}

var xxx_messageInfo_NtfCreateLeague proto.InternalMessageInfo

func (m *NtfCreateLeague) GetLeague() *LeagueEntity {
	if m != nil {
		return m.League
	}
	return nil
}

func (m *NtfCreateLeague) GetPlayers() []*LeaguePlayer {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *NtfCreateLeague) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

//请求我的工会信息
type ReqMyLeague struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqMyLeague) Reset()         { *m = ReqMyLeague{} }
func (m *ReqMyLeague) String() string { return proto.CompactTextString(m) }
func (*ReqMyLeague) ProtoMessage()    {}
func (*ReqMyLeague) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdb9cfffc57d92f0, []int{2}
}

func (m *ReqMyLeague) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqMyLeague.Unmarshal(m, b)
}
func (m *ReqMyLeague) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqMyLeague.Marshal(b, m, deterministic)
}
func (m *ReqMyLeague) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqMyLeague.Merge(m, src)
}
func (m *ReqMyLeague) XXX_Size() int {
	return xxx_messageInfo_ReqMyLeague.Size(m)
}
func (m *ReqMyLeague) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqMyLeague.DiscardUnknown(m)
}

var xxx_messageInfo_ReqMyLeague proto.InternalMessageInfo

type NtfMyLeague struct {
	League               *LeagueEntity   `protobuf:"bytes,1,opt,name=league,proto3" json:"league,omitempty"`
	Players              []*LeaguePlayer `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	ErrorCode            int32           `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *NtfMyLeague) Reset()         { *m = NtfMyLeague{} }
func (m *NtfMyLeague) String() string { return proto.CompactTextString(m) }
func (*NtfMyLeague) ProtoMessage()    {}
func (*NtfMyLeague) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdb9cfffc57d92f0, []int{3}
}

func (m *NtfMyLeague) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NtfMyLeague.Unmarshal(m, b)
}
func (m *NtfMyLeague) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NtfMyLeague.Marshal(b, m, deterministic)
}
func (m *NtfMyLeague) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NtfMyLeague.Merge(m, src)
}
func (m *NtfMyLeague) XXX_Size() int {
	return xxx_messageInfo_NtfMyLeague.Size(m)
}
func (m *NtfMyLeague) XXX_DiscardUnknown() {
	xxx_messageInfo_NtfMyLeague.DiscardUnknown(m)
}

var xxx_messageInfo_NtfMyLeague proto.InternalMessageInfo

func (m *NtfMyLeague) GetLeague() *LeagueEntity {
	if m != nil {
		return m.League
	}
	return nil
}

func (m *NtfMyLeague) GetPlayers() []*LeaguePlayer {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *NtfMyLeague) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

//解散工会
type ReqDismissLeague struct {
	LeagueId             int32    `protobuf:"varint,1,opt,name=league_id,json=leagueId,proto3" json:"league_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqDismissLeague) Reset()         { *m = ReqDismissLeague{} }
func (m *ReqDismissLeague) String() string { return proto.CompactTextString(m) }
func (*ReqDismissLeague) ProtoMessage()    {}
func (*ReqDismissLeague) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdb9cfffc57d92f0, []int{4}
}

func (m *ReqDismissLeague) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqDismissLeague.Unmarshal(m, b)
}
func (m *ReqDismissLeague) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqDismissLeague.Marshal(b, m, deterministic)
}
func (m *ReqDismissLeague) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqDismissLeague.Merge(m, src)
}
func (m *ReqDismissLeague) XXX_Size() int {
	return xxx_messageInfo_ReqDismissLeague.Size(m)
}
func (m *ReqDismissLeague) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqDismissLeague.DiscardUnknown(m)
}

var xxx_messageInfo_ReqDismissLeague proto.InternalMessageInfo

func (m *ReqDismissLeague) GetLeagueId() int32 {
	if m != nil {
		return m.LeagueId
	}
	return 0
}

type NtfDismissLeague struct {
	CreatorId            int64    `protobuf:"varint,1,opt,name=creator_id,json=creatorId,proto3" json:"creator_id,omitempty"`
	ErrorCode            int32    `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NtfDismissLeague) Reset()         { *m = NtfDismissLeague{} }
func (m *NtfDismissLeague) String() string { return proto.CompactTextString(m) }
func (*NtfDismissLeague) ProtoMessage()    {}
func (*NtfDismissLeague) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdb9cfffc57d92f0, []int{5}
}

func (m *NtfDismissLeague) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NtfDismissLeague.Unmarshal(m, b)
}
func (m *NtfDismissLeague) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NtfDismissLeague.Marshal(b, m, deterministic)
}
func (m *NtfDismissLeague) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NtfDismissLeague.Merge(m, src)
}
func (m *NtfDismissLeague) XXX_Size() int {
	return xxx_messageInfo_NtfDismissLeague.Size(m)
}
func (m *NtfDismissLeague) XXX_DiscardUnknown() {
	xxx_messageInfo_NtfDismissLeague.DiscardUnknown(m)
}

var xxx_messageInfo_NtfDismissLeague proto.InternalMessageInfo

func (m *NtfDismissLeague) GetCreatorId() int64 {
	if m != nil {
		return m.CreatorId
	}
	return 0
}

func (m *NtfDismissLeague) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

//邀请别人加入我的工会
type ReqInviteOtherJoinLeague struct {
	PlayerId             int64    `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqInviteOtherJoinLeague) Reset()         { *m = ReqInviteOtherJoinLeague{} }
func (m *ReqInviteOtherJoinLeague) String() string { return proto.CompactTextString(m) }
func (*ReqInviteOtherJoinLeague) ProtoMessage()    {}
func (*ReqInviteOtherJoinLeague) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdb9cfffc57d92f0, []int{6}
}

func (m *ReqInviteOtherJoinLeague) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqInviteOtherJoinLeague.Unmarshal(m, b)
}
func (m *ReqInviteOtherJoinLeague) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqInviteOtherJoinLeague.Marshal(b, m, deterministic)
}
func (m *ReqInviteOtherJoinLeague) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqInviteOtherJoinLeague.Merge(m, src)
}
func (m *ReqInviteOtherJoinLeague) XXX_Size() int {
	return xxx_messageInfo_ReqInviteOtherJoinLeague.Size(m)
}
func (m *ReqInviteOtherJoinLeague) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqInviteOtherJoinLeague.DiscardUnknown(m)
}

var xxx_messageInfo_ReqInviteOtherJoinLeague proto.InternalMessageInfo

func (m *ReqInviteOtherJoinLeague) GetPlayerId() int64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

type NtfInviteOtherJoinLeague struct {
	ErrorCode            int32         `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	PlayerId             int32         `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	Player               *LeaguePlayer `protobuf:"bytes,3,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *NtfInviteOtherJoinLeague) Reset()         { *m = NtfInviteOtherJoinLeague{} }
func (m *NtfInviteOtherJoinLeague) String() string { return proto.CompactTextString(m) }
func (*NtfInviteOtherJoinLeague) ProtoMessage()    {}
func (*NtfInviteOtherJoinLeague) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdb9cfffc57d92f0, []int{7}
}

func (m *NtfInviteOtherJoinLeague) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NtfInviteOtherJoinLeague.Unmarshal(m, b)
}
func (m *NtfInviteOtherJoinLeague) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NtfInviteOtherJoinLeague.Marshal(b, m, deterministic)
}
func (m *NtfInviteOtherJoinLeague) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NtfInviteOtherJoinLeague.Merge(m, src)
}
func (m *NtfInviteOtherJoinLeague) XXX_Size() int {
	return xxx_messageInfo_NtfInviteOtherJoinLeague.Size(m)
}
func (m *NtfInviteOtherJoinLeague) XXX_DiscardUnknown() {
	xxx_messageInfo_NtfInviteOtherJoinLeague.DiscardUnknown(m)
}

var xxx_messageInfo_NtfInviteOtherJoinLeague proto.InternalMessageInfo

func (m *NtfInviteOtherJoinLeague) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *NtfInviteOtherJoinLeague) GetPlayerId() int32 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *NtfInviteOtherJoinLeague) GetPlayer() *LeaguePlayer {
	if m != nil {
		return m.Player
	}
	return nil
}

//别人邀请我加入他的工会
type NtfInviteMeJoinLeague struct {
	League               *LeagueEntity `protobuf:"bytes,1,opt,name=league,proto3" json:"league,omitempty"`
	Creator              *LeaguePlayer `protobuf:"bytes,2,opt,name=creator,proto3" json:"creator,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *NtfInviteMeJoinLeague) Reset()         { *m = NtfInviteMeJoinLeague{} }
func (m *NtfInviteMeJoinLeague) String() string { return proto.CompactTextString(m) }
func (*NtfInviteMeJoinLeague) ProtoMessage()    {}
func (*NtfInviteMeJoinLeague) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdb9cfffc57d92f0, []int{8}
}

func (m *NtfInviteMeJoinLeague) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NtfInviteMeJoinLeague.Unmarshal(m, b)
}
func (m *NtfInviteMeJoinLeague) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NtfInviteMeJoinLeague.Marshal(b, m, deterministic)
}
func (m *NtfInviteMeJoinLeague) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NtfInviteMeJoinLeague.Merge(m, src)
}
func (m *NtfInviteMeJoinLeague) XXX_Size() int {
	return xxx_messageInfo_NtfInviteMeJoinLeague.Size(m)
}
func (m *NtfInviteMeJoinLeague) XXX_DiscardUnknown() {
	xxx_messageInfo_NtfInviteMeJoinLeague.DiscardUnknown(m)
}

var xxx_messageInfo_NtfInviteMeJoinLeague proto.InternalMessageInfo

func (m *NtfInviteMeJoinLeague) GetLeague() *LeagueEntity {
	if m != nil {
		return m.League
	}
	return nil
}

func (m *NtfInviteMeJoinLeague) GetCreator() *LeaguePlayer {
	if m != nil {
		return m.Creator
	}
	return nil
}

//请求加入工会
type ReqJoinLeague struct {
	LeagueCode           string   `protobuf:"bytes,1,opt,name=league_code,json=leagueCode,proto3" json:"league_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqJoinLeague) Reset()         { *m = ReqJoinLeague{} }
func (m *ReqJoinLeague) String() string { return proto.CompactTextString(m) }
func (*ReqJoinLeague) ProtoMessage()    {}
func (*ReqJoinLeague) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdb9cfffc57d92f0, []int{9}
}

func (m *ReqJoinLeague) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqJoinLeague.Unmarshal(m, b)
}
func (m *ReqJoinLeague) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqJoinLeague.Marshal(b, m, deterministic)
}
func (m *ReqJoinLeague) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqJoinLeague.Merge(m, src)
}
func (m *ReqJoinLeague) XXX_Size() int {
	return xxx_messageInfo_ReqJoinLeague.Size(m)
}
func (m *ReqJoinLeague) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqJoinLeague.DiscardUnknown(m)
}

var xxx_messageInfo_ReqJoinLeague proto.InternalMessageInfo

func (m *ReqJoinLeague) GetLeagueCode() string {
	if m != nil {
		return m.LeagueCode
	}
	return ""
}

type NtfJoinLeague struct {
	League               *LeagueEntity   `protobuf:"bytes,1,opt,name=league,proto3" json:"league,omitempty"`
	Players              []*LeaguePlayer `protobuf:"bytes,2,rep,name=players,proto3" json:"players,omitempty"`
	ErrorCode            int32           `protobuf:"varint,3,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *NtfJoinLeague) Reset()         { *m = NtfJoinLeague{} }
func (m *NtfJoinLeague) String() string { return proto.CompactTextString(m) }
func (*NtfJoinLeague) ProtoMessage()    {}
func (*NtfJoinLeague) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdb9cfffc57d92f0, []int{10}
}

func (m *NtfJoinLeague) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NtfJoinLeague.Unmarshal(m, b)
}
func (m *NtfJoinLeague) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NtfJoinLeague.Marshal(b, m, deterministic)
}
func (m *NtfJoinLeague) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NtfJoinLeague.Merge(m, src)
}
func (m *NtfJoinLeague) XXX_Size() int {
	return xxx_messageInfo_NtfJoinLeague.Size(m)
}
func (m *NtfJoinLeague) XXX_DiscardUnknown() {
	xxx_messageInfo_NtfJoinLeague.DiscardUnknown(m)
}

var xxx_messageInfo_NtfJoinLeague proto.InternalMessageInfo

func (m *NtfJoinLeague) GetLeague() *LeagueEntity {
	if m != nil {
		return m.League
	}
	return nil
}

func (m *NtfJoinLeague) GetPlayers() []*LeaguePlayer {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *NtfJoinLeague) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

//请求离开工会
type ReqLeaveLeague struct {
	LeagueId             int32    `protobuf:"varint,1,opt,name=league_id,json=leagueId,proto3" json:"league_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqLeaveLeague) Reset()         { *m = ReqLeaveLeague{} }
func (m *ReqLeaveLeague) String() string { return proto.CompactTextString(m) }
func (*ReqLeaveLeague) ProtoMessage()    {}
func (*ReqLeaveLeague) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdb9cfffc57d92f0, []int{11}
}

func (m *ReqLeaveLeague) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqLeaveLeague.Unmarshal(m, b)
}
func (m *ReqLeaveLeague) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqLeaveLeague.Marshal(b, m, deterministic)
}
func (m *ReqLeaveLeague) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqLeaveLeague.Merge(m, src)
}
func (m *ReqLeaveLeague) XXX_Size() int {
	return xxx_messageInfo_ReqLeaveLeague.Size(m)
}
func (m *ReqLeaveLeague) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqLeaveLeague.DiscardUnknown(m)
}

var xxx_messageInfo_ReqLeaveLeague proto.InternalMessageInfo

func (m *ReqLeaveLeague) GetLeagueId() int32 {
	if m != nil {
		return m.LeagueId
	}
	return 0
}

type NtfLeaveLeague struct {
	ErrorCode            int32         `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Player               *LeaguePlayer `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *NtfLeaveLeague) Reset()         { *m = NtfLeaveLeague{} }
func (m *NtfLeaveLeague) String() string { return proto.CompactTextString(m) }
func (*NtfLeaveLeague) ProtoMessage()    {}
func (*NtfLeaveLeague) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdb9cfffc57d92f0, []int{12}
}

func (m *NtfLeaveLeague) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NtfLeaveLeague.Unmarshal(m, b)
}
func (m *NtfLeaveLeague) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NtfLeaveLeague.Marshal(b, m, deterministic)
}
func (m *NtfLeaveLeague) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NtfLeaveLeague.Merge(m, src)
}
func (m *NtfLeaveLeague) XXX_Size() int {
	return xxx_messageInfo_NtfLeaveLeague.Size(m)
}
func (m *NtfLeaveLeague) XXX_DiscardUnknown() {
	xxx_messageInfo_NtfLeaveLeague.DiscardUnknown(m)
}

var xxx_messageInfo_NtfLeaveLeague proto.InternalMessageInfo

func (m *NtfLeaveLeague) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *NtfLeaveLeague) GetPlayer() *LeaguePlayer {
	if m != nil {
		return m.Player
	}
	return nil
}

//请求工会列表
type ReqLeagueList struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqLeagueList) Reset()         { *m = ReqLeagueList{} }
func (m *ReqLeagueList) String() string { return proto.CompactTextString(m) }
func (*ReqLeagueList) ProtoMessage()    {}
func (*ReqLeagueList) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdb9cfffc57d92f0, []int{13}
}

func (m *ReqLeagueList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqLeagueList.Unmarshal(m, b)
}
func (m *ReqLeagueList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqLeagueList.Marshal(b, m, deterministic)
}
func (m *ReqLeagueList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqLeagueList.Merge(m, src)
}
func (m *ReqLeagueList) XXX_Size() int {
	return xxx_messageInfo_ReqLeagueList.Size(m)
}
func (m *ReqLeagueList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqLeagueList.DiscardUnknown(m)
}

var xxx_messageInfo_ReqLeagueList proto.InternalMessageInfo

func (m *ReqLeagueList) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ReqLeagueList) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type NtfLeagueList struct {
	Leagues              []*LeagueEntity `protobuf:"bytes,1,rep,name=leagues,proto3" json:"leagues,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *NtfLeagueList) Reset()         { *m = NtfLeagueList{} }
func (m *NtfLeagueList) String() string { return proto.CompactTextString(m) }
func (*NtfLeagueList) ProtoMessage()    {}
func (*NtfLeagueList) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdb9cfffc57d92f0, []int{14}
}

func (m *NtfLeagueList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NtfLeagueList.Unmarshal(m, b)
}
func (m *NtfLeagueList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NtfLeagueList.Marshal(b, m, deterministic)
}
func (m *NtfLeagueList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NtfLeagueList.Merge(m, src)
}
func (m *NtfLeagueList) XXX_Size() int {
	return xxx_messageInfo_NtfLeagueList.Size(m)
}
func (m *NtfLeagueList) XXX_DiscardUnknown() {
	xxx_messageInfo_NtfLeagueList.DiscardUnknown(m)
}

var xxx_messageInfo_NtfLeagueList proto.InternalMessageInfo

func (m *NtfLeagueList) GetLeagues() []*LeagueEntity {
	if m != nil {
		return m.Leagues
	}
	return nil
}

//请求邀请玩家列表
type ReqInvitePlayerList struct {
	Page                 int32    `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqInvitePlayerList) Reset()         { *m = ReqInvitePlayerList{} }
func (m *ReqInvitePlayerList) String() string { return proto.CompactTextString(m) }
func (*ReqInvitePlayerList) ProtoMessage()    {}
func (*ReqInvitePlayerList) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdb9cfffc57d92f0, []int{15}
}

func (m *ReqInvitePlayerList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqInvitePlayerList.Unmarshal(m, b)
}
func (m *ReqInvitePlayerList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqInvitePlayerList.Marshal(b, m, deterministic)
}
func (m *ReqInvitePlayerList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqInvitePlayerList.Merge(m, src)
}
func (m *ReqInvitePlayerList) XXX_Size() int {
	return xxx_messageInfo_ReqInvitePlayerList.Size(m)
}
func (m *ReqInvitePlayerList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqInvitePlayerList.DiscardUnknown(m)
}

var xxx_messageInfo_ReqInvitePlayerList proto.InternalMessageInfo

func (m *ReqInvitePlayerList) GetPage() int32 {
	if m != nil {
		return m.Page
	}
	return 0
}

func (m *ReqInvitePlayerList) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

type NtfInvitePlayerList struct {
	Players              []*LeaguePlayer `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *NtfInvitePlayerList) Reset()         { *m = NtfInvitePlayerList{} }
func (m *NtfInvitePlayerList) String() string { return proto.CompactTextString(m) }
func (*NtfInvitePlayerList) ProtoMessage()    {}
func (*NtfInvitePlayerList) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdb9cfffc57d92f0, []int{16}
}

func (m *NtfInvitePlayerList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NtfInvitePlayerList.Unmarshal(m, b)
}
func (m *NtfInvitePlayerList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NtfInvitePlayerList.Marshal(b, m, deterministic)
}
func (m *NtfInvitePlayerList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NtfInvitePlayerList.Merge(m, src)
}
func (m *NtfInvitePlayerList) XXX_Size() int {
	return xxx_messageInfo_NtfInvitePlayerList.Size(m)
}
func (m *NtfInvitePlayerList) XXX_DiscardUnknown() {
	xxx_messageInfo_NtfInvitePlayerList.DiscardUnknown(m)
}

var xxx_messageInfo_NtfInvitePlayerList proto.InternalMessageInfo

func (m *NtfInvitePlayerList) GetPlayers() []*LeaguePlayer {
	if m != nil {
		return m.Players
	}
	return nil
}

//邮件
type ReqMailList struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqMailList) Reset()         { *m = ReqMailList{} }
func (m *ReqMailList) String() string { return proto.CompactTextString(m) }
func (*ReqMailList) ProtoMessage()    {}
func (*ReqMailList) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdb9cfffc57d92f0, []int{17}
}

func (m *ReqMailList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqMailList.Unmarshal(m, b)
}
func (m *ReqMailList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqMailList.Marshal(b, m, deterministic)
}
func (m *ReqMailList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqMailList.Merge(m, src)
}
func (m *ReqMailList) XXX_Size() int {
	return xxx_messageInfo_ReqMailList.Size(m)
}
func (m *ReqMailList) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqMailList.DiscardUnknown(m)
}

var xxx_messageInfo_ReqMailList proto.InternalMessageInfo

//3219=league.ntf_mail
type NtfMail struct {
	ErrorCode            int32       `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Mail                 *MailEntity `protobuf:"bytes,2,opt,name=mail,proto3" json:"mail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *NtfMail) Reset()         { *m = NtfMail{} }
func (m *NtfMail) String() string { return proto.CompactTextString(m) }
func (*NtfMail) ProtoMessage()    {}
func (*NtfMail) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdb9cfffc57d92f0, []int{18}
}

func (m *NtfMail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NtfMail.Unmarshal(m, b)
}
func (m *NtfMail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NtfMail.Marshal(b, m, deterministic)
}
func (m *NtfMail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NtfMail.Merge(m, src)
}
func (m *NtfMail) XXX_Size() int {
	return xxx_messageInfo_NtfMail.Size(m)
}
func (m *NtfMail) XXX_DiscardUnknown() {
	xxx_messageInfo_NtfMail.DiscardUnknown(m)
}

var xxx_messageInfo_NtfMail proto.InternalMessageInfo

func (m *NtfMail) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *NtfMail) GetMail() *MailEntity {
	if m != nil {
		return m.Mail
	}
	return nil
}

//3221=league.rsp_mail_list
type RspMailList struct {
	ErrorCode            int32         `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Mails                []*MailEntity `protobuf:"bytes,2,rep,name=mails,proto3" json:"mails,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *RspMailList) Reset()         { *m = RspMailList{} }
func (m *RspMailList) String() string { return proto.CompactTextString(m) }
func (*RspMailList) ProtoMessage()    {}
func (*RspMailList) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdb9cfffc57d92f0, []int{19}
}

func (m *RspMailList) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspMailList.Unmarshal(m, b)
}
func (m *RspMailList) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspMailList.Marshal(b, m, deterministic)
}
func (m *RspMailList) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspMailList.Merge(m, src)
}
func (m *RspMailList) XXX_Size() int {
	return xxx_messageInfo_RspMailList.Size(m)
}
func (m *RspMailList) XXX_DiscardUnknown() {
	xxx_messageInfo_RspMailList.DiscardUnknown(m)
}

var xxx_messageInfo_RspMailList proto.InternalMessageInfo

func (m *RspMailList) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *RspMailList) GetMails() []*MailEntity {
	if m != nil {
		return m.Mails
	}
	return nil
}

type ReqDeleteMail struct {
	MailId               int64    `protobuf:"varint,1,opt,name=mail_id,json=mailId,proto3" json:"mail_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqDeleteMail) Reset()         { *m = ReqDeleteMail{} }
func (m *ReqDeleteMail) String() string { return proto.CompactTextString(m) }
func (*ReqDeleteMail) ProtoMessage()    {}
func (*ReqDeleteMail) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdb9cfffc57d92f0, []int{20}
}

func (m *ReqDeleteMail) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqDeleteMail.Unmarshal(m, b)
}
func (m *ReqDeleteMail) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqDeleteMail.Marshal(b, m, deterministic)
}
func (m *ReqDeleteMail) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqDeleteMail.Merge(m, src)
}
func (m *ReqDeleteMail) XXX_Size() int {
	return xxx_messageInfo_ReqDeleteMail.Size(m)
}
func (m *ReqDeleteMail) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqDeleteMail.DiscardUnknown(m)
}

var xxx_messageInfo_ReqDeleteMail proto.InternalMessageInfo

func (m *ReqDeleteMail) GetMailId() int64 {
	if m != nil {
		return m.MailId
	}
	return 0
}

//工会异常
type NtfLeagueError struct {
	ErrorCode            int32    `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NtfLeagueError) Reset()         { *m = NtfLeagueError{} }
func (m *NtfLeagueError) String() string { return proto.CompactTextString(m) }
func (*NtfLeagueError) ProtoMessage()    {}
func (*NtfLeagueError) Descriptor() ([]byte, []int) {
	return fileDescriptor_bdb9cfffc57d92f0, []int{21}
}

func (m *NtfLeagueError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NtfLeagueError.Unmarshal(m, b)
}
func (m *NtfLeagueError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NtfLeagueError.Marshal(b, m, deterministic)
}
func (m *NtfLeagueError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NtfLeagueError.Merge(m, src)
}
func (m *NtfLeagueError) XXX_Size() int {
	return xxx_messageInfo_NtfLeagueError.Size(m)
}
func (m *NtfLeagueError) XXX_DiscardUnknown() {
	xxx_messageInfo_NtfLeagueError.DiscardUnknown(m)
}

var xxx_messageInfo_NtfLeagueError proto.InternalMessageInfo

func (m *NtfLeagueError) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func init() {
	proto.RegisterType((*ReqCreateLeague)(nil), "league.req_create_league")
	proto.RegisterType((*NtfCreateLeague)(nil), "league.ntf_create_league")
	proto.RegisterType((*ReqMyLeague)(nil), "league.req_my_league")
	proto.RegisterType((*NtfMyLeague)(nil), "league.ntf_my_league")
	proto.RegisterType((*ReqDismissLeague)(nil), "league.req_dismiss_league")
	proto.RegisterType((*NtfDismissLeague)(nil), "league.ntf_dismiss_league")
	proto.RegisterType((*ReqInviteOtherJoinLeague)(nil), "league.req_invite_other_join_league")
	proto.RegisterType((*NtfInviteOtherJoinLeague)(nil), "league.ntf_invite_other_join_league")
	proto.RegisterType((*NtfInviteMeJoinLeague)(nil), "league.ntf_invite_me_join_league")
	proto.RegisterType((*ReqJoinLeague)(nil), "league.req_join_league")
	proto.RegisterType((*NtfJoinLeague)(nil), "league.ntf_join_league")
	proto.RegisterType((*ReqLeaveLeague)(nil), "league.req_leave_league")
	proto.RegisterType((*NtfLeaveLeague)(nil), "league.ntf_leave_league")
	proto.RegisterType((*ReqLeagueList)(nil), "league.req_league_list")
	proto.RegisterType((*NtfLeagueList)(nil), "league.ntf_league_list")
	proto.RegisterType((*ReqInvitePlayerList)(nil), "league.req_invite_player_list")
	proto.RegisterType((*NtfInvitePlayerList)(nil), "league.ntf_invite_player_list")
	proto.RegisterType((*ReqMailList)(nil), "league.req_mail_list")
	proto.RegisterType((*NtfMail)(nil), "league.ntf_mail")
	proto.RegisterType((*RspMailList)(nil), "league.rsp_mail_list")
	proto.RegisterType((*ReqDeleteMail)(nil), "league.req_delete_mail")
	proto.RegisterType((*NtfLeagueError)(nil), "league.ntf_league_error")
}

func init() { proto.RegisterFile("league.proto", fileDescriptor_bdb9cfffc57d92f0) }

var fileDescriptor_bdb9cfffc57d92f0 = []byte{
	// 568 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xc4, 0x55, 0x4d, 0x6f, 0xd3, 0x40,
	0x10, 0xd5, 0x26, 0xcd, 0xd7, 0xb4, 0x51, 0x5a, 0x03, 0xc5, 0x40, 0x2b, 0xa2, 0xbd, 0x50, 0x90,
	0x68, 0xd4, 0x72, 0xec, 0x2d, 0x70, 0xf1, 0x85, 0x83, 0x25, 0x0e, 0x70, 0x31, 0xc6, 0x3b, 0x2d,
	0x8b, 0x6c, 0x6f, 0x58, 0xbb, 0x95, 0x22, 0x7e, 0x01, 0x17, 0x84, 0xf8, 0xc5, 0x68, 0x3f, 0xec,
	0x6c, 0xac, 0x44, 0x49, 0x04, 0x52, 0x6f, 0xbb, 0xe3, 0xb7, 0x6f, 0xde, 0xbc, 0x99, 0x5d, 0xc3,
	0x41, 0x8a, 0xf1, 0xcd, 0x2d, 0x9e, 0xcf, 0xa4, 0x28, 0x85, 0xd7, 0x35, 0xbb, 0xa7, 0x07, 0x89,
	0xc8, 0x32, 0x91, 0x9b, 0x28, 0xfd, 0x00, 0x47, 0x12, 0xbf, 0x47, 0x89, 0xc4, 0xb8, 0xc4, 0xc8,
	0x40, 0xbc, 0xe7, 0xb0, 0x6f, 0x56, 0x51, 0x1e, 0x67, 0xe8, 0x93, 0x31, 0x39, 0x1b, 0x84, 0x60,
	0x42, 0xef, 0xe3, 0xcc, 0x05, 0x30, 0x2c, 0x12, 0xbf, 0xe5, 0x02, 0xde, 0x61, 0x91, 0xd0, 0x3f,
	0x04, 0x8e, 0xf2, 0xf2, 0xba, 0xc1, 0xfb, 0x1a, 0xac, 0x08, 0x4d, 0xb9, 0x7f, 0xf9, 0xe8, 0xdc,
	0x6a, 0xb1, 0x64, 0x98, 0x97, 0xbc, 0x9c, 0x87, 0x16, 0xe4, 0x4d, 0xa0, 0x37, 0x4b, 0xe3, 0x39,
	0xca, 0xc2, 0x6f, 0x8d, 0xdb, 0x2b, 0xf0, 0xe6, 0x6b, 0x58, 0xa1, 0xbc, 0x53, 0x00, 0x94, 0x52,
	0xc8, 0x28, 0x11, 0x0c, 0xfd, 0xf6, 0x98, 0x9c, 0x75, 0xc2, 0x81, 0x8e, 0xbc, 0x15, 0x0c, 0xe9,
	0x08, 0x86, 0xaa, 0xd6, 0x6c, 0x6e, 0xf5, 0xd0, 0x5f, 0x04, 0x86, 0x4a, 0x65, 0x1d, 0xb9, 0x6f,
	0x85, 0x17, 0xe0, 0x29, 0x85, 0x8c, 0x17, 0x19, 0x2f, 0x8a, 0x4a, 0xd4, 0x33, 0x18, 0x58, 0x3a,
	0xce, 0xb4, 0xae, 0x4e, 0xd8, 0x37, 0x81, 0x80, 0xd1, 0x10, 0x3c, 0x55, 0x42, 0xe3, 0xc8, 0x29,
	0x80, 0xb6, 0x5e, 0xc8, 0xea, 0x4c, 0x3b, 0x1c, 0xd8, 0x48, 0xc0, 0x1a, 0x32, 0x5a, 0x4d, 0x19,
	0x57, 0x70, 0xa2, 0x64, 0xf0, 0xfc, 0x8e, 0x97, 0x18, 0x89, 0xf2, 0x2b, 0xca, 0xe8, 0x9b, 0xe0,
	0xb9, 0x23, 0xc8, 0x14, 0xb4, 0x20, 0xef, 0x9b, 0x40, 0xc0, 0xe8, 0x4f, 0x02, 0x27, 0x4a, 0xd1,
	0xda, 0xd3, 0xcb, 0xc9, 0x49, 0x23, 0xf9, 0x32, 0xb9, 0x91, 0x56, 0x93, 0xab, 0xfe, 0x98, 0xb5,
	0xf6, 0x6e, 0xad, 0xdf, 0x16, 0x44, 0x7f, 0xc0, 0x13, 0x47, 0x4a, 0x86, 0x4b, 0x3a, 0x76, 0xef,
	0xb5, 0x35, 0x50, 0xab, 0x5a, 0xdf, 0x6b, 0x8b, 0xa2, 0x97, 0x30, 0x52, 0x2e, 0xba, 0x29, 0x17,
	0xf7, 0xa6, 0xae, 0xbd, 0xbe, 0x37, 0xda, 0xf9, 0xdf, 0x04, 0x46, 0x4a, 0xf1, 0xbf, 0xe9, 0xfc,
	0xaf, 0x33, 0x39, 0x81, 0x43, 0x55, 0x46, 0x8a, 0xf1, 0x1d, 0x6e, 0x35, 0x91, 0x9f, 0xe1, 0x50,
	0x95, 0xb0, 0x74, 0x60, 0x43, 0xcf, 0x17, 0x6d, 0x6d, 0x6d, 0xd3, 0xd6, 0x2b, 0xe3, 0xac, 0xfd,
	0x98, 0xf2, 0xa2, 0xf4, 0x3c, 0xd8, 0x9b, 0xc5, 0x37, 0x15, 0xb5, 0x5e, 0x7b, 0x0f, 0xa1, 0x93,
	0x88, 0xdb, 0xbc, 0xb4, 0x53, 0x64, 0x36, 0x74, 0x6a, 0x1c, 0x76, 0x0f, 0x4f, 0xa0, 0x67, 0xb6,
	0x85, 0x4f, 0x56, 0x5a, 0x66, 0x2d, 0xae, 0x50, 0x74, 0x0a, 0xc7, 0xce, 0x05, 0xb1, 0xe3, 0xba,
	0xa3, 0x8e, 0x00, 0x8e, 0x9d, 0xd9, 0x74, 0x39, 0x9c, 0x0e, 0x92, 0x6d, 0x3a, 0x58, 0x3f, 0x6c,
	0x31, 0x4f, 0x35, 0x03, 0x0d, 0xa1, 0xaf, 0xdf, 0xb5, 0x98, 0xa7, 0x9b, 0xac, 0x7f, 0x01, 0x7b,
	0x0a, 0x66, 0x8d, 0x7f, 0x50, 0x65, 0xd2, 0x5c, 0xb6, 0x6c, 0x0d, 0xa0, 0x1f, 0x61, 0x28, 0x8b,
	0xd9, 0x22, 0xc9, 0x26, 0xe2, 0x97, 0xd0, 0x51, 0xd8, 0x6a, 0x0a, 0x57, 0x32, 0x1b, 0x04, 0x7d,
	0x65, 0xfa, 0xc9, 0x30, 0x45, 0x75, 0x4d, 0x95, 0xea, 0xc7, 0xd0, 0xd3, 0xc0, 0xfa, 0x81, 0xe9,
	0xaa, 0x6d, 0xc0, 0xe8, 0x45, 0x3d, 0x5d, 0xba, 0x31, 0x2a, 0xdd, 0x06, 0x25, 0x53, 0xf8, 0xd4,
	0xd7, 0x3f, 0x3b, 0x86, 0xd7, 0x5f, 0xba, 0x7a, 0xf5, 0xe6, 0x6f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xb3, 0xd8, 0xd9, 0xd0, 0x1c, 0x07, 0x00, 0x00,
}
