// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

package protodef

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//登录
type ReqLogin struct {
	Idfa                 string   `protobuf:"bytes,1,opt,name=idfa,proto3" json:"idfa,omitempty"`
	Idfv                 string   `protobuf:"bytes,2,opt,name=idfv,proto3" json:"idfv,omitempty"`
	Guid                 string   `protobuf:"bytes,3,opt,name=guid,proto3" json:"guid,omitempty"`
	Device               string   `protobuf:"bytes,4,opt,name=device,proto3" json:"device,omitempty"`
	Platform             string   `protobuf:"bytes,5,opt,name=platform,proto3" json:"platform,omitempty"`
	OpenType             string   `protobuf:"bytes,6,opt,name=openType,proto3" json:"openType,omitempty"`
	OpenId               string   `protobuf:"bytes,7,opt,name=openId,proto3" json:"openId,omitempty"`
	Token                string   `protobuf:"bytes,8,opt,name=token,proto3" json:"token,omitempty"`
	AppVersion           string   `protobuf:"bytes,9,opt,name=appVersion,proto3" json:"appVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqLogin) Reset()         { *m = ReqLogin{} }
func (m *ReqLogin) String() string { return proto.CompactTextString(m) }
func (*ReqLogin) ProtoMessage()    {}
func (*ReqLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{0}
}

func (m *ReqLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqLogin.Unmarshal(m, b)
}
func (m *ReqLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqLogin.Marshal(b, m, deterministic)
}
func (m *ReqLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqLogin.Merge(m, src)
}
func (m *ReqLogin) XXX_Size() int {
	return xxx_messageInfo_ReqLogin.Size(m)
}
func (m *ReqLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqLogin.DiscardUnknown(m)
}

var xxx_messageInfo_ReqLogin proto.InternalMessageInfo

func (m *ReqLogin) GetIdfa() string {
	if m != nil {
		return m.Idfa
	}
	return ""
}

func (m *ReqLogin) GetIdfv() string {
	if m != nil {
		return m.Idfv
	}
	return ""
}

func (m *ReqLogin) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func (m *ReqLogin) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *ReqLogin) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *ReqLogin) GetOpenType() string {
	if m != nil {
		return m.OpenType
	}
	return ""
}

func (m *ReqLogin) GetOpenId() string {
	if m != nil {
		return m.OpenId
	}
	return ""
}

func (m *ReqLogin) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *ReqLogin) GetAppVersion() string {
	if m != nil {
		return m.AppVersion
	}
	return ""
}

//登录rsp
type RspLogin struct {
	Token                string         `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	PlayerId             int64          `protobuf:"varint,2,opt,name=playerId,proto3" json:"playerId,omitempty"`
	PlayerName           string         `protobuf:"bytes,3,opt,name=playerName,proto3" json:"playerName,omitempty"`
	DataVersion          int64          `protobuf:"varint,4,opt,name=data_version,json=dataVersion,proto3" json:"data_version,omitempty"`
	GameState            int32          `protobuf:"varint,5,opt,name=gameState,proto3" json:"gameState,omitempty"`
	GameType             int32          `protobuf:"varint,6,opt,name=gameType,proto3" json:"gameType,omitempty"`
	IsNew                bool           `protobuf:"varint,7,opt,name=isNew,proto3" json:"isNew,omitempty"`
	Reward               string         `protobuf:"bytes,8,opt,name=reward,proto3" json:"reward,omitempty"`
	ErrorCode            int32          `protobuf:"varint,9,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Archive              *ArchiveEntity `protobuf:"bytes,10,opt,name=archive,proto3" json:"archive,omitempty"`
	Attri                *AttriEntity   `protobuf:"bytes,11,opt,name=attri,proto3" json:"attri,omitempty"`
	UserSig              string         `protobuf:"bytes,12,opt,name=userSig,proto3" json:"userSig,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *RspLogin) Reset()         { *m = RspLogin{} }
func (m *RspLogin) String() string { return proto.CompactTextString(m) }
func (*RspLogin) ProtoMessage()    {}
func (*RspLogin) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{1}
}

func (m *RspLogin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspLogin.Unmarshal(m, b)
}
func (m *RspLogin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspLogin.Marshal(b, m, deterministic)
}
func (m *RspLogin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspLogin.Merge(m, src)
}
func (m *RspLogin) XXX_Size() int {
	return xxx_messageInfo_RspLogin.Size(m)
}
func (m *RspLogin) XXX_DiscardUnknown() {
	xxx_messageInfo_RspLogin.DiscardUnknown(m)
}

var xxx_messageInfo_RspLogin proto.InternalMessageInfo

func (m *RspLogin) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RspLogin) GetPlayerId() int64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *RspLogin) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *RspLogin) GetDataVersion() int64 {
	if m != nil {
		return m.DataVersion
	}
	return 0
}

func (m *RspLogin) GetGameState() int32 {
	if m != nil {
		return m.GameState
	}
	return 0
}

func (m *RspLogin) GetGameType() int32 {
	if m != nil {
		return m.GameType
	}
	return 0
}

func (m *RspLogin) GetIsNew() bool {
	if m != nil {
		return m.IsNew
	}
	return false
}

func (m *RspLogin) GetReward() string {
	if m != nil {
		return m.Reward
	}
	return ""
}

func (m *RspLogin) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *RspLogin) GetArchive() *ArchiveEntity {
	if m != nil {
		return m.Archive
	}
	return nil
}

func (m *RspLogin) GetAttri() *AttriEntity {
	if m != nil {
		return m.Attri
	}
	return nil
}

func (m *RspLogin) GetUserSig() string {
	if m != nil {
		return m.UserSig
	}
	return ""
}

//服务端提示消息
type NtfMsgTip struct {
	Title                string   `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Button               string   `protobuf:"bytes,3,opt,name=button,proto3" json:"button,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NtfMsgTip) Reset()         { *m = NtfMsgTip{} }
func (m *NtfMsgTip) String() string { return proto.CompactTextString(m) }
func (*NtfMsgTip) ProtoMessage()    {}
func (*NtfMsgTip) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{2}
}

func (m *NtfMsgTip) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NtfMsgTip.Unmarshal(m, b)
}
func (m *NtfMsgTip) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NtfMsgTip.Marshal(b, m, deterministic)
}
func (m *NtfMsgTip) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NtfMsgTip.Merge(m, src)
}
func (m *NtfMsgTip) XXX_Size() int {
	return xxx_messageInfo_NtfMsgTip.Size(m)
}
func (m *NtfMsgTip) XXX_DiscardUnknown() {
	xxx_messageInfo_NtfMsgTip.DiscardUnknown(m)
}

var xxx_messageInfo_NtfMsgTip proto.InternalMessageInfo

func (m *NtfMsgTip) GetTitle() string {
	if m != nil {
		return m.Title
	}
	return ""
}

func (m *NtfMsgTip) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *NtfMsgTip) GetButton() string {
	if m != nil {
		return m.Button
	}
	return ""
}

// 心跳
type ReqHeart struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqHeart) Reset()         { *m = ReqHeart{} }
func (m *ReqHeart) String() string { return proto.CompactTextString(m) }
func (*ReqHeart) ProtoMessage()    {}
func (*ReqHeart) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{3}
}

func (m *ReqHeart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqHeart.Unmarshal(m, b)
}
func (m *ReqHeart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqHeart.Marshal(b, m, deterministic)
}
func (m *ReqHeart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqHeart.Merge(m, src)
}
func (m *ReqHeart) XXX_Size() int {
	return xxx_messageInfo_ReqHeart.Size(m)
}
func (m *ReqHeart) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqHeart.DiscardUnknown(m)
}

var xxx_messageInfo_ReqHeart proto.InternalMessageInfo

type RspHeart struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspHeart) Reset()         { *m = RspHeart{} }
func (m *RspHeart) String() string { return proto.CompactTextString(m) }
func (*RspHeart) ProtoMessage()    {}
func (*RspHeart) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{4}
}

func (m *RspHeart) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspHeart.Unmarshal(m, b)
}
func (m *RspHeart) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspHeart.Marshal(b, m, deterministic)
}
func (m *RspHeart) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspHeart.Merge(m, src)
}
func (m *RspHeart) XXX_Size() int {
	return xxx_messageInfo_RspHeart.Size(m)
}
func (m *RspHeart) XXX_DiscardUnknown() {
	xxx_messageInfo_RspHeart.DiscardUnknown(m)
}

var xxx_messageInfo_RspHeart proto.InternalMessageInfo

//通知客户端下线
type NtfKickOut struct {
	Reason               int32    `protobuf:"varint,1,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NtfKickOut) Reset()         { *m = NtfKickOut{} }
func (m *NtfKickOut) String() string { return proto.CompactTextString(m) }
func (*NtfKickOut) ProtoMessage()    {}
func (*NtfKickOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{5}
}

func (m *NtfKickOut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NtfKickOut.Unmarshal(m, b)
}
func (m *NtfKickOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NtfKickOut.Marshal(b, m, deterministic)
}
func (m *NtfKickOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NtfKickOut.Merge(m, src)
}
func (m *NtfKickOut) XXX_Size() int {
	return xxx_messageInfo_NtfKickOut.Size(m)
}
func (m *NtfKickOut) XXX_DiscardUnknown() {
	xxx_messageInfo_NtfKickOut.DiscardUnknown(m)
}

var xxx_messageInfo_NtfKickOut proto.InternalMessageInfo

func (m *NtfKickOut) GetReason() int32 {
	if m != nil {
		return m.Reason
	}
	return 0
}

//玩家状态变化
type NtfStateChange struct {
	GameState            int32    `protobuf:"varint,1,opt,name=gameState,proto3" json:"gameState,omitempty"`
	GameType             int32    `protobuf:"varint,2,opt,name=gameType,proto3" json:"gameType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NtfStateChange) Reset()         { *m = NtfStateChange{} }
func (m *NtfStateChange) String() string { return proto.CompactTextString(m) }
func (*NtfStateChange) ProtoMessage()    {}
func (*NtfStateChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{6}
}

func (m *NtfStateChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NtfStateChange.Unmarshal(m, b)
}
func (m *NtfStateChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NtfStateChange.Marshal(b, m, deterministic)
}
func (m *NtfStateChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NtfStateChange.Merge(m, src)
}
func (m *NtfStateChange) XXX_Size() int {
	return xxx_messageInfo_NtfStateChange.Size(m)
}
func (m *NtfStateChange) XXX_DiscardUnknown() {
	xxx_messageInfo_NtfStateChange.DiscardUnknown(m)
}

var xxx_messageInfo_NtfStateChange proto.InternalMessageInfo

func (m *NtfStateChange) GetGameState() int32 {
	if m != nil {
		return m.GameState
	}
	return 0
}

func (m *NtfStateChange) GetGameType() int32 {
	if m != nil {
		return m.GameType
	}
	return 0
}

//通知玩家奖杯变化
type ReqUpdate_Cup struct {
	Cup                  int32    `protobuf:"varint,1,opt,name=cup,proto3" json:"cup,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqUpdate_Cup) Reset()         { *m = ReqUpdate_Cup{} }
func (m *ReqUpdate_Cup) String() string { return proto.CompactTextString(m) }
func (*ReqUpdate_Cup) ProtoMessage()    {}
func (*ReqUpdate_Cup) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{7}
}

func (m *ReqUpdate_Cup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqUpdate_Cup.Unmarshal(m, b)
}
func (m *ReqUpdate_Cup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqUpdate_Cup.Marshal(b, m, deterministic)
}
func (m *ReqUpdate_Cup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqUpdate_Cup.Merge(m, src)
}
func (m *ReqUpdate_Cup) XXX_Size() int {
	return xxx_messageInfo_ReqUpdate_Cup.Size(m)
}
func (m *ReqUpdate_Cup) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqUpdate_Cup.DiscardUnknown(m)
}

var xxx_messageInfo_ReqUpdate_Cup proto.InternalMessageInfo

func (m *ReqUpdate_Cup) GetCup() int32 {
	if m != nil {
		return m.Cup
	}
	return 0
}

type NtfPlayerCup struct {
	Cup                  int32    `protobuf:"varint,1,opt,name=cup,proto3" json:"cup,omitempty"`
	Rank                 int32    `protobuf:"varint,2,opt,name=rank,proto3" json:"rank,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NtfPlayerCup) Reset()         { *m = NtfPlayerCup{} }
func (m *NtfPlayerCup) String() string { return proto.CompactTextString(m) }
func (*NtfPlayerCup) ProtoMessage()    {}
func (*NtfPlayerCup) Descriptor() ([]byte, []int) {
	return fileDescriptor_67c21677aa7f4e4f, []int{8}
}

func (m *NtfPlayerCup) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NtfPlayerCup.Unmarshal(m, b)
}
func (m *NtfPlayerCup) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NtfPlayerCup.Marshal(b, m, deterministic)
}
func (m *NtfPlayerCup) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NtfPlayerCup.Merge(m, src)
}
func (m *NtfPlayerCup) XXX_Size() int {
	return xxx_messageInfo_NtfPlayerCup.Size(m)
}
func (m *NtfPlayerCup) XXX_DiscardUnknown() {
	xxx_messageInfo_NtfPlayerCup.DiscardUnknown(m)
}

var xxx_messageInfo_NtfPlayerCup proto.InternalMessageInfo

func (m *NtfPlayerCup) GetCup() int32 {
	if m != nil {
		return m.Cup
	}
	return 0
}

func (m *NtfPlayerCup) GetRank() int32 {
	if m != nil {
		return m.Rank
	}
	return 0
}

func init() {
	proto.RegisterType((*ReqLogin)(nil), "login.req_login")
	proto.RegisterType((*RspLogin)(nil), "login.rsp_login")
	proto.RegisterType((*NtfMsgTip)(nil), "login.ntf_msg_tip")
	proto.RegisterType((*ReqHeart)(nil), "login.req_heart")
	proto.RegisterType((*RspHeart)(nil), "login.rsp_heart")
	proto.RegisterType((*NtfKickOut)(nil), "login.ntf_kick_out")
	proto.RegisterType((*NtfStateChange)(nil), "login.ntf_state_change")
	proto.RegisterType((*ReqUpdate_Cup)(nil), "login.req_update__cup")
	proto.RegisterType((*NtfPlayerCup)(nil), "login.ntf_player_cup")
}

func init() { proto.RegisterFile("login.proto", fileDescriptor_67c21677aa7f4e4f) }

var fileDescriptor_67c21677aa7f4e4f = []byte{
	// 514 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0x93, 0xc1, 0x8a, 0xdb, 0x3c,
	0x10, 0xc7, 0x71, 0x12, 0x27, 0xf1, 0x38, 0x7c, 0xdf, 0x22, 0x96, 0x45, 0x2c, 0x6d, 0xd9, 0xba,
	0x50, 0x96, 0x1e, 0x96, 0xd2, 0x42, 0x1f, 0xa0, 0x3d, 0x2d, 0x94, 0x3d, 0x78, 0xdb, 0x1e, 0x7a,
	0x31, 0x5a, 0x6b, 0xe2, 0x88, 0xc4, 0x96, 0x2a, 0xcb, 0x59, 0xf2, 0xc0, 0x7d, 0x8e, 0x96, 0x91,
	0x14, 0x37, 0x0b, 0xa5, 0xb7, 0xf9, 0xfd, 0x67, 0x3c, 0x1a, 0xfd, 0x47, 0x86, 0x7c, 0xa7, 0x1b,
	0xd5, 0xdd, 0x18, 0xab, 0x9d, 0x66, 0xa9, 0x87, 0xcb, 0x55, 0xad, 0xdb, 0x56, 0x47, 0xb1, 0xf8,
	0x99, 0x40, 0x66, 0xf1, 0x47, 0xe5, 0x73, 0x8c, 0xc1, 0x4c, 0xc9, 0xb5, 0xe0, 0xc9, 0x55, 0x72,
	0x9d, 0x95, 0x3e, 0x8e, 0xda, 0x9e, 0x4f, 0x46, 0x6d, 0x4f, 0x5a, 0x33, 0x28, 0xc9, 0xa7, 0x41,
	0xa3, 0x98, 0x5d, 0xc0, 0x5c, 0xe2, 0x5e, 0xd5, 0xc8, 0x67, 0x5e, 0x8d, 0xc4, 0x2e, 0x61, 0x69,
	0x76, 0xc2, 0xad, 0xb5, 0x6d, 0x79, 0xea, 0x33, 0x23, 0x53, 0x4e, 0x1b, 0xec, 0xbe, 0x1c, 0x0c,
	0xf2, 0x79, 0xc8, 0x1d, 0x99, 0xfa, 0x51, 0x7c, 0x2b, 0xf9, 0x22, 0xf4, 0x0b, 0xc4, 0xce, 0x21,
	0x75, 0x7a, 0x8b, 0x1d, 0x5f, 0x7a, 0x39, 0x00, 0x7b, 0x01, 0x20, 0x8c, 0xf9, 0x86, 0xb6, 0x57,
	0xba, 0xe3, 0x99, 0x4f, 0x9d, 0x28, 0xc5, 0xaf, 0x09, 0x64, 0xb6, 0x37, 0xf1, 0x9e, 0x63, 0x8f,
	0xe4, 0xb4, 0x47, 0x98, 0xf4, 0x80, 0xf6, 0x56, 0xfa, 0xdb, 0x4e, 0xcb, 0x91, 0xa9, 0x7f, 0x88,
	0xef, 0x44, 0x8b, 0xf1, 0xde, 0x27, 0x0a, 0x7b, 0x09, 0x2b, 0x29, 0x9c, 0xa8, 0xf6, 0x71, 0x82,
	0x99, 0xff, 0x3e, 0x27, 0x2d, 0x8e, 0xc0, 0x9e, 0x41, 0xd6, 0x88, 0x16, 0xef, 0x9d, 0x70, 0xe8,
	0x9d, 0x48, 0xcb, 0x3f, 0x02, 0x1d, 0x4e, 0x30, 0x5a, 0x91, 0x96, 0x23, 0xd3, 0xb8, 0xaa, 0xbf,
	0xc3, 0x47, 0xef, 0xc4, 0xb2, 0x0c, 0x40, 0x06, 0x59, 0x7c, 0x14, 0x56, 0x46, 0x27, 0x22, 0xb1,
	0xe7, 0x00, 0x68, 0xad, 0xb6, 0x55, 0xad, 0x25, 0x7a, 0x2b, 0xd2, 0x32, 0xf3, 0xca, 0x27, 0x2d,
	0x91, 0xbd, 0x85, 0x85, 0xb0, 0xf5, 0x46, 0xed, 0x91, 0xc3, 0x55, 0x72, 0x9d, 0xbf, 0xbb, 0xb8,
	0x89, 0x2f, 0x22, 0xca, 0x15, 0x76, 0x4e, 0xb9, 0x43, 0x79, 0x2c, 0x63, 0x6f, 0x20, 0x15, 0xce,
	0x59, 0xc5, 0x73, 0x5f, 0x7f, 0x3e, 0xd6, 0x93, 0x78, 0xac, 0x0e, 0x25, 0x8c, 0xc3, 0x62, 0xe8,
	0xd1, 0xde, 0xab, 0x86, 0xaf, 0xfc, 0x54, 0x47, 0x2c, 0xbe, 0x42, 0xde, 0xb9, 0x75, 0xd5, 0xf6,
	0x4d, 0xe5, 0x94, 0xf1, 0x2b, 0x50, 0x6e, 0x87, 0xe3, 0x0a, 0x08, 0xe8, 0xf3, 0x16, 0xfb, 0x5e,
	0x34, 0x18, 0xdf, 0xdb, 0x11, 0xe9, 0xb6, 0x0f, 0x83, 0x73, 0xba, 0x8b, 0xe6, 0x47, 0x2a, 0xf2,
	0xf0, 0x7e, 0x37, 0x28, 0xac, 0xf3, 0xd0, 0x9b, 0x08, 0xaf, 0x61, 0x45, 0x07, 0x6e, 0x55, 0xbd,
	0xad, 0xf4, 0xe0, 0x82, 0x5f, 0xa2, 0xd7, 0x61, 0xeb, 0x69, 0x19, 0xa9, 0xf8, 0x0c, 0x67, 0x54,
	0xd7, 0xd3, 0x1a, 0xaa, 0x7a, 0x23, 0xba, 0x06, 0x9f, 0xee, 0x2a, 0xf9, 0xd7, 0xae, 0x26, 0x4f,
	0x77, 0x55, 0xbc, 0x82, 0xff, 0x69, 0x9e, 0xc1, 0x48, 0x6a, 0x57, 0xd5, 0x83, 0x61, 0x67, 0x30,
	0xad, 0x07, 0x13, 0xdb, 0x50, 0x58, 0x7c, 0x80, 0xff, 0xe8, 0xc8, 0xf0, 0x7e, 0xfe, 0x5e, 0x43,
	0xff, 0x98, 0x15, 0xdd, 0x36, 0x1e, 0xe0, 0xe3, 0x8f, 0xf0, 0x7d, 0xe9, 0x7f, 0x5b, 0x89, 0xeb,
	0x87, 0xb9, 0x8f, 0xde, 0xff, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x73, 0xf2, 0xfd, 0xdc, 0xe4, 0x03,
	0x00, 0x00,
}
