// Code generated by protoc-gen-go. DO NOT EDIT.
// source: match.proto

package protodef

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//随机匹配req
type ReqMatchGame struct {
	SceneLevel           int32         `protobuf:"varint,1,opt,name=scene_level,json=sceneLevel,proto3" json:"scene_level,omitempty"`
	UpgradeCard          bool          `protobuf:"varint,2,opt,name=upgrade_card,json=upgradeCard,proto3" json:"upgrade_card,omitempty"`
	Player               *EntityPlayer `protobuf:"bytes,3,opt,name=player,proto3" json:"player,omitempty"`
	GameType             int32         `protobuf:"varint,4,opt,name=game_type,json=gameType,proto3" json:"game_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReqMatchGame) Reset()         { *m = ReqMatchGame{} }
func (m *ReqMatchGame) String() string { return proto.CompactTextString(m) }
func (*ReqMatchGame) ProtoMessage()    {}
func (*ReqMatchGame) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a39bbc00e119b00, []int{0}
}

func (m *ReqMatchGame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqMatchGame.Unmarshal(m, b)
}
func (m *ReqMatchGame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqMatchGame.Marshal(b, m, deterministic)
}
func (m *ReqMatchGame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqMatchGame.Merge(m, src)
}
func (m *ReqMatchGame) XXX_Size() int {
	return xxx_messageInfo_ReqMatchGame.Size(m)
}
func (m *ReqMatchGame) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqMatchGame.DiscardUnknown(m)
}

var xxx_messageInfo_ReqMatchGame proto.InternalMessageInfo

func (m *ReqMatchGame) GetSceneLevel() int32 {
	if m != nil {
		return m.SceneLevel
	}
	return 0
}

func (m *ReqMatchGame) GetUpgradeCard() bool {
	if m != nil {
		return m.UpgradeCard
	}
	return false
}

func (m *ReqMatchGame) GetPlayer() *EntityPlayer {
	if m != nil {
		return m.Player
	}
	return nil
}

func (m *ReqMatchGame) GetGameType() int32 {
	if m != nil {
		return m.GameType
	}
	return 0
}

//匹配结果
type RspMatchGame struct {
	ErrorCode            int32    `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	MatchType            int32    `protobuf:"varint,2,opt,name=match_type,json=matchType,proto3" json:"match_type,omitempty"`
	RobotId              int32    `protobuf:"varint,3,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspMatchGame) Reset()         { *m = RspMatchGame{} }
func (m *RspMatchGame) String() string { return proto.CompactTextString(m) }
func (*RspMatchGame) ProtoMessage()    {}
func (*RspMatchGame) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a39bbc00e119b00, []int{1}
}

func (m *RspMatchGame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspMatchGame.Unmarshal(m, b)
}
func (m *RspMatchGame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspMatchGame.Marshal(b, m, deterministic)
}
func (m *RspMatchGame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspMatchGame.Merge(m, src)
}
func (m *RspMatchGame) XXX_Size() int {
	return xxx_messageInfo_RspMatchGame.Size(m)
}
func (m *RspMatchGame) XXX_DiscardUnknown() {
	xxx_messageInfo_RspMatchGame.DiscardUnknown(m)
}

var xxx_messageInfo_RspMatchGame proto.InternalMessageInfo

func (m *RspMatchGame) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *RspMatchGame) GetMatchType() int32 {
	if m != nil {
		return m.MatchType
	}
	return 0
}

func (m *RspMatchGame) GetRobotId() int32 {
	if m != nil {
		return m.RobotId
	}
	return 0
}

//取消匹配
type ReqCancelMatch struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqCancelMatch) Reset()         { *m = ReqCancelMatch{} }
func (m *ReqCancelMatch) String() string { return proto.CompactTextString(m) }
func (*ReqCancelMatch) ProtoMessage()    {}
func (*ReqCancelMatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a39bbc00e119b00, []int{2}
}

func (m *ReqCancelMatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCancelMatch.Unmarshal(m, b)
}
func (m *ReqCancelMatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCancelMatch.Marshal(b, m, deterministic)
}
func (m *ReqCancelMatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCancelMatch.Merge(m, src)
}
func (m *ReqCancelMatch) XXX_Size() int {
	return xxx_messageInfo_ReqCancelMatch.Size(m)
}
func (m *ReqCancelMatch) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCancelMatch.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCancelMatch proto.InternalMessageInfo

type NtfCancelMatch struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NtfCancelMatch) Reset()         { *m = NtfCancelMatch{} }
func (m *NtfCancelMatch) String() string { return proto.CompactTextString(m) }
func (*NtfCancelMatch) ProtoMessage()    {}
func (*NtfCancelMatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a39bbc00e119b00, []int{3}
}

func (m *NtfCancelMatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NtfCancelMatch.Unmarshal(m, b)
}
func (m *NtfCancelMatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NtfCancelMatch.Marshal(b, m, deterministic)
}
func (m *NtfCancelMatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NtfCancelMatch.Merge(m, src)
}
func (m *NtfCancelMatch) XXX_Size() int {
	return xxx_messageInfo_NtfCancelMatch.Size(m)
}
func (m *NtfCancelMatch) XXX_DiscardUnknown() {
	xxx_messageInfo_NtfCancelMatch.DiscardUnknown(m)
}

var xxx_messageInfo_NtfCancelMatch proto.InternalMessageInfo

//创建房间req
type ReqCreateRoom struct {
	SceneLevel           int32         `protobuf:"varint,1,opt,name=scene_level,json=sceneLevel,proto3" json:"scene_level,omitempty"`
	PvpCount             int32         `protobuf:"varint,2,opt,name=pvp_count,json=pvpCount,proto3" json:"pvp_count,omitempty"`
	Player               *EntityPlayer `protobuf:"bytes,3,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReqCreateRoom) Reset()         { *m = ReqCreateRoom{} }
func (m *ReqCreateRoom) String() string { return proto.CompactTextString(m) }
func (*ReqCreateRoom) ProtoMessage()    {}
func (*ReqCreateRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a39bbc00e119b00, []int{4}
}

func (m *ReqCreateRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCreateRoom.Unmarshal(m, b)
}
func (m *ReqCreateRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCreateRoom.Marshal(b, m, deterministic)
}
func (m *ReqCreateRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCreateRoom.Merge(m, src)
}
func (m *ReqCreateRoom) XXX_Size() int {
	return xxx_messageInfo_ReqCreateRoom.Size(m)
}
func (m *ReqCreateRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCreateRoom.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCreateRoom proto.InternalMessageInfo

func (m *ReqCreateRoom) GetSceneLevel() int32 {
	if m != nil {
		return m.SceneLevel
	}
	return 0
}

func (m *ReqCreateRoom) GetPvpCount() int32 {
	if m != nil {
		return m.PvpCount
	}
	return 0
}

func (m *ReqCreateRoom) GetPlayer() *EntityPlayer {
	if m != nil {
		return m.Player
	}
	return nil
}

//解散房间
type ReqDeleteRoom struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqDeleteRoom) Reset()         { *m = ReqDeleteRoom{} }
func (m *ReqDeleteRoom) String() string { return proto.CompactTextString(m) }
func (*ReqDeleteRoom) ProtoMessage()    {}
func (*ReqDeleteRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a39bbc00e119b00, []int{5}
}

func (m *ReqDeleteRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqDeleteRoom.Unmarshal(m, b)
}
func (m *ReqDeleteRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqDeleteRoom.Marshal(b, m, deterministic)
}
func (m *ReqDeleteRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqDeleteRoom.Merge(m, src)
}
func (m *ReqDeleteRoom) XXX_Size() int {
	return xxx_messageInfo_ReqDeleteRoom.Size(m)
}
func (m *ReqDeleteRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqDeleteRoom.DiscardUnknown(m)
}

var xxx_messageInfo_ReqDeleteRoom proto.InternalMessageInfo

type NtfDeleteRoom struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NtfDeleteRoom) Reset()         { *m = NtfDeleteRoom{} }
func (m *NtfDeleteRoom) String() string { return proto.CompactTextString(m) }
func (*NtfDeleteRoom) ProtoMessage()    {}
func (*NtfDeleteRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a39bbc00e119b00, []int{6}
}

func (m *NtfDeleteRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NtfDeleteRoom.Unmarshal(m, b)
}
func (m *NtfDeleteRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NtfDeleteRoom.Marshal(b, m, deterministic)
}
func (m *NtfDeleteRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NtfDeleteRoom.Merge(m, src)
}
func (m *NtfDeleteRoom) XXX_Size() int {
	return xxx_messageInfo_NtfDeleteRoom.Size(m)
}
func (m *NtfDeleteRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_NtfDeleteRoom.DiscardUnknown(m)
}

var xxx_messageInfo_NtfDeleteRoom proto.InternalMessageInfo

//创建房间rsp
type RspCreateRoom struct {
	ErrorCode            int32    `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	RoomCode             int32    `protobuf:"varint,2,opt,name=room_code,json=roomCode,proto3" json:"room_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspCreateRoom) Reset()         { *m = RspCreateRoom{} }
func (m *RspCreateRoom) String() string { return proto.CompactTextString(m) }
func (*RspCreateRoom) ProtoMessage()    {}
func (*RspCreateRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a39bbc00e119b00, []int{7}
}

func (m *RspCreateRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspCreateRoom.Unmarshal(m, b)
}
func (m *RspCreateRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspCreateRoom.Marshal(b, m, deterministic)
}
func (m *RspCreateRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspCreateRoom.Merge(m, src)
}
func (m *RspCreateRoom) XXX_Size() int {
	return xxx_messageInfo_RspCreateRoom.Size(m)
}
func (m *RspCreateRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_RspCreateRoom.DiscardUnknown(m)
}

var xxx_messageInfo_RspCreateRoom proto.InternalMessageInfo

func (m *RspCreateRoom) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *RspCreateRoom) GetRoomCode() int32 {
	if m != nil {
		return m.RoomCode
	}
	return 0
}

//加入房间req
type ReqJoinRoom struct {
	RoomCode             int32         `protobuf:"varint,1,opt,name=room_code,json=roomCode,proto3" json:"room_code,omitempty"`
	Player               *EntityPlayer `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReqJoinRoom) Reset()         { *m = ReqJoinRoom{} }
func (m *ReqJoinRoom) String() string { return proto.CompactTextString(m) }
func (*ReqJoinRoom) ProtoMessage()    {}
func (*ReqJoinRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a39bbc00e119b00, []int{8}
}

func (m *ReqJoinRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqJoinRoom.Unmarshal(m, b)
}
func (m *ReqJoinRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqJoinRoom.Marshal(b, m, deterministic)
}
func (m *ReqJoinRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqJoinRoom.Merge(m, src)
}
func (m *ReqJoinRoom) XXX_Size() int {
	return xxx_messageInfo_ReqJoinRoom.Size(m)
}
func (m *ReqJoinRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqJoinRoom.DiscardUnknown(m)
}

var xxx_messageInfo_ReqJoinRoom proto.InternalMessageInfo

func (m *ReqJoinRoom) GetRoomCode() int32 {
	if m != nil {
		return m.RoomCode
	}
	return 0
}

func (m *ReqJoinRoom) GetPlayer() *EntityPlayer {
	if m != nil {
		return m.Player
	}
	return nil
}

//加入房间rsp
type RspJoinRoom struct {
	ErrorCode            int32    `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspJoinRoom) Reset()         { *m = RspJoinRoom{} }
func (m *RspJoinRoom) String() string { return proto.CompactTextString(m) }
func (*RspJoinRoom) ProtoMessage()    {}
func (*RspJoinRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a39bbc00e119b00, []int{9}
}

func (m *RspJoinRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspJoinRoom.Unmarshal(m, b)
}
func (m *RspJoinRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspJoinRoom.Marshal(b, m, deterministic)
}
func (m *RspJoinRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspJoinRoom.Merge(m, src)
}
func (m *RspJoinRoom) XXX_Size() int {
	return xxx_messageInfo_RspJoinRoom.Size(m)
}
func (m *RspJoinRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_RspJoinRoom.DiscardUnknown(m)
}

var xxx_messageInfo_RspJoinRoom proto.InternalMessageInfo

func (m *RspJoinRoom) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

//房间准备好通知
type NtfRoomReady struct {
	RoomId               string          `protobuf:"bytes,1,opt,name=room_id,json=roomId,proto3" json:"room_id,omitempty"`
	MapId                int32           `protobuf:"varint,2,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	SceneId              int32           `protobuf:"varint,3,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	GameType             int32           `protobuf:"varint,4,opt,name=game_type,json=gameType,proto3" json:"game_type,omitempty"`
	ActivityId           int32           `protobuf:"varint,5,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	RandomSeed           int32           `protobuf:"varint,6,opt,name=random_seed,json=randomSeed,proto3" json:"random_seed,omitempty"`
	Players              []*EntityPlayer `protobuf:"bytes,7,rep,name=players,proto3" json:"players,omitempty"`
	TeamEntitys          []*EntityTeam   `protobuf:"bytes,8,rep,name=team_entitys,json=teamEntitys,proto3" json:"team_entitys,omitempty"`
	DialogArr            []*DialogAttr   `protobuf:"bytes,9,rep,name=dialog_arr,json=dialogArr,proto3" json:"dialog_arr,omitempty"`
	MapData              *MapEntity      `protobuf:"bytes,10,opt,name=map_data,json=mapData,proto3" json:"map_data,omitempty"`
	Args                 int32           `protobuf:"varint,12,opt,name=args,proto3" json:"args,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *NtfRoomReady) Reset()         { *m = NtfRoomReady{} }
func (m *NtfRoomReady) String() string { return proto.CompactTextString(m) }
func (*NtfRoomReady) ProtoMessage()    {}
func (*NtfRoomReady) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a39bbc00e119b00, []int{10}
}

func (m *NtfRoomReady) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NtfRoomReady.Unmarshal(m, b)
}
func (m *NtfRoomReady) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NtfRoomReady.Marshal(b, m, deterministic)
}
func (m *NtfRoomReady) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NtfRoomReady.Merge(m, src)
}
func (m *NtfRoomReady) XXX_Size() int {
	return xxx_messageInfo_NtfRoomReady.Size(m)
}
func (m *NtfRoomReady) XXX_DiscardUnknown() {
	xxx_messageInfo_NtfRoomReady.DiscardUnknown(m)
}

var xxx_messageInfo_NtfRoomReady proto.InternalMessageInfo

func (m *NtfRoomReady) GetRoomId() string {
	if m != nil {
		return m.RoomId
	}
	return ""
}

func (m *NtfRoomReady) GetMapId() int32 {
	if m != nil {
		return m.MapId
	}
	return 0
}

func (m *NtfRoomReady) GetSceneId() int32 {
	if m != nil {
		return m.SceneId
	}
	return 0
}

func (m *NtfRoomReady) GetGameType() int32 {
	if m != nil {
		return m.GameType
	}
	return 0
}

func (m *NtfRoomReady) GetActivityId() int32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *NtfRoomReady) GetRandomSeed() int32 {
	if m != nil {
		return m.RandomSeed
	}
	return 0
}

func (m *NtfRoomReady) GetPlayers() []*EntityPlayer {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *NtfRoomReady) GetTeamEntitys() []*EntityTeam {
	if m != nil {
		return m.TeamEntitys
	}
	return nil
}

func (m *NtfRoomReady) GetDialogArr() []*DialogAttr {
	if m != nil {
		return m.DialogArr
	}
	return nil
}

func (m *NtfRoomReady) GetMapData() *MapEntity {
	if m != nil {
		return m.MapData
	}
	return nil
}

func (m *NtfRoomReady) GetArgs() int32 {
	if m != nil {
		return m.Args
	}
	return 0
}

//随机匹配（活动）
type ReqMatchActivity struct {
	SceneLevel           int32         `protobuf:"varint,1,opt,name=scene_level,json=sceneLevel,proto3" json:"scene_level,omitempty"`
	Player               *EntityPlayer `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReqMatchActivity) Reset()         { *m = ReqMatchActivity{} }
func (m *ReqMatchActivity) String() string { return proto.CompactTextString(m) }
func (*ReqMatchActivity) ProtoMessage()    {}
func (*ReqMatchActivity) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a39bbc00e119b00, []int{11}
}

func (m *ReqMatchActivity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqMatchActivity.Unmarshal(m, b)
}
func (m *ReqMatchActivity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqMatchActivity.Marshal(b, m, deterministic)
}
func (m *ReqMatchActivity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqMatchActivity.Merge(m, src)
}
func (m *ReqMatchActivity) XXX_Size() int {
	return xxx_messageInfo_ReqMatchActivity.Size(m)
}
func (m *ReqMatchActivity) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqMatchActivity.DiscardUnknown(m)
}

var xxx_messageInfo_ReqMatchActivity proto.InternalMessageInfo

func (m *ReqMatchActivity) GetSceneLevel() int32 {
	if m != nil {
		return m.SceneLevel
	}
	return 0
}

func (m *ReqMatchActivity) GetPlayer() *EntityPlayer {
	if m != nil {
		return m.Player
	}
	return nil
}

//匹配结果（活动）
type RspMatchActivity struct {
	ErrorCode            int32    `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	MatchType            int32    `protobuf:"varint,2,opt,name=match_type,json=matchType,proto3" json:"match_type,omitempty"`
	RobotId              int32    `protobuf:"varint,3,opt,name=robot_id,json=robotId,proto3" json:"robot_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspMatchActivity) Reset()         { *m = RspMatchActivity{} }
func (m *RspMatchActivity) String() string { return proto.CompactTextString(m) }
func (*RspMatchActivity) ProtoMessage()    {}
func (*RspMatchActivity) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a39bbc00e119b00, []int{12}
}

func (m *RspMatchActivity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspMatchActivity.Unmarshal(m, b)
}
func (m *RspMatchActivity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspMatchActivity.Marshal(b, m, deterministic)
}
func (m *RspMatchActivity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspMatchActivity.Merge(m, src)
}
func (m *RspMatchActivity) XXX_Size() int {
	return xxx_messageInfo_RspMatchActivity.Size(m)
}
func (m *RspMatchActivity) XXX_DiscardUnknown() {
	xxx_messageInfo_RspMatchActivity.DiscardUnknown(m)
}

var xxx_messageInfo_RspMatchActivity proto.InternalMessageInfo

func (m *RspMatchActivity) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *RspMatchActivity) GetMatchType() int32 {
	if m != nil {
		return m.MatchType
	}
	return 0
}

func (m *RspMatchActivity) GetRobotId() int32 {
	if m != nil {
		return m.RobotId
	}
	return 0
}

//取消匹配（活动）
type ReqCancelMatchActivity struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqCancelMatchActivity) Reset()         { *m = ReqCancelMatchActivity{} }
func (m *ReqCancelMatchActivity) String() string { return proto.CompactTextString(m) }
func (*ReqCancelMatchActivity) ProtoMessage()    {}
func (*ReqCancelMatchActivity) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a39bbc00e119b00, []int{13}
}

func (m *ReqCancelMatchActivity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCancelMatchActivity.Unmarshal(m, b)
}
func (m *ReqCancelMatchActivity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCancelMatchActivity.Marshal(b, m, deterministic)
}
func (m *ReqCancelMatchActivity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCancelMatchActivity.Merge(m, src)
}
func (m *ReqCancelMatchActivity) XXX_Size() int {
	return xxx_messageInfo_ReqCancelMatchActivity.Size(m)
}
func (m *ReqCancelMatchActivity) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCancelMatchActivity.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCancelMatchActivity proto.InternalMessageInfo

type NtfCancelMatchActivity struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NtfCancelMatchActivity) Reset()         { *m = NtfCancelMatchActivity{} }
func (m *NtfCancelMatchActivity) String() string { return proto.CompactTextString(m) }
func (*NtfCancelMatchActivity) ProtoMessage()    {}
func (*NtfCancelMatchActivity) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a39bbc00e119b00, []int{14}
}

func (m *NtfCancelMatchActivity) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NtfCancelMatchActivity.Unmarshal(m, b)
}
func (m *NtfCancelMatchActivity) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NtfCancelMatchActivity.Marshal(b, m, deterministic)
}
func (m *NtfCancelMatchActivity) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NtfCancelMatchActivity.Merge(m, src)
}
func (m *NtfCancelMatchActivity) XXX_Size() int {
	return xxx_messageInfo_NtfCancelMatchActivity.Size(m)
}
func (m *NtfCancelMatchActivity) XXX_DiscardUnknown() {
	xxx_messageInfo_NtfCancelMatchActivity.DiscardUnknown(m)
}

var xxx_messageInfo_NtfCancelMatchActivity proto.InternalMessageInfo

//创建队伍
type ReqCreateTeam struct {
	PvpCount             int32         `protobuf:"varint,1,opt,name=pvp_count,json=pvpCount,proto3" json:"pvp_count,omitempty"`
	Player               *EntityPlayer `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReqCreateTeam) Reset()         { *m = ReqCreateTeam{} }
func (m *ReqCreateTeam) String() string { return proto.CompactTextString(m) }
func (*ReqCreateTeam) ProtoMessage()    {}
func (*ReqCreateTeam) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a39bbc00e119b00, []int{15}
}

func (m *ReqCreateTeam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqCreateTeam.Unmarshal(m, b)
}
func (m *ReqCreateTeam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqCreateTeam.Marshal(b, m, deterministic)
}
func (m *ReqCreateTeam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqCreateTeam.Merge(m, src)
}
func (m *ReqCreateTeam) XXX_Size() int {
	return xxx_messageInfo_ReqCreateTeam.Size(m)
}
func (m *ReqCreateTeam) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqCreateTeam.DiscardUnknown(m)
}

var xxx_messageInfo_ReqCreateTeam proto.InternalMessageInfo

func (m *ReqCreateTeam) GetPvpCount() int32 {
	if m != nil {
		return m.PvpCount
	}
	return 0
}

func (m *ReqCreateTeam) GetPlayer() *EntityPlayer {
	if m != nil {
		return m.Player
	}
	return nil
}

//3022=match.rsp_create_team
type RspCreateTeam struct {
	ErrorCode            int32    `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspCreateTeam) Reset()         { *m = RspCreateTeam{} }
func (m *RspCreateTeam) String() string { return proto.CompactTextString(m) }
func (*RspCreateTeam) ProtoMessage()    {}
func (*RspCreateTeam) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a39bbc00e119b00, []int{16}
}

func (m *RspCreateTeam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspCreateTeam.Unmarshal(m, b)
}
func (m *RspCreateTeam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspCreateTeam.Marshal(b, m, deterministic)
}
func (m *RspCreateTeam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspCreateTeam.Merge(m, src)
}
func (m *RspCreateTeam) XXX_Size() int {
	return xxx_messageInfo_RspCreateTeam.Size(m)
}
func (m *RspCreateTeam) XXX_DiscardUnknown() {
	xxx_messageInfo_RspCreateTeam.DiscardUnknown(m)
}

var xxx_messageInfo_RspCreateTeam proto.InternalMessageInfo

func (m *RspCreateTeam) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

//请求我的队伍信息
type ReqMyTeam struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqMyTeam) Reset()         { *m = ReqMyTeam{} }
func (m *ReqMyTeam) String() string { return proto.CompactTextString(m) }
func (*ReqMyTeam) ProtoMessage()    {}
func (*ReqMyTeam) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a39bbc00e119b00, []int{17}
}

func (m *ReqMyTeam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqMyTeam.Unmarshal(m, b)
}
func (m *ReqMyTeam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqMyTeam.Marshal(b, m, deterministic)
}
func (m *ReqMyTeam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqMyTeam.Merge(m, src)
}
func (m *ReqMyTeam) XXX_Size() int {
	return xxx_messageInfo_ReqMyTeam.Size(m)
}
func (m *ReqMyTeam) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqMyTeam.DiscardUnknown(m)
}

var xxx_messageInfo_ReqMyTeam proto.InternalMessageInfo

//3035=match.ntf_my_team
type NtfMyTeam struct {
	ErrorCode            int32       `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Team                 *TeamEntity `protobuf:"bytes,2,opt,name=team,proto3" json:"team,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *NtfMyTeam) Reset()         { *m = NtfMyTeam{} }
func (m *NtfMyTeam) String() string { return proto.CompactTextString(m) }
func (*NtfMyTeam) ProtoMessage()    {}
func (*NtfMyTeam) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a39bbc00e119b00, []int{18}
}

func (m *NtfMyTeam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NtfMyTeam.Unmarshal(m, b)
}
func (m *NtfMyTeam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NtfMyTeam.Marshal(b, m, deterministic)
}
func (m *NtfMyTeam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NtfMyTeam.Merge(m, src)
}
func (m *NtfMyTeam) XXX_Size() int {
	return xxx_messageInfo_NtfMyTeam.Size(m)
}
func (m *NtfMyTeam) XXX_DiscardUnknown() {
	xxx_messageInfo_NtfMyTeam.DiscardUnknown(m)
}

var xxx_messageInfo_NtfMyTeam proto.InternalMessageInfo

func (m *NtfMyTeam) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *NtfMyTeam) GetTeam() *TeamEntity {
	if m != nil {
		return m.Team
	}
	return nil
}

//邀请加入队伍，回复邮件
type ReqInviteJoinTeam struct {
	PlayerId             int64    `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqInviteJoinTeam) Reset()         { *m = ReqInviteJoinTeam{} }
func (m *ReqInviteJoinTeam) String() string { return proto.CompactTextString(m) }
func (*ReqInviteJoinTeam) ProtoMessage()    {}
func (*ReqInviteJoinTeam) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a39bbc00e119b00, []int{19}
}

func (m *ReqInviteJoinTeam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqInviteJoinTeam.Unmarshal(m, b)
}
func (m *ReqInviteJoinTeam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqInviteJoinTeam.Marshal(b, m, deterministic)
}
func (m *ReqInviteJoinTeam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqInviteJoinTeam.Merge(m, src)
}
func (m *ReqInviteJoinTeam) XXX_Size() int {
	return xxx_messageInfo_ReqInviteJoinTeam.Size(m)
}
func (m *ReqInviteJoinTeam) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqInviteJoinTeam.DiscardUnknown(m)
}

var xxx_messageInfo_ReqInviteJoinTeam proto.InternalMessageInfo

func (m *ReqInviteJoinTeam) GetPlayerId() int64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

type RspInviteJoinTeam struct {
	ErrorCode            int32    `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspInviteJoinTeam) Reset()         { *m = RspInviteJoinTeam{} }
func (m *RspInviteJoinTeam) String() string { return proto.CompactTextString(m) }
func (*RspInviteJoinTeam) ProtoMessage()    {}
func (*RspInviteJoinTeam) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a39bbc00e119b00, []int{20}
}

func (m *RspInviteJoinTeam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspInviteJoinTeam.Unmarshal(m, b)
}
func (m *RspInviteJoinTeam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspInviteJoinTeam.Marshal(b, m, deterministic)
}
func (m *RspInviteJoinTeam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspInviteJoinTeam.Merge(m, src)
}
func (m *RspInviteJoinTeam) XXX_Size() int {
	return xxx_messageInfo_RspInviteJoinTeam.Size(m)
}
func (m *RspInviteJoinTeam) XXX_DiscardUnknown() {
	xxx_messageInfo_RspInviteJoinTeam.DiscardUnknown(m)
}

var xxx_messageInfo_RspInviteJoinTeam proto.InternalMessageInfo

func (m *RspInviteJoinTeam) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

//同意加入队伍
type ReqAgreeJoinTeam struct {
	TeamId               int64         `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	InviterId            int64         `protobuf:"varint,2,opt,name=inviterId,proto3" json:"inviterId,omitempty"`
	Player               *EntityPlayer `protobuf:"bytes,3,opt,name=player,proto3" json:"player,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ReqAgreeJoinTeam) Reset()         { *m = ReqAgreeJoinTeam{} }
func (m *ReqAgreeJoinTeam) String() string { return proto.CompactTextString(m) }
func (*ReqAgreeJoinTeam) ProtoMessage()    {}
func (*ReqAgreeJoinTeam) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a39bbc00e119b00, []int{21}
}

func (m *ReqAgreeJoinTeam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqAgreeJoinTeam.Unmarshal(m, b)
}
func (m *ReqAgreeJoinTeam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqAgreeJoinTeam.Marshal(b, m, deterministic)
}
func (m *ReqAgreeJoinTeam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqAgreeJoinTeam.Merge(m, src)
}
func (m *ReqAgreeJoinTeam) XXX_Size() int {
	return xxx_messageInfo_ReqAgreeJoinTeam.Size(m)
}
func (m *ReqAgreeJoinTeam) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqAgreeJoinTeam.DiscardUnknown(m)
}

var xxx_messageInfo_ReqAgreeJoinTeam proto.InternalMessageInfo

func (m *ReqAgreeJoinTeam) GetTeamId() int64 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

func (m *ReqAgreeJoinTeam) GetInviterId() int64 {
	if m != nil {
		return m.InviterId
	}
	return 0
}

func (m *ReqAgreeJoinTeam) GetPlayer() *EntityPlayer {
	if m != nil {
		return m.Player
	}
	return nil
}

//3039=match.rsp_agree_join_team
type RspAgreeJoinTeam struct {
	ErrorCode            int32    `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspAgreeJoinTeam) Reset()         { *m = RspAgreeJoinTeam{} }
func (m *RspAgreeJoinTeam) String() string { return proto.CompactTextString(m) }
func (*RspAgreeJoinTeam) ProtoMessage()    {}
func (*RspAgreeJoinTeam) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a39bbc00e119b00, []int{22}
}

func (m *RspAgreeJoinTeam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspAgreeJoinTeam.Unmarshal(m, b)
}
func (m *RspAgreeJoinTeam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspAgreeJoinTeam.Marshal(b, m, deterministic)
}
func (m *RspAgreeJoinTeam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspAgreeJoinTeam.Merge(m, src)
}
func (m *RspAgreeJoinTeam) XXX_Size() int {
	return xxx_messageInfo_RspAgreeJoinTeam.Size(m)
}
func (m *RspAgreeJoinTeam) XXX_DiscardUnknown() {
	xxx_messageInfo_RspAgreeJoinTeam.DiscardUnknown(m)
}

var xxx_messageInfo_RspAgreeJoinTeam proto.InternalMessageInfo

func (m *RspAgreeJoinTeam) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

//谁邀请谁进入房间广播
type NtfAnyoneJoinTeam struct {
	PlayerId             int64    `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	InviterId            int64    `protobuf:"varint,2,opt,name=inviterId,proto3" json:"inviterId,omitempty"`
	TeamType             int32    `protobuf:"varint,3,opt,name=teamType,proto3" json:"teamType,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NtfAnyoneJoinTeam) Reset()         { *m = NtfAnyoneJoinTeam{} }
func (m *NtfAnyoneJoinTeam) String() string { return proto.CompactTextString(m) }
func (*NtfAnyoneJoinTeam) ProtoMessage()    {}
func (*NtfAnyoneJoinTeam) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a39bbc00e119b00, []int{23}
}

func (m *NtfAnyoneJoinTeam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NtfAnyoneJoinTeam.Unmarshal(m, b)
}
func (m *NtfAnyoneJoinTeam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NtfAnyoneJoinTeam.Marshal(b, m, deterministic)
}
func (m *NtfAnyoneJoinTeam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NtfAnyoneJoinTeam.Merge(m, src)
}
func (m *NtfAnyoneJoinTeam) XXX_Size() int {
	return xxx_messageInfo_NtfAnyoneJoinTeam.Size(m)
}
func (m *NtfAnyoneJoinTeam) XXX_DiscardUnknown() {
	xxx_messageInfo_NtfAnyoneJoinTeam.DiscardUnknown(m)
}

var xxx_messageInfo_NtfAnyoneJoinTeam proto.InternalMessageInfo

func (m *NtfAnyoneJoinTeam) GetPlayerId() int64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *NtfAnyoneJoinTeam) GetInviterId() int64 {
	if m != nil {
		return m.InviterId
	}
	return 0
}

func (m *NtfAnyoneJoinTeam) GetTeamType() int32 {
	if m != nil {
		return m.TeamType
	}
	return 0
}

//请求离开队伍
type ReqLeaveTeam struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqLeaveTeam) Reset()         { *m = ReqLeaveTeam{} }
func (m *ReqLeaveTeam) String() string { return proto.CompactTextString(m) }
func (*ReqLeaveTeam) ProtoMessage()    {}
func (*ReqLeaveTeam) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a39bbc00e119b00, []int{24}
}

func (m *ReqLeaveTeam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqLeaveTeam.Unmarshal(m, b)
}
func (m *ReqLeaveTeam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqLeaveTeam.Marshal(b, m, deterministic)
}
func (m *ReqLeaveTeam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqLeaveTeam.Merge(m, src)
}
func (m *ReqLeaveTeam) XXX_Size() int {
	return xxx_messageInfo_ReqLeaveTeam.Size(m)
}
func (m *ReqLeaveTeam) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqLeaveTeam.DiscardUnknown(m)
}

var xxx_messageInfo_ReqLeaveTeam proto.InternalMessageInfo

//3026=match.ntf_leave_team
type NtfLeaveTeam struct {
	ErrorCode            int32    `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NtfLeaveTeam) Reset()         { *m = NtfLeaveTeam{} }
func (m *NtfLeaveTeam) String() string { return proto.CompactTextString(m) }
func (*NtfLeaveTeam) ProtoMessage()    {}
func (*NtfLeaveTeam) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a39bbc00e119b00, []int{25}
}

func (m *NtfLeaveTeam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NtfLeaveTeam.Unmarshal(m, b)
}
func (m *NtfLeaveTeam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NtfLeaveTeam.Marshal(b, m, deterministic)
}
func (m *NtfLeaveTeam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NtfLeaveTeam.Merge(m, src)
}
func (m *NtfLeaveTeam) XXX_Size() int {
	return xxx_messageInfo_NtfLeaveTeam.Size(m)
}
func (m *NtfLeaveTeam) XXX_DiscardUnknown() {
	xxx_messageInfo_NtfLeaveTeam.DiscardUnknown(m)
}

var xxx_messageInfo_NtfLeaveTeam proto.InternalMessageInfo

func (m *NtfLeaveTeam) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

//请求解散队伍
type ReqBreakTeam struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqBreakTeam) Reset()         { *m = ReqBreakTeam{} }
func (m *ReqBreakTeam) String() string { return proto.CompactTextString(m) }
func (*ReqBreakTeam) ProtoMessage()    {}
func (*ReqBreakTeam) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a39bbc00e119b00, []int{26}
}

func (m *ReqBreakTeam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqBreakTeam.Unmarshal(m, b)
}
func (m *ReqBreakTeam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqBreakTeam.Marshal(b, m, deterministic)
}
func (m *ReqBreakTeam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqBreakTeam.Merge(m, src)
}
func (m *ReqBreakTeam) XXX_Size() int {
	return xxx_messageInfo_ReqBreakTeam.Size(m)
}
func (m *ReqBreakTeam) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqBreakTeam.DiscardUnknown(m)
}

var xxx_messageInfo_ReqBreakTeam proto.InternalMessageInfo

//3032=match.ntf_break_team
type NtfBreakTeam struct {
	ErrorCode            int32    `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NtfBreakTeam) Reset()         { *m = NtfBreakTeam{} }
func (m *NtfBreakTeam) String() string { return proto.CompactTextString(m) }
func (*NtfBreakTeam) ProtoMessage()    {}
func (*NtfBreakTeam) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a39bbc00e119b00, []int{27}
}

func (m *NtfBreakTeam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NtfBreakTeam.Unmarshal(m, b)
}
func (m *NtfBreakTeam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NtfBreakTeam.Marshal(b, m, deterministic)
}
func (m *NtfBreakTeam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NtfBreakTeam.Merge(m, src)
}
func (m *NtfBreakTeam) XXX_Size() int {
	return xxx_messageInfo_NtfBreakTeam.Size(m)
}
func (m *NtfBreakTeam) XXX_DiscardUnknown() {
	xxx_messageInfo_NtfBreakTeam.DiscardUnknown(m)
}

var xxx_messageInfo_NtfBreakTeam proto.InternalMessageInfo

func (m *NtfBreakTeam) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

//请求搜索队友
type ReqSearchPalyers struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSearchPalyers) Reset()         { *m = ReqSearchPalyers{} }
func (m *ReqSearchPalyers) String() string { return proto.CompactTextString(m) }
func (*ReqSearchPalyers) ProtoMessage()    {}
func (*ReqSearchPalyers) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a39bbc00e119b00, []int{28}
}

func (m *ReqSearchPalyers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSearchPalyers.Unmarshal(m, b)
}
func (m *ReqSearchPalyers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSearchPalyers.Marshal(b, m, deterministic)
}
func (m *ReqSearchPalyers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSearchPalyers.Merge(m, src)
}
func (m *ReqSearchPalyers) XXX_Size() int {
	return xxx_messageInfo_ReqSearchPalyers.Size(m)
}
func (m *ReqSearchPalyers) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSearchPalyers.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSearchPalyers proto.InternalMessageInfo

//3028=match.ntf_search_players
type NtfSearchPlayers struct {
	ErrorCode            int32    `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NtfSearchPlayers) Reset()         { *m = NtfSearchPlayers{} }
func (m *NtfSearchPlayers) String() string { return proto.CompactTextString(m) }
func (*NtfSearchPlayers) ProtoMessage()    {}
func (*NtfSearchPlayers) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a39bbc00e119b00, []int{29}
}

func (m *NtfSearchPlayers) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NtfSearchPlayers.Unmarshal(m, b)
}
func (m *NtfSearchPlayers) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NtfSearchPlayers.Marshal(b, m, deterministic)
}
func (m *NtfSearchPlayers) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NtfSearchPlayers.Merge(m, src)
}
func (m *NtfSearchPlayers) XXX_Size() int {
	return xxx_messageInfo_NtfSearchPlayers.Size(m)
}
func (m *NtfSearchPlayers) XXX_DiscardUnknown() {
	xxx_messageInfo_NtfSearchPlayers.DiscardUnknown(m)
}

var xxx_messageInfo_NtfSearchPlayers proto.InternalMessageInfo

func (m *NtfSearchPlayers) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

//队伍成员准备
type ReqTeamMemberReady struct {
	PlayerId             int64    `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqTeamMemberReady) Reset()         { *m = ReqTeamMemberReady{} }
func (m *ReqTeamMemberReady) String() string { return proto.CompactTextString(m) }
func (*ReqTeamMemberReady) ProtoMessage()    {}
func (*ReqTeamMemberReady) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a39bbc00e119b00, []int{30}
}

func (m *ReqTeamMemberReady) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqTeamMemberReady.Unmarshal(m, b)
}
func (m *ReqTeamMemberReady) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqTeamMemberReady.Marshal(b, m, deterministic)
}
func (m *ReqTeamMemberReady) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqTeamMemberReady.Merge(m, src)
}
func (m *ReqTeamMemberReady) XXX_Size() int {
	return xxx_messageInfo_ReqTeamMemberReady.Size(m)
}
func (m *ReqTeamMemberReady) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqTeamMemberReady.DiscardUnknown(m)
}

var xxx_messageInfo_ReqTeamMemberReady proto.InternalMessageInfo

func (m *ReqTeamMemberReady) GetPlayerId() int64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

//3034=match.ntf_team_member_ready
type NtfTeamMemberReady struct {
	PlayerId             int64    `protobuf:"varint,1,opt,name=playerId,proto3" json:"playerId,omitempty"`
	ErrorCode            int32    `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NtfTeamMemberReady) Reset()         { *m = NtfTeamMemberReady{} }
func (m *NtfTeamMemberReady) String() string { return proto.CompactTextString(m) }
func (*NtfTeamMemberReady) ProtoMessage()    {}
func (*NtfTeamMemberReady) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a39bbc00e119b00, []int{31}
}

func (m *NtfTeamMemberReady) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NtfTeamMemberReady.Unmarshal(m, b)
}
func (m *NtfTeamMemberReady) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NtfTeamMemberReady.Marshal(b, m, deterministic)
}
func (m *NtfTeamMemberReady) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NtfTeamMemberReady.Merge(m, src)
}
func (m *NtfTeamMemberReady) XXX_Size() int {
	return xxx_messageInfo_NtfTeamMemberReady.Size(m)
}
func (m *NtfTeamMemberReady) XXX_DiscardUnknown() {
	xxx_messageInfo_NtfTeamMemberReady.DiscardUnknown(m)
}

var xxx_messageInfo_NtfTeamMemberReady proto.InternalMessageInfo

func (m *NtfTeamMemberReady) GetPlayerId() int64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *NtfTeamMemberReady) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

//队伍天赋选择
type ReqSelectTeamTalentId struct {
	TalentId             int32    `protobuf:"varint,1,opt,name=talentId,proto3" json:"talentId,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSelectTeamTalentId) Reset()         { *m = ReqSelectTeamTalentId{} }
func (m *ReqSelectTeamTalentId) String() string { return proto.CompactTextString(m) }
func (*ReqSelectTeamTalentId) ProtoMessage()    {}
func (*ReqSelectTeamTalentId) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a39bbc00e119b00, []int{32}
}

func (m *ReqSelectTeamTalentId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSelectTeamTalentId.Unmarshal(m, b)
}
func (m *ReqSelectTeamTalentId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSelectTeamTalentId.Marshal(b, m, deterministic)
}
func (m *ReqSelectTeamTalentId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSelectTeamTalentId.Merge(m, src)
}
func (m *ReqSelectTeamTalentId) XXX_Size() int {
	return xxx_messageInfo_ReqSelectTeamTalentId.Size(m)
}
func (m *ReqSelectTeamTalentId) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSelectTeamTalentId.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSelectTeamTalentId proto.InternalMessageInfo

func (m *ReqSelectTeamTalentId) GetTalentId() int32 {
	if m != nil {
		return m.TalentId
	}
	return 0
}

//3038=match.rsp_select_team_talentId
type RspSelectTeamTalentId struct {
	TalentId             int32    `protobuf:"varint,1,opt,name=talentId,proto3" json:"talentId,omitempty"`
	ErrorCode            int32    `protobuf:"varint,2,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspSelectTeamTalentId) Reset()         { *m = RspSelectTeamTalentId{} }
func (m *RspSelectTeamTalentId) String() string { return proto.CompactTextString(m) }
func (*RspSelectTeamTalentId) ProtoMessage()    {}
func (*RspSelectTeamTalentId) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a39bbc00e119b00, []int{33}
}

func (m *RspSelectTeamTalentId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspSelectTeamTalentId.Unmarshal(m, b)
}
func (m *RspSelectTeamTalentId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspSelectTeamTalentId.Marshal(b, m, deterministic)
}
func (m *RspSelectTeamTalentId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspSelectTeamTalentId.Merge(m, src)
}
func (m *RspSelectTeamTalentId) XXX_Size() int {
	return xxx_messageInfo_RspSelectTeamTalentId.Size(m)
}
func (m *RspSelectTeamTalentId) XXX_DiscardUnknown() {
	xxx_messageInfo_RspSelectTeamTalentId.DiscardUnknown(m)
}

var xxx_messageInfo_RspSelectTeamTalentId proto.InternalMessageInfo

func (m *RspSelectTeamTalentId) GetTalentId() int32 {
	if m != nil {
		return m.TalentId
	}
	return 0
}

func (m *RspSelectTeamTalentId) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

//团队匹配
type ReqMatchTeamGame struct {
	TeamId               int64           `protobuf:"varint,1,opt,name=team_id,json=teamId,proto3" json:"team_id,omitempty"`
	TalentId             int32           `protobuf:"varint,2,opt,name=talentId,proto3" json:"talentId,omitempty"`
	UpgradeCard          bool            `protobuf:"varint,3,opt,name=upgrade_card,json=upgradeCard,proto3" json:"upgrade_card,omitempty"`
	Players              []*EntityPlayer `protobuf:"bytes,4,rep,name=players,proto3" json:"players,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *ReqMatchTeamGame) Reset()         { *m = ReqMatchTeamGame{} }
func (m *ReqMatchTeamGame) String() string { return proto.CompactTextString(m) }
func (*ReqMatchTeamGame) ProtoMessage()    {}
func (*ReqMatchTeamGame) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a39bbc00e119b00, []int{34}
}

func (m *ReqMatchTeamGame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqMatchTeamGame.Unmarshal(m, b)
}
func (m *ReqMatchTeamGame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqMatchTeamGame.Marshal(b, m, deterministic)
}
func (m *ReqMatchTeamGame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqMatchTeamGame.Merge(m, src)
}
func (m *ReqMatchTeamGame) XXX_Size() int {
	return xxx_messageInfo_ReqMatchTeamGame.Size(m)
}
func (m *ReqMatchTeamGame) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqMatchTeamGame.DiscardUnknown(m)
}

var xxx_messageInfo_ReqMatchTeamGame proto.InternalMessageInfo

func (m *ReqMatchTeamGame) GetTeamId() int64 {
	if m != nil {
		return m.TeamId
	}
	return 0
}

func (m *ReqMatchTeamGame) GetTalentId() int32 {
	if m != nil {
		return m.TalentId
	}
	return 0
}

func (m *ReqMatchTeamGame) GetUpgradeCard() bool {
	if m != nil {
		return m.UpgradeCard
	}
	return false
}

func (m *ReqMatchTeamGame) GetPlayers() []*EntityPlayer {
	if m != nil {
		return m.Players
	}
	return nil
}

//3030=match.ntf_match_team_game
type NtfMatchTeamGame struct {
	ErrorCode            int32    `protobuf:"varint,1,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	MatchType            int32    `protobuf:"varint,2,opt,name=match_type,json=matchType,proto3" json:"match_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NtfMatchTeamGame) Reset()         { *m = NtfMatchTeamGame{} }
func (m *NtfMatchTeamGame) String() string { return proto.CompactTextString(m) }
func (*NtfMatchTeamGame) ProtoMessage()    {}
func (*NtfMatchTeamGame) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a39bbc00e119b00, []int{35}
}

func (m *NtfMatchTeamGame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NtfMatchTeamGame.Unmarshal(m, b)
}
func (m *NtfMatchTeamGame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NtfMatchTeamGame.Marshal(b, m, deterministic)
}
func (m *NtfMatchTeamGame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NtfMatchTeamGame.Merge(m, src)
}
func (m *NtfMatchTeamGame) XXX_Size() int {
	return xxx_messageInfo_NtfMatchTeamGame.Size(m)
}
func (m *NtfMatchTeamGame) XXX_DiscardUnknown() {
	xxx_messageInfo_NtfMatchTeamGame.DiscardUnknown(m)
}

var xxx_messageInfo_NtfMatchTeamGame proto.InternalMessageInfo

func (m *NtfMatchTeamGame) GetErrorCode() int32 {
	if m != nil {
		return m.ErrorCode
	}
	return 0
}

func (m *NtfMatchTeamGame) GetMatchType() int32 {
	if m != nil {
		return m.MatchType
	}
	return 0
}

func init() {
	proto.RegisterType((*ReqMatchGame)(nil), "match.req_match_game")
	proto.RegisterType((*RspMatchGame)(nil), "match.rsp_match_game")
	proto.RegisterType((*ReqCancelMatch)(nil), "match.req_cancel_match")
	proto.RegisterType((*NtfCancelMatch)(nil), "match.ntf_cancel_match")
	proto.RegisterType((*ReqCreateRoom)(nil), "match.req_create_room")
	proto.RegisterType((*ReqDeleteRoom)(nil), "match.req_delete_room")
	proto.RegisterType((*NtfDeleteRoom)(nil), "match.ntf_delete_room")
	proto.RegisterType((*RspCreateRoom)(nil), "match.rsp_create_room")
	proto.RegisterType((*ReqJoinRoom)(nil), "match.req_join_room")
	proto.RegisterType((*RspJoinRoom)(nil), "match.rsp_join_room")
	proto.RegisterType((*NtfRoomReady)(nil), "match.ntf_room_ready")
	proto.RegisterType((*ReqMatchActivity)(nil), "match.req_match_activity")
	proto.RegisterType((*RspMatchActivity)(nil), "match.rsp_match_activity")
	proto.RegisterType((*ReqCancelMatchActivity)(nil), "match.req_cancel_match_activity")
	proto.RegisterType((*NtfCancelMatchActivity)(nil), "match.ntf_cancel_match_activity")
	proto.RegisterType((*ReqCreateTeam)(nil), "match.req_create_team")
	proto.RegisterType((*RspCreateTeam)(nil), "match.rsp_create_team")
	proto.RegisterType((*ReqMyTeam)(nil), "match.req_my_team")
	proto.RegisterType((*NtfMyTeam)(nil), "match.ntf_my_team")
	proto.RegisterType((*ReqInviteJoinTeam)(nil), "match.req_invite_join_team")
	proto.RegisterType((*RspInviteJoinTeam)(nil), "match.rsp_invite_join_team")
	proto.RegisterType((*ReqAgreeJoinTeam)(nil), "match.req_agree_join_team")
	proto.RegisterType((*RspAgreeJoinTeam)(nil), "match.rsp_agree_join_team")
	proto.RegisterType((*NtfAnyoneJoinTeam)(nil), "match.ntf_anyone_join_team")
	proto.RegisterType((*ReqLeaveTeam)(nil), "match.req_leave_team")
	proto.RegisterType((*NtfLeaveTeam)(nil), "match.ntf_leave_team")
	proto.RegisterType((*ReqBreakTeam)(nil), "match.req_break_team")
	proto.RegisterType((*NtfBreakTeam)(nil), "match.ntf_break_team")
	proto.RegisterType((*ReqSearchPalyers)(nil), "match.req_search_palyers")
	proto.RegisterType((*NtfSearchPlayers)(nil), "match.ntf_search_players")
	proto.RegisterType((*ReqTeamMemberReady)(nil), "match.req_team_member_ready")
	proto.RegisterType((*NtfTeamMemberReady)(nil), "match.ntf_team_member_ready")
	proto.RegisterType((*ReqSelectTeamTalentId)(nil), "match.req_select_team_talentId")
	proto.RegisterType((*RspSelectTeamTalentId)(nil), "match.rsp_select_team_talentId")
	proto.RegisterType((*ReqMatchTeamGame)(nil), "match.req_match_team_game")
	proto.RegisterType((*NtfMatchTeamGame)(nil), "match.ntf_match_team_game")
}

func init() { proto.RegisterFile("match.proto", fileDescriptor_4a39bbc00e119b00) }

var fileDescriptor_4a39bbc00e119b00 = []byte{
	// 892 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x56, 0xdf, 0x6f, 0xe3, 0x44,
	0x10, 0x96, 0x93, 0x26, 0xb1, 0x27, 0x6d, 0xef, 0xd8, 0xb6, 0x3a, 0x5f, 0x0b, 0xa2, 0xf8, 0x85,
	0xbe, 0x5c, 0x0f, 0xb5, 0x70, 0xef, 0x50, 0x78, 0x88, 0x04, 0x2f, 0x3e, 0xee, 0x05, 0x84, 0xac,
	0xad, 0x77, 0x2e, 0x67, 0xb0, 0xbd, 0x66, 0xb3, 0x17, 0x29, 0x42, 0xe2, 0x0f, 0xe1, 0x01, 0xf1,
	0xa7, 0xa2, 0xd9, 0x5d, 0xc7, 0x3f, 0x4e, 0xad, 0x13, 0x21, 0x5e, 0xa2, 0xcc, 0x37, 0xb3, 0xf3,
	0x7d, 0x3b, 0x3b, 0x3b, 0x5e, 0x98, 0x17, 0x5c, 0xa7, 0xef, 0xae, 0x2b, 0x25, 0xb5, 0x64, 0x13,
	0x63, 0x9c, 0x1f, 0xa6, 0xb2, 0x28, 0x64, 0x69, 0xc1, 0xe8, 0x1f, 0x0f, 0x8e, 0x15, 0xfe, 0x9e,
	0x18, 0x5f, 0xb2, 0xe4, 0x05, 0xb2, 0x4f, 0x61, 0xbe, 0x4a, 0xb1, 0xc4, 0x24, 0xc7, 0x35, 0xe6,
	0xa1, 0x77, 0xe9, 0x5d, 0x4d, 0x62, 0x30, 0xd0, 0xf7, 0x84, 0xb0, 0xcf, 0xe0, 0xf0, 0x7d, 0xb5,
	0x54, 0x5c, 0x60, 0x92, 0x72, 0x25, 0xc2, 0xd1, 0xa5, 0x77, 0xe5, 0xc7, 0x73, 0x87, 0xdd, 0x71,
	0x25, 0xd8, 0x0b, 0x98, 0x56, 0x39, 0xdf, 0xa0, 0x0a, 0xc7, 0x97, 0xde, 0xd5, 0xfc, 0xe6, 0xec,
	0xda, 0xb1, 0x62, 0xa9, 0x33, 0xbd, 0x49, 0xac, 0x33, 0x76, 0x41, 0xec, 0x02, 0x02, 0xa2, 0x4e,
	0xf4, 0xa6, 0xc2, 0xf0, 0xc0, 0x10, 0xfa, 0x04, 0xfc, 0xb8, 0xa9, 0x30, 0xca, 0xe0, 0x58, 0xad,
	0xaa, 0xb6, 0xc2, 0x4f, 0x00, 0x50, 0x29, 0xa9, 0x92, 0x54, 0x0a, 0x74, 0x02, 0x03, 0x83, 0xdc,
	0x49, 0x61, 0xdc, 0x36, 0xd8, 0xa4, 0x1b, 0x59, 0xb7, 0x41, 0x28, 0x1f, 0x7b, 0x0e, 0xbe, 0x92,
	0xf7, 0x52, 0x27, 0x99, 0x30, 0xea, 0x26, 0xf1, 0xcc, 0xd8, 0x0b, 0x11, 0x31, 0x78, 0x4a, 0xc5,
	0x48, 0x79, 0x99, 0x62, 0x6e, 0x19, 0x09, 0x2b, 0xf5, 0xdb, 0x2e, 0xf6, 0x27, 0x3c, 0x31, 0x71,
	0x0a, 0xb9, 0xc6, 0x44, 0x49, 0x59, 0x0c, 0x57, 0xed, 0x02, 0x82, 0x6a, 0x5d, 0x25, 0xa9, 0x7c,
	0x5f, 0x6a, 0x27, 0xca, 0xaf, 0xd6, 0xd5, 0x1d, 0xd9, 0x7b, 0xd6, 0x2b, 0xfa, 0xc8, 0xf2, 0x0b,
	0xcc, 0xd1, 0xf1, 0x13, 0x44, 0x32, 0xdb, 0xd0, 0x0f, 0xf0, 0x84, 0x0a, 0xd7, 0x56, 0x39, 0x50,
	0xb9, 0x0b, 0x08, 0x28, 0xcc, 0x7a, 0x9d, 0x46, 0x02, 0xc8, 0x19, 0xfd, 0x0c, 0x47, 0x44, 0xfa,
	0xab, 0xcc, 0x4a, 0x9b, 0xac, 0x13, 0xed, 0x75, 0xa3, 0x5b, 0x3b, 0x1a, 0xed, 0xb2, 0xa3, 0x6b,
	0x38, 0x22, 0xad, 0x4d, 0xf2, 0xc7, 0x95, 0x46, 0x7f, 0x8d, 0xe1, 0x98, 0xf6, 0x6b, 0x04, 0x28,
	0xe4, 0x62, 0xc3, 0x9e, 0xc1, 0xcc, 0x58, 0x99, 0x30, 0xe1, 0x41, 0x3c, 0x25, 0x73, 0x21, 0xd8,
	0x19, 0x4c, 0x0b, 0x5e, 0x11, 0x6e, 0xb7, 0x34, 0x29, 0x78, 0xb5, 0x10, 0xd4, 0x07, 0xf6, 0xc4,
	0x9a, 0x3e, 0x30, 0xf6, 0x42, 0x3c, 0xda, 0x8f, 0x74, 0xd2, 0x3c, 0xd5, 0xd9, 0x9a, 0x76, 0x91,
	0x89, 0x70, 0x62, 0x4f, 0xba, 0x86, 0x16, 0x82, 0x02, 0x14, 0x2f, 0x85, 0x2c, 0x92, 0x15, 0xa2,
	0x08, 0xa7, 0x36, 0xc0, 0x42, 0xaf, 0x11, 0x05, 0x7b, 0x09, 0x33, 0xbb, 0xed, 0x55, 0x38, 0xbb,
	0x1c, 0x3f, 0x5c, 0x9c, 0x3a, 0x8a, 0xbd, 0x82, 0x43, 0x8d, 0xbc, 0x48, 0xac, 0x7b, 0x15, 0xfa,
	0x66, 0xd5, 0x49, 0x6f, 0x15, 0x85, 0xc4, 0x73, 0xfa, 0xfd, 0xce, 0xc6, 0xb1, 0x1b, 0x00, 0x91,
	0xf1, 0x5c, 0x2e, 0x13, 0xae, 0x54, 0x18, 0x74, 0x57, 0xd5, 0x1e, 0xad, 0x55, 0x1c, 0x58, 0xe3,
	0x6b, 0xa5, 0xd8, 0x0b, 0xf0, 0xa9, 0x5a, 0x82, 0x6b, 0x1e, 0x82, 0x39, 0x3a, 0x56, 0xaf, 0x20,
	0xdc, 0x72, 0xc5, 0xb3, 0x82, 0x57, 0xdf, 0x72, 0xcd, 0x19, 0x83, 0x03, 0xae, 0x96, 0xab, 0xf0,
	0xd0, 0xec, 0xd2, 0xfc, 0x8f, 0x04, 0xb0, 0x66, 0xa6, 0xd4, 0x85, 0x19, 0xbe, 0x21, 0x7b, 0xb6,
	0x4c, 0x01, 0xac, 0x99, 0x0b, 0x5b, 0x96, 0xff, 0x6d, 0x36, 0x5c, 0xc0, 0xf3, 0xfe, 0x6c, 0xd8,
	0xb2, 0x92, 0xb3, 0x3f, 0x24, 0x1a, 0xe7, 0x2f, 0x9d, 0x69, 0x41, 0xe7, 0xd3, 0x1d, 0x06, 0xde,
	0x83, 0xc3, 0x60, 0xa7, 0x3a, 0x7c, 0xd1, 0xb9, 0xe6, 0x26, 0xfd, 0xc0, 0xe5, 0x39, 0x82, 0xb9,
	0x39, 0x1f, 0xdb, 0x32, 0xd1, 0x1b, 0x98, 0x93, 0x78, 0x67, 0x0e, 0x55, 0xf0, 0x73, 0x38, 0xa0,
	0x30, 0xa7, 0x6d, 0xdb, 0x4d, 0xad, 0xfe, 0x8c, 0x4d, 0x40, 0x74, 0x03, 0xa7, 0xc4, 0x92, 0x95,
	0xeb, 0x4c, 0xa3, 0xbd, 0xd9, 0x26, 0xff, 0x39, 0xf8, 0x56, 0xf9, 0xc2, 0x5e, 0xd4, 0x71, 0xbc,
	0xb5, 0xa3, 0xaf, 0xe0, 0x94, 0xf6, 0xf2, 0xc1, 0x9a, 0x81, 0x0d, 0xfd, 0x01, 0x27, 0x44, 0xc5,
	0x97, 0x0a, 0xdb, 0xab, 0x9e, 0xc1, 0xcc, 0xc8, 0xca, 0x6a, 0xa2, 0x29, 0x99, 0x0b, 0xc1, 0x3e,
	0x86, 0xc0, 0x52, 0x90, 0x86, 0x91, 0x71, 0x35, 0xc0, 0xbe, 0xc3, 0xf8, 0x4b, 0x38, 0x21, 0xcd,
	0x7d, 0xf2, 0x01, 0xc9, 0x39, 0x9c, 0x52, 0xd1, 0x79, 0xb9, 0x91, 0xe5, 0x8e, 0xd5, 0x19, 0x90,
	0x7d, 0x0e, 0x3e, 0x65, 0xa0, 0x3e, 0x76, 0xbd, 0xbb, 0xb5, 0xa3, 0xa7, 0xf6, 0x2b, 0x9f, 0x23,
	0x5f, 0xdb, 0x16, 0x89, 0x5e, 0xda, 0xf9, 0xd9, 0x20, 0x43, 0x82, 0x5d, 0x8a, 0x7b, 0x85, 0xfc,
	0xb7, 0x4e, 0x8a, 0x06, 0x19, 0x4a, 0x71, 0x6a, 0xe7, 0xc2, 0x0a, 0xb9, 0x4a, 0xdf, 0x25, 0x15,
	0xcf, 0x69, 0xb8, 0x45, 0xb7, 0xc0, 0x28, 0x4d, 0x8d, 0xba, 0x91, 0x37, 0x90, 0xea, 0x16, 0xce,
	0x28, 0x95, 0x39, 0xde, 0x02, 0x8b, 0x7b, 0x54, 0xee, 0x2b, 0xf0, 0x58, 0x77, 0xc5, 0x70, 0x46,
	0x4c, 0x7b, 0x2d, 0xea, 0x09, 0x19, 0xf5, 0x85, 0xbc, 0x82, 0xd0, 0xee, 0x29, 0xc7, 0x54, 0xdb,
	0xd4, 0x9a, 0xe7, 0x58, 0x6a, 0x77, 0x22, 0xee, 0x7f, 0x7d, 0xc9, 0x6b, 0x3b, 0x7a, 0x03, 0x21,
	0x75, 0xcd, 0xbe, 0xeb, 0x86, 0xe4, 0xfc, 0xed, 0xd9, 0xab, 0xe0, 0x86, 0x1c, 0xa5, 0x35, 0x4f,
	0xa6, 0x07, 0xaf, 0x42, 0x9b, 0x6b, 0xd4, 0xe3, 0xea, 0x3f, 0xf4, 0xc6, 0x1f, 0x3e, 0xf4, 0x5a,
	0x9f, 0xb2, 0x83, 0x5d, 0x3e, 0x65, 0xd1, 0x6b, 0x38, 0x31, 0xc3, 0xa6, 0xa7, 0xef, 0x3f, 0x8d,
	0xed, 0x6f, 0xe0, 0x27, 0xdf, 0x3c, 0x67, 0x05, 0xbe, 0xbd, 0x9f, 0x9a, 0x7f, 0xb7, 0xff, 0x06,
	0x00, 0x00, 0xff, 0xff, 0x73, 0xdb, 0x1a, 0x79, 0xfc, 0x0a, 0x00, 0x00,
}
