// Code generated by protoc-gen-go. DO NOT EDIT.
// source: server.proto

package protodef

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Packet struct {
	CmdId                int32    `protobuf:"varint,1,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"`
	Data                 []byte   `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Packet) Reset()         { *m = Packet{} }
func (m *Packet) String() string { return proto.CompactTextString(m) }
func (*Packet) ProtoMessage()    {}
func (*Packet) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{0}
}

func (m *Packet) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Packet.Unmarshal(m, b)
}
func (m *Packet) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Packet.Marshal(b, m, deterministic)
}
func (m *Packet) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Packet.Merge(m, src)
}
func (m *Packet) XXX_Size() int {
	return xxx_messageInfo_Packet.Size(m)
}
func (m *Packet) XXX_DiscardUnknown() {
	xxx_messageInfo_Packet.DiscardUnknown(m)
}

var xxx_messageInfo_Packet proto.InternalMessageInfo

func (m *Packet) GetCmdId() int32 {
	if m != nil {
		return m.CmdId
	}
	return 0
}

func (m *Packet) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type ServerPacket struct {
	SessionId            int64    `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	CmdId                int32    `protobuf:"varint,2,opt,name=cmd_id,json=cmdId,proto3" json:"cmd_id,omitempty"`
	Data                 []byte   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	PlayerId             int64    `protobuf:"varint,4,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ServerPacket) Reset()         { *m = ServerPacket{} }
func (m *ServerPacket) String() string { return proto.CompactTextString(m) }
func (*ServerPacket) ProtoMessage()    {}
func (*ServerPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{1}
}

func (m *ServerPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ServerPacket.Unmarshal(m, b)
}
func (m *ServerPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ServerPacket.Marshal(b, m, deterministic)
}
func (m *ServerPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ServerPacket.Merge(m, src)
}
func (m *ServerPacket) XXX_Size() int {
	return xxx_messageInfo_ServerPacket.Size(m)
}
func (m *ServerPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_ServerPacket.DiscardUnknown(m)
}

var xxx_messageInfo_ServerPacket proto.InternalMessageInfo

func (m *ServerPacket) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *ServerPacket) GetCmdId() int32 {
	if m != nil {
		return m.CmdId
	}
	return 0
}

func (m *ServerPacket) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ServerPacket) GetPlayerId() int64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

type ClientConnectPacket struct {
	GateId               int32    `protobuf:"varint,1,opt,name=gate_id,json=gateId,proto3" json:"gate_id,omitempty"`
	SessionId            int64    `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Ip                   string   `protobuf:"bytes,3,opt,name=ip,proto3" json:"ip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientConnectPacket) Reset()         { *m = ClientConnectPacket{} }
func (m *ClientConnectPacket) String() string { return proto.CompactTextString(m) }
func (*ClientConnectPacket) ProtoMessage()    {}
func (*ClientConnectPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{2}
}

func (m *ClientConnectPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientConnectPacket.Unmarshal(m, b)
}
func (m *ClientConnectPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientConnectPacket.Marshal(b, m, deterministic)
}
func (m *ClientConnectPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientConnectPacket.Merge(m, src)
}
func (m *ClientConnectPacket) XXX_Size() int {
	return xxx_messageInfo_ClientConnectPacket.Size(m)
}
func (m *ClientConnectPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientConnectPacket.DiscardUnknown(m)
}

var xxx_messageInfo_ClientConnectPacket proto.InternalMessageInfo

func (m *ClientConnectPacket) GetGateId() int32 {
	if m != nil {
		return m.GateId
	}
	return 0
}

func (m *ClientConnectPacket) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *ClientConnectPacket) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

type ClientDisConnectPacket struct {
	PlayerId             int64    `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	SessionId            int64    `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientDisConnectPacket) Reset()         { *m = ClientDisConnectPacket{} }
func (m *ClientDisConnectPacket) String() string { return proto.CompactTextString(m) }
func (*ClientDisConnectPacket) ProtoMessage()    {}
func (*ClientDisConnectPacket) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{3}
}

func (m *ClientDisConnectPacket) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientDisConnectPacket.Unmarshal(m, b)
}
func (m *ClientDisConnectPacket) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientDisConnectPacket.Marshal(b, m, deterministic)
}
func (m *ClientDisConnectPacket) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientDisConnectPacket.Merge(m, src)
}
func (m *ClientDisConnectPacket) XXX_Size() int {
	return xxx_messageInfo_ClientDisConnectPacket.Size(m)
}
func (m *ClientDisConnectPacket) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientDisConnectPacket.DiscardUnknown(m)
}

var xxx_messageInfo_ClientDisConnectPacket proto.InternalMessageInfo

func (m *ClientDisConnectPacket) GetPlayerId() int64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *ClientDisConnectPacket) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

type ReqServerId struct {
	ServerType           int32    `protobuf:"varint,1,opt,name=server_type,json=serverType,proto3" json:"server_type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqServerId) Reset()         { *m = ReqServerId{} }
func (m *ReqServerId) String() string { return proto.CompactTextString(m) }
func (*ReqServerId) ProtoMessage()    {}
func (*ReqServerId) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{4}
}

func (m *ReqServerId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqServerId.Unmarshal(m, b)
}
func (m *ReqServerId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqServerId.Marshal(b, m, deterministic)
}
func (m *ReqServerId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqServerId.Merge(m, src)
}
func (m *ReqServerId) XXX_Size() int {
	return xxx_messageInfo_ReqServerId.Size(m)
}
func (m *ReqServerId) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqServerId.DiscardUnknown(m)
}

var xxx_messageInfo_ReqServerId proto.InternalMessageInfo

func (m *ReqServerId) GetServerType() int32 {
	if m != nil {
		return m.ServerType
	}
	return 0
}

type RspServerId struct {
	ServerID             int32    `protobuf:"varint,1,opt,name=serverID,proto3" json:"serverID,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspServerId) Reset()         { *m = RspServerId{} }
func (m *RspServerId) String() string { return proto.CompactTextString(m) }
func (*RspServerId) ProtoMessage()    {}
func (*RspServerId) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{5}
}

func (m *RspServerId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspServerId.Unmarshal(m, b)
}
func (m *RspServerId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspServerId.Marshal(b, m, deterministic)
}
func (m *RspServerId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspServerId.Merge(m, src)
}
func (m *RspServerId) XXX_Size() int {
	return xxx_messageInfo_RspServerId.Size(m)
}
func (m *RspServerId) XXX_DiscardUnknown() {
	xxx_messageInfo_RspServerId.DiscardUnknown(m)
}

var xxx_messageInfo_RspServerId proto.InternalMessageInfo

func (m *RspServerId) GetServerID() int32 {
	if m != nil {
		return m.ServerID
	}
	return 0
}

//大厅通知房间服务器 有玩家需要进入房间
type W2GPlayer struct {
	GateId               int32         `protobuf:"varint,1,opt,name=gate_id,json=gateId,proto3" json:"gate_id,omitempty"`
	Player               *EntityPlayer `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
	PlayerGateSession    int64         `protobuf:"varint,3,opt,name=player_gate_session,json=playerGateSession,proto3" json:"player_gate_session,omitempty"`
	RewardCup            int32         `protobuf:"varint,4,opt,name=reward_cup,json=rewardCup,proto3" json:"reward_cup,omitempty"`
	CInfo                *ClientInfo   `protobuf:"bytes,5,opt,name=c_info,json=cInfo,proto3" json:"c_info,omitempty"`
	LeagueID             int64         `protobuf:"varint,6,opt,name=leagueID,proto3" json:"leagueID,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *W2GPlayer) Reset()         { *m = W2GPlayer{} }
func (m *W2GPlayer) String() string { return proto.CompactTextString(m) }
func (*W2GPlayer) ProtoMessage()    {}
func (*W2GPlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{6}
}

func (m *W2GPlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_W2GPlayer.Unmarshal(m, b)
}
func (m *W2GPlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_W2GPlayer.Marshal(b, m, deterministic)
}
func (m *W2GPlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_W2GPlayer.Merge(m, src)
}
func (m *W2GPlayer) XXX_Size() int {
	return xxx_messageInfo_W2GPlayer.Size(m)
}
func (m *W2GPlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_W2GPlayer.DiscardUnknown(m)
}

var xxx_messageInfo_W2GPlayer proto.InternalMessageInfo

func (m *W2GPlayer) GetGateId() int32 {
	if m != nil {
		return m.GateId
	}
	return 0
}

func (m *W2GPlayer) GetPlayer() *EntityPlayer {
	if m != nil {
		return m.Player
	}
	return nil
}

func (m *W2GPlayer) GetPlayerGateSession() int64 {
	if m != nil {
		return m.PlayerGateSession
	}
	return 0
}

func (m *W2GPlayer) GetRewardCup() int32 {
	if m != nil {
		return m.RewardCup
	}
	return 0
}

func (m *W2GPlayer) GetCInfo() *ClientInfo {
	if m != nil {
		return m.CInfo
	}
	return nil
}

func (m *W2GPlayer) GetLeagueID() int64 {
	if m != nil {
		return m.LeagueID
	}
	return 0
}

type ClientInfo struct {
	PlayerID             int64    `protobuf:"varint,1,opt,name=playerID,proto3" json:"playerID,omitempty"`
	Idfa                 string   `protobuf:"bytes,2,opt,name=idfa,proto3" json:"idfa,omitempty"`
	Guid                 string   `protobuf:"bytes,3,opt,name=guid,proto3" json:"guid,omitempty"`
	Language             int32    `protobuf:"varint,4,opt,name=language,proto3" json:"language,omitempty"`
	Version              string   `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	Device               string   `protobuf:"bytes,6,opt,name=device,proto3" json:"device,omitempty"`
	Platform             string   `protobuf:"bytes,7,opt,name=platform,proto3" json:"platform,omitempty"`
	AppVersion           int32    `protobuf:"varint,9,opt,name=appVersion,proto3" json:"appVersion,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ClientInfo) Reset()         { *m = ClientInfo{} }
func (m *ClientInfo) String() string { return proto.CompactTextString(m) }
func (*ClientInfo) ProtoMessage()    {}
func (*ClientInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{7}
}

func (m *ClientInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ClientInfo.Unmarshal(m, b)
}
func (m *ClientInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ClientInfo.Marshal(b, m, deterministic)
}
func (m *ClientInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClientInfo.Merge(m, src)
}
func (m *ClientInfo) XXX_Size() int {
	return xxx_messageInfo_ClientInfo.Size(m)
}
func (m *ClientInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_ClientInfo.DiscardUnknown(m)
}

var xxx_messageInfo_ClientInfo proto.InternalMessageInfo

func (m *ClientInfo) GetPlayerID() int64 {
	if m != nil {
		return m.PlayerID
	}
	return 0
}

func (m *ClientInfo) GetIdfa() string {
	if m != nil {
		return m.Idfa
	}
	return ""
}

func (m *ClientInfo) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

func (m *ClientInfo) GetLanguage() int32 {
	if m != nil {
		return m.Language
	}
	return 0
}

func (m *ClientInfo) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *ClientInfo) GetDevice() string {
	if m != nil {
		return m.Device
	}
	return ""
}

func (m *ClientInfo) GetPlatform() string {
	if m != nil {
		return m.Platform
	}
	return ""
}

func (m *ClientInfo) GetAppVersion() int32 {
	if m != nil {
		return m.AppVersion
	}
	return 0
}

type MapEventParam struct {
	MapEventInterval     int32    `protobuf:"varint,1,opt,name=map_event_interval,json=mapEventInterval,proto3" json:"map_event_interval,omitempty"`
	MapEventLast         int32    `protobuf:"varint,2,opt,name=map_event_last,json=mapEventLast,proto3" json:"map_event_last,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MapEventParam) Reset()         { *m = MapEventParam{} }
func (m *MapEventParam) String() string { return proto.CompactTextString(m) }
func (*MapEventParam) ProtoMessage()    {}
func (*MapEventParam) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{8}
}

func (m *MapEventParam) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapEventParam.Unmarshal(m, b)
}
func (m *MapEventParam) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapEventParam.Marshal(b, m, deterministic)
}
func (m *MapEventParam) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapEventParam.Merge(m, src)
}
func (m *MapEventParam) XXX_Size() int {
	return xxx_messageInfo_MapEventParam.Size(m)
}
func (m *MapEventParam) XXX_DiscardUnknown() {
	xxx_messageInfo_MapEventParam.DiscardUnknown(m)
}

var xxx_messageInfo_MapEventParam proto.InternalMessageInfo

func (m *MapEventParam) GetMapEventInterval() int32 {
	if m != nil {
		return m.MapEventInterval
	}
	return 0
}

func (m *MapEventParam) GetMapEventLast() int32 {
	if m != nil {
		return m.MapEventLast
	}
	return 0
}

type W2GReqEnterRoom struct {
	Players              []*W2GPlayer   `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	RoomNumber           int32          `protobuf:"varint,2,opt,name=room_number,json=roomNumber,proto3" json:"room_number,omitempty"`
	MapID                int32          `protobuf:"varint,3,opt,name=mapID,proto3" json:"mapID,omitempty"`
	BgId                 int32          `protobuf:"varint,4,opt,name=bg_id,json=bgId,proto3" json:"bg_id,omitempty"`
	MapDifficulty        int32          `protobuf:"varint,5,opt,name=map_difficulty,json=mapDifficulty,proto3" json:"map_difficulty,omitempty"`
	ActivityId           int32          `protobuf:"varint,6,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	Mps                  []int32        `protobuf:"varint,7,rep,packed,name=mps,proto3" json:"mps,omitempty"`
	MapEventParam        *MapEventParam `protobuf:"bytes,8,opt,name=map_event_param,json=mapEventParam,proto3" json:"map_event_param,omitempty"`
	SceneEvent           string         `protobuf:"bytes,9,opt,name=scene_event,json=sceneEvent,proto3" json:"scene_event,omitempty"`
	MapData              *MapEntity     `protobuf:"bytes,10,opt,name=map_data,json=mapData,proto3" json:"map_data,omitempty"`
	GameType             int32          `protobuf:"varint,11,opt,name=game_type,json=gameType,proto3" json:"game_type,omitempty"`
	Args                 int32          `protobuf:"varint,12,opt,name=args,proto3" json:"args,omitempty"`
	TeamEntitys          []*EntityTeam  `protobuf:"bytes,13,rep,name=team_entitys,json=teamEntitys,proto3" json:"team_entitys,omitempty"`
	FirstTeamIndex       int32          `protobuf:"varint,14,opt,name=first_team_index,json=firstTeamIndex,proto3" json:"first_team_index,omitempty"`
	FirstPlayerID        int64          `protobuf:"varint,15,opt,name=first_playerID,json=firstPlayerID,proto3" json:"first_playerID,omitempty"`
	FirstRoleIndex       int32          `protobuf:"varint,16,opt,name=first_role_index,json=firstRoleIndex,proto3" json:"first_role_index,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *W2GReqEnterRoom) Reset()         { *m = W2GReqEnterRoom{} }
func (m *W2GReqEnterRoom) String() string { return proto.CompactTextString(m) }
func (*W2GReqEnterRoom) ProtoMessage()    {}
func (*W2GReqEnterRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{9}
}

func (m *W2GReqEnterRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_W2GReqEnterRoom.Unmarshal(m, b)
}
func (m *W2GReqEnterRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_W2GReqEnterRoom.Marshal(b, m, deterministic)
}
func (m *W2GReqEnterRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_W2GReqEnterRoom.Merge(m, src)
}
func (m *W2GReqEnterRoom) XXX_Size() int {
	return xxx_messageInfo_W2GReqEnterRoom.Size(m)
}
func (m *W2GReqEnterRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_W2GReqEnterRoom.DiscardUnknown(m)
}

var xxx_messageInfo_W2GReqEnterRoom proto.InternalMessageInfo

func (m *W2GReqEnterRoom) GetPlayers() []*W2GPlayer {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *W2GReqEnterRoom) GetRoomNumber() int32 {
	if m != nil {
		return m.RoomNumber
	}
	return 0
}

func (m *W2GReqEnterRoom) GetMapID() int32 {
	if m != nil {
		return m.MapID
	}
	return 0
}

func (m *W2GReqEnterRoom) GetBgId() int32 {
	if m != nil {
		return m.BgId
	}
	return 0
}

func (m *W2GReqEnterRoom) GetMapDifficulty() int32 {
	if m != nil {
		return m.MapDifficulty
	}
	return 0
}

func (m *W2GReqEnterRoom) GetActivityId() int32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *W2GReqEnterRoom) GetMps() []int32 {
	if m != nil {
		return m.Mps
	}
	return nil
}

func (m *W2GReqEnterRoom) GetMapEventParam() *MapEventParam {
	if m != nil {
		return m.MapEventParam
	}
	return nil
}

func (m *W2GReqEnterRoom) GetSceneEvent() string {
	if m != nil {
		return m.SceneEvent
	}
	return ""
}

func (m *W2GReqEnterRoom) GetMapData() *MapEntity {
	if m != nil {
		return m.MapData
	}
	return nil
}

func (m *W2GReqEnterRoom) GetGameType() int32 {
	if m != nil {
		return m.GameType
	}
	return 0
}

func (m *W2GReqEnterRoom) GetArgs() int32 {
	if m != nil {
		return m.Args
	}
	return 0
}

func (m *W2GReqEnterRoom) GetTeamEntitys() []*EntityTeam {
	if m != nil {
		return m.TeamEntitys
	}
	return nil
}

func (m *W2GReqEnterRoom) GetFirstTeamIndex() int32 {
	if m != nil {
		return m.FirstTeamIndex
	}
	return 0
}

func (m *W2GReqEnterRoom) GetFirstPlayerID() int64 {
	if m != nil {
		return m.FirstPlayerID
	}
	return 0
}

func (m *W2GReqEnterRoom) GetFirstRoleIndex() int32 {
	if m != nil {
		return m.FirstRoleIndex
	}
	return 0
}

//房间服务器通知大厅 房间创建完成
type G2WPlayer struct {
	Player               *EntityPlayer `protobuf:"bytes,1,opt,name=player,proto3" json:"player,omitempty"`
	GameID               int32         `protobuf:"varint,2,opt,name=gameID,proto3" json:"gameID,omitempty"`
	DiaId                int32         `protobuf:"varint,3,opt,name=dia_id,json=diaId,proto3" json:"dia_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *G2WPlayer) Reset()         { *m = G2WPlayer{} }
func (m *G2WPlayer) String() string { return proto.CompactTextString(m) }
func (*G2WPlayer) ProtoMessage()    {}
func (*G2WPlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{10}
}

func (m *G2WPlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_G2WPlayer.Unmarshal(m, b)
}
func (m *G2WPlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_G2WPlayer.Marshal(b, m, deterministic)
}
func (m *G2WPlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_G2WPlayer.Merge(m, src)
}
func (m *G2WPlayer) XXX_Size() int {
	return xxx_messageInfo_G2WPlayer.Size(m)
}
func (m *G2WPlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_G2WPlayer.DiscardUnknown(m)
}

var xxx_messageInfo_G2WPlayer proto.InternalMessageInfo

func (m *G2WPlayer) GetPlayer() *EntityPlayer {
	if m != nil {
		return m.Player
	}
	return nil
}

func (m *G2WPlayer) GetGameID() int32 {
	if m != nil {
		return m.GameID
	}
	return 0
}

func (m *G2WPlayer) GetDiaId() int32 {
	if m != nil {
		return m.DiaId
	}
	return 0
}

type G2WRspEnterRoom struct {
	Players              []*G2WPlayer  `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	RoomNumber           int32         `protobuf:"varint,2,opt,name=room_number,json=roomNumber,proto3" json:"room_number,omitempty"`
	MapId                int32         `protobuf:"varint,3,opt,name=map_id,json=mapId,proto3" json:"map_id,omitempty"`
	SceneId              int32         `protobuf:"varint,4,opt,name=scene_id,json=sceneId,proto3" json:"scene_id,omitempty"`
	RoomID               int64         `protobuf:"varint,5,opt,name=roomID,proto3" json:"roomID,omitempty"`
	ActivityId           int32         `protobuf:"varint,6,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	RandSeed             int32         `protobuf:"varint,7,opt,name=rand_seed,json=randSeed,proto3" json:"rand_seed,omitempty"`
	GameType             int32         `protobuf:"varint,8,opt,name=game_type,json=gameType,proto3" json:"game_type,omitempty"`
	Args                 int32         `protobuf:"varint,9,opt,name=args,proto3" json:"args,omitempty"`
	TeamEntitys          []*EntityTeam `protobuf:"bytes,10,rep,name=team_entitys,json=teamEntitys,proto3" json:"team_entitys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *G2WRspEnterRoom) Reset()         { *m = G2WRspEnterRoom{} }
func (m *G2WRspEnterRoom) String() string { return proto.CompactTextString(m) }
func (*G2WRspEnterRoom) ProtoMessage()    {}
func (*G2WRspEnterRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{11}
}

func (m *G2WRspEnterRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_G2WRspEnterRoom.Unmarshal(m, b)
}
func (m *G2WRspEnterRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_G2WRspEnterRoom.Marshal(b, m, deterministic)
}
func (m *G2WRspEnterRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_G2WRspEnterRoom.Merge(m, src)
}
func (m *G2WRspEnterRoom) XXX_Size() int {
	return xxx_messageInfo_G2WRspEnterRoom.Size(m)
}
func (m *G2WRspEnterRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_G2WRspEnterRoom.DiscardUnknown(m)
}

var xxx_messageInfo_G2WRspEnterRoom proto.InternalMessageInfo

func (m *G2WRspEnterRoom) GetPlayers() []*G2WPlayer {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *G2WRspEnterRoom) GetRoomNumber() int32 {
	if m != nil {
		return m.RoomNumber
	}
	return 0
}

func (m *G2WRspEnterRoom) GetMapId() int32 {
	if m != nil {
		return m.MapId
	}
	return 0
}

func (m *G2WRspEnterRoom) GetSceneId() int32 {
	if m != nil {
		return m.SceneId
	}
	return 0
}

func (m *G2WRspEnterRoom) GetRoomID() int64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *G2WRspEnterRoom) GetActivityId() int32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *G2WRspEnterRoom) GetRandSeed() int32 {
	if m != nil {
		return m.RandSeed
	}
	return 0
}

func (m *G2WRspEnterRoom) GetGameType() int32 {
	if m != nil {
		return m.GameType
	}
	return 0
}

func (m *G2WRspEnterRoom) GetArgs() int32 {
	if m != nil {
		return m.Args
	}
	return 0
}

func (m *G2WRspEnterRoom) GetTeamEntitys() []*EntityTeam {
	if m != nil {
		return m.TeamEntitys
	}
	return nil
}

//大厅通知网关 玩家所在的房间服务器
type ReqSetPlayerGameId struct {
	GameId               int32    `protobuf:"varint,1,opt,name=game_id,json=gameId,proto3" json:"game_id,omitempty"`
	SessionId            int64    `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSetPlayerGameId) Reset()         { *m = ReqSetPlayerGameId{} }
func (m *ReqSetPlayerGameId) String() string { return proto.CompactTextString(m) }
func (*ReqSetPlayerGameId) ProtoMessage()    {}
func (*ReqSetPlayerGameId) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{12}
}

func (m *ReqSetPlayerGameId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSetPlayerGameId.Unmarshal(m, b)
}
func (m *ReqSetPlayerGameId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSetPlayerGameId.Marshal(b, m, deterministic)
}
func (m *ReqSetPlayerGameId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSetPlayerGameId.Merge(m, src)
}
func (m *ReqSetPlayerGameId) XXX_Size() int {
	return xxx_messageInfo_ReqSetPlayerGameId.Size(m)
}
func (m *ReqSetPlayerGameId) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSetPlayerGameId.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSetPlayerGameId proto.InternalMessageInfo

func (m *ReqSetPlayerGameId) GetGameId() int32 {
	if m != nil {
		return m.GameId
	}
	return 0
}

func (m *ReqSetPlayerGameId) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

//大厅通知网关 玩家的唯一ID
type ReqSetPlayerId struct {
	PlayerId             int64    `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	SessionId            int64    `protobuf:"varint,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqSetPlayerId) Reset()         { *m = ReqSetPlayerId{} }
func (m *ReqSetPlayerId) String() string { return proto.CompactTextString(m) }
func (*ReqSetPlayerId) ProtoMessage()    {}
func (*ReqSetPlayerId) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{13}
}

func (m *ReqSetPlayerId) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqSetPlayerId.Unmarshal(m, b)
}
func (m *ReqSetPlayerId) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqSetPlayerId.Marshal(b, m, deterministic)
}
func (m *ReqSetPlayerId) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqSetPlayerId.Merge(m, src)
}
func (m *ReqSetPlayerId) XXX_Size() int {
	return xxx_messageInfo_ReqSetPlayerId.Size(m)
}
func (m *ReqSetPlayerId) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqSetPlayerId.DiscardUnknown(m)
}

var xxx_messageInfo_ReqSetPlayerId proto.InternalMessageInfo

func (m *ReqSetPlayerId) GetPlayerId() int64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *ReqSetPlayerId) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

//房间服务器通知大厅 游戏结束
type R2WExitRoom struct {
	Players              []*R2WExitPlayer `protobuf:"bytes,1,rep,name=players,proto3" json:"players,omitempty"`
	WinPlayer            int64            `protobuf:"varint,2,opt,name=win_player,json=winPlayer,proto3" json:"win_player,omitempty"`
	Frame                int32            `protobuf:"varint,3,opt,name=frame,proto3" json:"frame,omitempty"`
	RoomType             int32            `protobuf:"varint,4,opt,name=room_type,json=roomType,proto3" json:"room_type,omitempty"`
	RoomID               int64            `protobuf:"varint,5,opt,name=roomID,proto3" json:"roomID,omitempty"`
	ResultType           int32            `protobuf:"varint,6,opt,name=result_type,json=resultType,proto3" json:"result_type,omitempty"`
	Entities             *EntityAll       `protobuf:"bytes,7,opt,name=entities,proto3" json:"entities,omitempty"`
	ActivityId           int32            `protobuf:"varint,8,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	FirstPlayId          int64            `protobuf:"varint,9,opt,name=first_playId,json=firstPlayId,proto3" json:"first_playId,omitempty"`
	WinTeam              int32            `protobuf:"varint,10,opt,name=win_team,json=winTeam,proto3" json:"win_team,omitempty"`
	BattleDetail         []*BattleDetail  `protobuf:"bytes,11,rep,name=battle_detail,json=battleDetail,proto3" json:"battle_detail,omitempty"`
	XXX_NoUnkeyedLiteral struct{}         `json:"-"`
	XXX_unrecognized     []byte           `json:"-"`
	XXX_sizecache        int32            `json:"-"`
}

func (m *R2WExitRoom) Reset()         { *m = R2WExitRoom{} }
func (m *R2WExitRoom) String() string { return proto.CompactTextString(m) }
func (*R2WExitRoom) ProtoMessage()    {}
func (*R2WExitRoom) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{14}
}

func (m *R2WExitRoom) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_R2WExitRoom.Unmarshal(m, b)
}
func (m *R2WExitRoom) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_R2WExitRoom.Marshal(b, m, deterministic)
}
func (m *R2WExitRoom) XXX_Merge(src proto.Message) {
	xxx_messageInfo_R2WExitRoom.Merge(m, src)
}
func (m *R2WExitRoom) XXX_Size() int {
	return xxx_messageInfo_R2WExitRoom.Size(m)
}
func (m *R2WExitRoom) XXX_DiscardUnknown() {
	xxx_messageInfo_R2WExitRoom.DiscardUnknown(m)
}

var xxx_messageInfo_R2WExitRoom proto.InternalMessageInfo

func (m *R2WExitRoom) GetPlayers() []*R2WExitPlayer {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *R2WExitRoom) GetWinPlayer() int64 {
	if m != nil {
		return m.WinPlayer
	}
	return 0
}

func (m *R2WExitRoom) GetFrame() int32 {
	if m != nil {
		return m.Frame
	}
	return 0
}

func (m *R2WExitRoom) GetRoomType() int32 {
	if m != nil {
		return m.RoomType
	}
	return 0
}

func (m *R2WExitRoom) GetRoomID() int64 {
	if m != nil {
		return m.RoomID
	}
	return 0
}

func (m *R2WExitRoom) GetResultType() int32 {
	if m != nil {
		return m.ResultType
	}
	return 0
}

func (m *R2WExitRoom) GetEntities() *EntityAll {
	if m != nil {
		return m.Entities
	}
	return nil
}

func (m *R2WExitRoom) GetActivityId() int32 {
	if m != nil {
		return m.ActivityId
	}
	return 0
}

func (m *R2WExitRoom) GetFirstPlayId() int64 {
	if m != nil {
		return m.FirstPlayId
	}
	return 0
}

func (m *R2WExitRoom) GetWinTeam() int32 {
	if m != nil {
		return m.WinTeam
	}
	return 0
}

func (m *R2WExitRoom) GetBattleDetail() []*BattleDetail {
	if m != nil {
		return m.BattleDetail
	}
	return nil
}

type R2WExitPlayer struct {
	PlayerId             int64             `protobuf:"varint,1,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	KillCount            int32             `protobuf:"varint,2,opt,name=kill_count,json=killCount,proto3" json:"kill_count,omitempty"`
	SelfKillCount        int32             `protobuf:"varint,3,opt,name=self_kill_count,json=selfKillCount,proto3" json:"self_kill_count,omitempty"`
	BestReplay           *BestReplay       `protobuf:"bytes,4,opt,name=best_replay,json=bestReplay,proto3" json:"best_replay,omitempty"`
	DazzlingActions      []*DazzlingAction `protobuf:"bytes,5,rep,name=dazzling_actions,json=dazzlingActions,proto3" json:"dazzling_actions,omitempty"`
	BattleTime           int32             `protobuf:"varint,6,opt,name=battle_time,json=battleTime,proto3" json:"battle_time,omitempty"`
	RoleType             int32             `protobuf:"varint,7,opt,name=role_type,json=roleType,proto3" json:"role_type,omitempty"`
	Team                 int32             `protobuf:"varint,8,opt,name=team,proto3" json:"team,omitempty"`
	Rank                 int32             `protobuf:"varint,9,opt,name=rank,proto3" json:"rank,omitempty"`
	LeagueID             int64             `protobuf:"varint,10,opt,name=leagueID,proto3" json:"leagueID,omitempty"`
	IsBot                bool              `protobuf:"varint,11,opt,name=is_bot,json=isBot,proto3" json:"is_bot,omitempty"`
	IsCreator            bool              `protobuf:"varint,12,opt,name=is_creator,json=isCreator,proto3" json:"is_creator,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *R2WExitPlayer) Reset()         { *m = R2WExitPlayer{} }
func (m *R2WExitPlayer) String() string { return proto.CompactTextString(m) }
func (*R2WExitPlayer) ProtoMessage()    {}
func (*R2WExitPlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{15}
}

func (m *R2WExitPlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_R2WExitPlayer.Unmarshal(m, b)
}
func (m *R2WExitPlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_R2WExitPlayer.Marshal(b, m, deterministic)
}
func (m *R2WExitPlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_R2WExitPlayer.Merge(m, src)
}
func (m *R2WExitPlayer) XXX_Size() int {
	return xxx_messageInfo_R2WExitPlayer.Size(m)
}
func (m *R2WExitPlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_R2WExitPlayer.DiscardUnknown(m)
}

var xxx_messageInfo_R2WExitPlayer proto.InternalMessageInfo

func (m *R2WExitPlayer) GetPlayerId() int64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *R2WExitPlayer) GetKillCount() int32 {
	if m != nil {
		return m.KillCount
	}
	return 0
}

func (m *R2WExitPlayer) GetSelfKillCount() int32 {
	if m != nil {
		return m.SelfKillCount
	}
	return 0
}

func (m *R2WExitPlayer) GetBestReplay() *BestReplay {
	if m != nil {
		return m.BestReplay
	}
	return nil
}

func (m *R2WExitPlayer) GetDazzlingActions() []*DazzlingAction {
	if m != nil {
		return m.DazzlingActions
	}
	return nil
}

func (m *R2WExitPlayer) GetBattleTime() int32 {
	if m != nil {
		return m.BattleTime
	}
	return 0
}

func (m *R2WExitPlayer) GetRoleType() int32 {
	if m != nil {
		return m.RoleType
	}
	return 0
}

func (m *R2WExitPlayer) GetTeam() int32 {
	if m != nil {
		return m.Team
	}
	return 0
}

func (m *R2WExitPlayer) GetRank() int32 {
	if m != nil {
		return m.Rank
	}
	return 0
}

func (m *R2WExitPlayer) GetLeagueID() int64 {
	if m != nil {
		return m.LeagueID
	}
	return 0
}

func (m *R2WExitPlayer) GetIsBot() bool {
	if m != nil {
		return m.IsBot
	}
	return false
}

func (m *R2WExitPlayer) GetIsCreator() bool {
	if m != nil {
		return m.IsCreator
	}
	return false
}

type W2GKickPlayer struct {
	SessionId            int64    `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Reason               int32    `protobuf:"varint,2,opt,name=reason,proto3" json:"reason,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *W2GKickPlayer) Reset()         { *m = W2GKickPlayer{} }
func (m *W2GKickPlayer) String() string { return proto.CompactTextString(m) }
func (*W2GKickPlayer) ProtoMessage()    {}
func (*W2GKickPlayer) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{16}
}

func (m *W2GKickPlayer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_W2GKickPlayer.Unmarshal(m, b)
}
func (m *W2GKickPlayer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_W2GKickPlayer.Marshal(b, m, deterministic)
}
func (m *W2GKickPlayer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_W2GKickPlayer.Merge(m, src)
}
func (m *W2GKickPlayer) XXX_Size() int {
	return xxx_messageInfo_W2GKickPlayer.Size(m)
}
func (m *W2GKickPlayer) XXX_DiscardUnknown() {
	xxx_messageInfo_W2GKickPlayer.DiscardUnknown(m)
}

var xxx_messageInfo_W2GKickPlayer proto.InternalMessageInfo

func (m *W2GKickPlayer) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *W2GKickPlayer) GetReason() int32 {
	if m != nil {
		return m.Reason
	}
	return 0
}

type G2RUpdateGate struct {
	SessionId            int64    `protobuf:"varint,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	PlayerId             int64    `protobuf:"varint,2,opt,name=player_id,json=playerId,proto3" json:"player_id,omitempty"`
	GateId               int32    `protobuf:"varint,3,opt,name=gate_id,json=gateId,proto3" json:"gate_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *G2RUpdateGate) Reset()         { *m = G2RUpdateGate{} }
func (m *G2RUpdateGate) String() string { return proto.CompactTextString(m) }
func (*G2RUpdateGate) ProtoMessage()    {}
func (*G2RUpdateGate) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{17}
}

func (m *G2RUpdateGate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_G2RUpdateGate.Unmarshal(m, b)
}
func (m *G2RUpdateGate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_G2RUpdateGate.Marshal(b, m, deterministic)
}
func (m *G2RUpdateGate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_G2RUpdateGate.Merge(m, src)
}
func (m *G2RUpdateGate) XXX_Size() int {
	return xxx_messageInfo_G2RUpdateGate.Size(m)
}
func (m *G2RUpdateGate) XXX_DiscardUnknown() {
	xxx_messageInfo_G2RUpdateGate.DiscardUnknown(m)
}

var xxx_messageInfo_G2RUpdateGate proto.InternalMessageInfo

func (m *G2RUpdateGate) GetSessionId() int64 {
	if m != nil {
		return m.SessionId
	}
	return 0
}

func (m *G2RUpdateGate) GetPlayerId() int64 {
	if m != nil {
		return m.PlayerId
	}
	return 0
}

func (m *G2RUpdateGate) GetGateId() int32 {
	if m != nil {
		return m.GateId
	}
	return 0
}

//世界服通知网关打印日志
type W2GPrintLog struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *W2GPrintLog) Reset()         { *m = W2GPrintLog{} }
func (m *W2GPrintLog) String() string { return proto.CompactTextString(m) }
func (*W2GPrintLog) ProtoMessage()    {}
func (*W2GPrintLog) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{18}
}

func (m *W2GPrintLog) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_W2GPrintLog.Unmarshal(m, b)
}
func (m *W2GPrintLog) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_W2GPrintLog.Marshal(b, m, deterministic)
}
func (m *W2GPrintLog) XXX_Merge(src proto.Message) {
	xxx_messageInfo_W2GPrintLog.Merge(m, src)
}
func (m *W2GPrintLog) XXX_Size() int {
	return xxx_messageInfo_W2GPrintLog.Size(m)
}
func (m *W2GPrintLog) XXX_DiscardUnknown() {
	xxx_messageInfo_W2GPrintLog.DiscardUnknown(m)
}

var xxx_messageInfo_W2GPrintLog proto.InternalMessageInfo

//变天
type DayChange struct {
	ChangeMonth          bool     `protobuf:"varint,1,opt,name=change_month,json=changeMonth,proto3" json:"change_month,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DayChange) Reset()         { *m = DayChange{} }
func (m *DayChange) String() string { return proto.CompactTextString(m) }
func (*DayChange) ProtoMessage()    {}
func (*DayChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_ad098daeda4239f7, []int{19}
}

func (m *DayChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DayChange.Unmarshal(m, b)
}
func (m *DayChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DayChange.Marshal(b, m, deterministic)
}
func (m *DayChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DayChange.Merge(m, src)
}
func (m *DayChange) XXX_Size() int {
	return xxx_messageInfo_DayChange.Size(m)
}
func (m *DayChange) XXX_DiscardUnknown() {
	xxx_messageInfo_DayChange.DiscardUnknown(m)
}

var xxx_messageInfo_DayChange proto.InternalMessageInfo

func (m *DayChange) GetChangeMonth() bool {
	if m != nil {
		return m.ChangeMonth
	}
	return false
}

func init() {
	proto.RegisterType((*Packet)(nil), "protodef.Packet")
	proto.RegisterType((*ServerPacket)(nil), "protodef.ServerPacket")
	proto.RegisterType((*ClientConnectPacket)(nil), "protodef.client_connect_packet")
	proto.RegisterType((*ClientDisConnectPacket)(nil), "protodef.ClientDisConnectPacket")
	proto.RegisterType((*ReqServerId)(nil), "protodef.req_server_id")
	proto.RegisterType((*RspServerId)(nil), "protodef.rsp_server_id")
	proto.RegisterType((*W2GPlayer)(nil), "protodef.w2g_player")
	proto.RegisterType((*ClientInfo)(nil), "protodef.client_info")
	proto.RegisterType((*MapEventParam)(nil), "protodef.map_event_param")
	proto.RegisterType((*W2GReqEnterRoom)(nil), "protodef.w2g_req_enter_room")
	proto.RegisterType((*G2WPlayer)(nil), "protodef.g2w_player")
	proto.RegisterType((*G2WRspEnterRoom)(nil), "protodef.g2w_rsp_enter_room")
	proto.RegisterType((*ReqSetPlayerGameId)(nil), "protodef.req_set_player_game_id")
	proto.RegisterType((*ReqSetPlayerId)(nil), "protodef.req_set_player_id")
	proto.RegisterType((*R2WExitRoom)(nil), "protodef.r2w_exit_room")
	proto.RegisterType((*R2WExitPlayer)(nil), "protodef.r2w_exit_player")
	proto.RegisterType((*W2GKickPlayer)(nil), "protodef.w2g_kick_player")
	proto.RegisterType((*G2RUpdateGate)(nil), "protodef.g2r_update_gate")
	proto.RegisterType((*W2GPrintLog)(nil), "protodef.w2g_print_log")
	proto.RegisterType((*DayChange)(nil), "protodef.day_change")
}

func init() { proto.RegisterFile("server.proto", fileDescriptor_ad098daeda4239f7) }

var fileDescriptor_ad098daeda4239f7 = []byte{
	// 1380 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x57, 0xdb, 0x6e, 0xdc, 0x36,
	0x13, 0xc6, 0x7a, 0xad, 0x3d, 0xcc, 0xee, 0x7a, 0x1d, 0x26, 0x76, 0x94, 0x04, 0xf9, 0x7f, 0x57,
	0x68, 0x0b, 0x03, 0x4d, 0xdc, 0xc2, 0x29, 0x7a, 0xd1, 0xbb, 0xc4, 0x1b, 0xb4, 0x42, 0x4f, 0x06,
	0x63, 0xf4, 0xa2, 0x37, 0x02, 0x2d, 0x72, 0x15, 0xd6, 0x3a, 0x55, 0xe2, 0xda, 0x71, 0x1e, 0xa5,
	0x2f, 0xd0, 0x37, 0xea, 0x4d, 0xaf, 0xfa, 0x00, 0x7d, 0x87, 0x62, 0x86, 0x94, 0xf6, 0x90, 0x26,
	0x4e, 0xd1, 0x1b, 0x9b, 0xf3, 0x69, 0x38, 0x24, 0xe7, 0xfb, 0x66, 0xc8, 0x85, 0x71, 0xad, 0xaa,
	0x4b, 0x55, 0x1d, 0x95, 0x55, 0x61, 0x0a, 0x36, 0xa0, 0x7f, 0x52, 0xcd, 0xef, 0x8f, 0xe3, 0x22,
	0xcb, 0x8a, 0xdc, 0xe2, 0xc1, 0x13, 0xe8, 0x9d, 0x8a, 0xf8, 0x42, 0x19, 0xb6, 0x07, 0xbd, 0x38,
	0x93, 0x91, 0x96, 0x7e, 0xe7, 0xa0, 0x73, 0xe8, 0x71, 0x2f, 0xce, 0x64, 0x28, 0x19, 0x83, 0x6d,
	0x29, 0x8c, 0xf0, 0xb7, 0x0e, 0x3a, 0x87, 0x63, 0x4e, 0xe3, 0x60, 0x01, 0xe3, 0x17, 0x14, 0xdc,
	0x4d, 0x7d, 0x08, 0x50, 0xab, 0xba, 0xd6, 0x45, 0xde, 0x4c, 0xef, 0xf2, 0xa1, 0x43, 0x42, 0xb9,
	0x12, 0x79, 0xeb, 0x9f, 0x22, 0x77, 0x97, 0x91, 0xd9, 0x03, 0x18, 0x96, 0xa9, 0xb8, 0x56, 0x15,
	0x7a, 0x6f, 0x53, 0xa0, 0x81, 0x05, 0x42, 0x19, 0x44, 0xb0, 0x17, 0xa7, 0x5a, 0xe5, 0x26, 0x8a,
	0x8b, 0x3c, 0x57, 0xb1, 0x89, 0x4a, 0xbb, 0xfe, 0x5d, 0xe8, 0x27, 0xc2, 0xa8, 0xe5, 0xde, 0x7b,
	0x68, 0x86, 0x72, 0x63, 0x63, 0x5b, 0x9b, 0x1b, 0xdb, 0x81, 0x2d, 0x5d, 0xd2, 0xfa, 0x43, 0xbe,
	0xa5, 0xcb, 0xe0, 0x0c, 0xf6, 0x4f, 0x68, 0x81, 0x99, 0xae, 0x4f, 0xec, 0x12, 0xee, 0x84, 0x6b,
	0xfb, 0xea, 0xac, 0xef, 0xeb, 0x86, 0x55, 0x82, 0xcf, 0x60, 0x52, 0xa9, 0x5f, 0x22, 0x4b, 0x47,
	0xa4, 0x25, 0xfb, 0x3f, 0x8c, 0x9c, 0x61, 0xae, 0x4b, 0xe5, 0xb6, 0x0c, 0x16, 0x3a, 0xbb, 0x2e,
	0x55, 0xf0, 0x09, 0x4c, 0xaa, 0xba, 0x5c, 0x99, 0x71, 0x1f, 0x06, 0xd6, 0x08, 0x67, 0xce, 0xbd,
	0xb5, 0x83, 0xbf, 0x3a, 0x00, 0x57, 0xc7, 0x49, 0x64, 0xb7, 0xf3, 0xf6, 0x5c, 0x3c, 0x86, 0x9e,
	0x75, 0xa1, 0x1d, 0x8e, 0x8e, 0xf7, 0x8e, 0x9c, 0x10, 0x54, 0x6e, 0xb4, 0xb9, 0x76, 0xf3, 0xb9,
	0x73, 0x62, 0x47, 0x70, 0xdb, 0x9d, 0x98, 0xc2, 0xb9, 0xe3, 0x50, 0xb2, 0xba, 0xfc, 0x96, 0xfd,
	0xf4, 0x95, 0x30, 0xea, 0x85, 0xfd, 0x80, 0x49, 0xa8, 0xd4, 0x95, 0xa8, 0x64, 0x14, 0x2f, 0x4a,
	0xa2, 0xce, 0xe3, 0x43, 0x8b, 0x9c, 0x2c, 0x4a, 0xf6, 0x08, 0x7a, 0x71, 0xa4, 0xf3, 0x79, 0xe1,
	0x7b, 0x6e, 0xf5, 0x46, 0x90, 0x47, 0x8e, 0x53, 0xfc, 0xc8, 0xbd, 0x38, 0xcc, 0xe7, 0x05, 0x9e,
	0x37, 0x55, 0x22, 0x59, 0xa8, 0x70, 0xe6, 0xf7, 0x6c, 0xb6, 0x1b, 0x3b, 0xf8, 0xa3, 0x03, 0xa3,
	0x95, 0x29, 0xe8, 0xeb, 0x98, 0x98, 0x6d, 0x30, 0x33, 0x43, 0x89, 0x69, 0x39, 0xb7, 0xe2, 0x1d,
	0x72, 0x1a, 0x23, 0x96, 0x2c, 0xb4, 0x74, 0xb4, 0xd3, 0x98, 0xd6, 0x13, 0x79, 0xb2, 0x10, 0x89,
	0x72, 0x5b, 0x6f, 0x6d, 0xe6, 0x43, 0xff, 0x52, 0x55, 0x74, 0x78, 0x8f, 0xa6, 0x34, 0x26, 0xdb,
	0x87, 0x9e, 0x54, 0x97, 0x3a, 0x56, 0xb4, 0xc7, 0x21, 0x77, 0x96, 0xdb, 0x91, 0x99, 0x17, 0x55,
	0xe6, 0xf7, 0xe9, 0x4b, 0x6b, 0xb3, 0xff, 0x01, 0x88, 0xb2, 0xfc, 0xd1, 0x05, 0x1c, 0x5a, 0xea,
	0x97, 0x48, 0xa0, 0x60, 0x9a, 0x89, 0x32, 0x52, 0x97, 0x78, 0xbe, 0x52, 0x54, 0x22, 0x63, 0x8f,
	0x80, 0x2d, 0x21, 0x9d, 0x1b, 0x55, 0x5d, 0x8a, 0xd4, 0x91, 0xbb, 0x9b, 0x89, 0xf2, 0x39, 0x7e,
	0x08, 0x1d, 0xce, 0x3e, 0x84, 0x9d, 0xa5, 0x77, 0x2a, 0x6a, 0xe3, 0x8a, 0x6e, 0xdc, 0x78, 0x7e,
	0x2b, 0x6a, 0x13, 0xfc, 0xb9, 0x0d, 0x0c, 0x45, 0x83, 0xc2, 0x54, 0x38, 0x35, 0xaa, 0x8a, 0x22,
	0x63, 0x47, 0xd0, 0xb7, 0xb9, 0xab, 0xfd, 0xce, 0x41, 0xf7, 0x70, 0x74, 0x7c, 0x67, 0x49, 0xd3,
	0x52, 0x63, 0xbc, 0x71, 0x42, 0x25, 0xe3, 0xbc, 0x28, 0x5f, 0x64, 0xe7, 0x4e, 0x58, 0x1e, 0x07,
	0x84, 0xbe, 0x27, 0x84, 0xdd, 0x01, 0x2f, 0x13, 0x65, 0x38, 0xa3, 0x6c, 0x7b, 0xdc, 0x1a, 0xec,
	0x36, 0x78, 0xe7, 0x49, 0x53, 0xe1, 0x1e, 0xdf, 0x3e, 0x4f, 0x42, 0xc9, 0x3e, 0xb2, 0x1b, 0x97,
	0x7a, 0x3e, 0xd7, 0xf1, 0x22, 0x35, 0xd7, 0x94, 0x6e, 0x8f, 0x4f, 0x32, 0x51, 0xce, 0x5a, 0x10,
	0x97, 0x14, 0xb1, 0xd1, 0x97, 0x28, 0x59, 0x2d, 0x29, 0xf3, 0x98, 0x41, 0x07, 0x85, 0x92, 0xed,
	0x42, 0x37, 0x2b, 0x6b, 0xbf, 0x7f, 0xd0, 0x3d, 0xf4, 0x38, 0x0e, 0xd9, 0xd3, 0x37, 0x72, 0xea,
	0x0f, 0x48, 0x84, 0xf7, 0x96, 0xa7, 0xdb, 0x70, 0xa0, 0x55, 0x29, 0x5d, 0xa7, 0xc4, 0x01, 0x96,
	0x6c, 0xac, 0x72, 0x65, 0x7d, 0x88, 0xb7, 0x21, 0x07, 0x82, 0xc8, 0x8b, 0x3d, 0x86, 0x01, 0xed,
	0x1e, 0x1b, 0x1a, 0x50, 0x70, 0xd6, 0xd4, 0x17, 0x85, 0xa6, 0x1a, 0xe3, 0x7d, 0x3c, 0x8b, 0xeb,
	0x73, 0x89, 0xc8, 0x94, 0x6d, 0x00, 0x23, 0xab, 0x38, 0x04, 0xb0, 0xfc, 0x51, 0xa1, 0xa2, 0x4a,
	0x6a, 0x7f, 0x6c, 0xb3, 0x83, 0x63, 0xf6, 0x05, 0x8c, 0x8d, 0x12, 0x99, 0x0b, 0x54, 0xfb, 0x13,
	0xa2, 0xe7, 0xf6, 0x46, 0x0d, 0xa3, 0x0b, 0x1f, 0xe1, 0xdf, 0xe7, 0xd6, 0x8f, 0x1d, 0xc2, 0xee,
	0x5c, 0x57, 0xb5, 0xa1, 0x4f, 0x91, 0xce, 0xa5, 0x7a, 0xe5, 0xef, 0x50, 0xdc, 0x1d, 0xc2, 0xcf,
	0x94, 0xc8, 0x42, 0x44, 0x31, 0xff, 0xd6, 0xb3, 0xad, 0xa6, 0x29, 0x55, 0xd3, 0x84, 0xd0, 0xd3,
	0xa6, 0xa4, 0xda, 0x80, 0x55, 0x91, 0x2a, 0x17, 0x70, 0x77, 0x25, 0x20, 0x2f, 0x52, 0x45, 0x01,
	0x83, 0x9f, 0x01, 0x92, 0xe3, 0xab, 0xa6, 0x2f, 0x2d, 0xdb, 0x4f, 0xe7, 0x7d, 0xda, 0xcf, 0x3e,
	0xf4, 0x30, 0x1f, 0xe1, 0xcc, 0x89, 0xca, 0x59, 0x78, 0x97, 0x48, 0x2d, 0x22, 0x57, 0xbf, 0x1e,
	0xf7, 0xa4, 0x16, 0xa1, 0x0c, 0x7e, 0xdf, 0x02, 0x86, 0x8b, 0x61, 0xdb, 0x7c, 0x4f, 0x3d, 0x2f,
	0xf7, 0xf6, 0x2f, 0xf4, 0xbc, 0x07, 0x3d, 0xa4, 0x73, 0xb9, 0x3c, 0x0a, 0x5a, 0xb2, 0x7b, 0x30,
	0xb0, 0xf2, 0x68, 0x35, 0xdd, 0x27, 0x3b, 0x94, 0x78, 0x10, 0x9c, 0x1f, 0xce, 0x48, 0xce, 0x5d,
	0xee, 0xac, 0x9b, 0x75, 0xfc, 0x00, 0x86, 0x95, 0xc8, 0x65, 0x54, 0x2b, 0x25, 0xa9, 0x8d, 0x78,
	0x7c, 0x80, 0xc0, 0x0b, 0xa5, 0xe4, 0xba, 0x7e, 0x06, 0x6f, 0xd1, 0xcf, 0xf0, 0x1d, 0xfa, 0x81,
	0xf7, 0xd3, 0x4f, 0x70, 0x0a, 0xfb, 0xf6, 0xf2, 0x6a, 0x74, 0x11, 0xd1, 0xba, 0x5a, 0xda, 0x8b,
	0x26, 0x5b, 0xbf, 0x68, 0xb2, 0x9b, 0x2f, 0xdd, 0xe0, 0x07, 0xb8, 0xb5, 0x11, 0x51, 0xcb, 0xff,
	0x74, 0xbf, 0xfe, 0xda, 0x85, 0x49, 0x75, 0x7c, 0x15, 0xa9, 0x57, 0xda, 0x58, 0xda, 0x9f, 0x6c,
	0xd2, 0xbe, 0x52, 0xe8, 0xad, 0xe7, 0x26, 0xf7, 0x0f, 0x01, 0xae, 0x74, 0x1e, 0xad, 0xdc, 0x91,
	0x5d, 0x3e, 0xbc, 0xd2, 0xb9, 0x55, 0x3e, 0x76, 0xb2, 0x79, 0x25, 0x32, 0xd5, 0x10, 0x4f, 0x06,
	0x91, 0x84, 0x82, 0x21, 0x1e, 0xdc, 0xcd, 0x81, 0x00, 0xf1, 0xf0, 0x0e, 0xea, 0x2b, 0x55, 0x2f,
	0x52, 0x63, 0xa7, 0x39, 0xea, 0x2d, 0x44, 0x13, 0x8f, 0x60, 0x40, 0x84, 0x68, 0x55, 0x13, 0xf3,
	0x2b, 0xcd, 0xc4, 0x11, 0x25, 0xd2, 0x94, 0xb7, 0x3e, 0x9b, 0x5a, 0x1a, 0xbc, 0xa1, 0xa5, 0x0f,
	0x60, 0xbc, 0xac, 0xed, 0x50, 0x92, 0x32, 0xba, 0x7c, 0xd4, 0x56, 0xb6, 0x95, 0x30, 0x1e, 0x1f,
	0xb9, 0xa7, 0x06, 0xe6, 0xf1, 0xfe, 0x95, 0xce, 0xb1, 0x3d, 0xb0, 0x2f, 0x61, 0x72, 0x2e, 0x8c,
	0x49, 0x55, 0x24, 0x95, 0x11, 0x3a, 0xf5, 0x47, 0x94, 0xd4, 0xb6, 0x82, 0xd7, 0x3e, 0xf2, 0xb1,
	0x35, 0x67, 0x64, 0x05, 0xbf, 0x75, 0x61, 0xba, 0x91, 0xf2, 0x1b, 0xc9, 0xbe, 0xd0, 0x69, 0x1a,
	0xc5, 0xc5, 0x22, 0x6f, 0xee, 0xae, 0x21, 0x22, 0x27, 0x08, 0xb0, 0x8f, 0x61, 0x5a, 0xab, 0x74,
	0x1e, 0xad, 0xf8, 0x58, 0x42, 0x26, 0x08, 0x7f, 0xd3, 0xfa, 0x7d, 0x0e, 0xa3, 0x73, 0x85, 0x5d,
	0x4a, 0x61, 0x64, 0xa2, 0x66, 0x45, 0xee, 0x2b, 0x9f, 0x38, 0xa0, 0xc1, 0x69, 0xcc, 0x9e, 0xc1,
	0xae, 0x14, 0xaf, 0x5f, 0xa7, 0x3a, 0x4f, 0x22, 0x4c, 0x5f, 0x91, 0xd7, 0xbe, 0x47, 0x87, 0xbd,
	0xdb, 0x4c, 0xdd, 0xf8, 0xce, 0xa7, 0x0d, 0xf0, 0xd4, 0xfa, 0x23, 0x19, 0x2e, 0x21, 0x46, 0x67,
	0x2d, 0xbb, 0x16, 0x3a, 0xd3, 0x8d, 0x66, 0x52, 0x57, 0xbb, 0x4d, 0x61, 0x17, 0x69, 0x5b, 0xbb,
	0x44, 0x81, 0xe5, 0x90, 0xc6, 0x88, 0x55, 0x22, 0xbf, 0x68, 0xea, 0x19, 0xc7, 0x6b, 0x2f, 0x24,
	0x58, 0x7f, 0x21, 0x61, 0x93, 0xd2, 0x75, 0x74, 0x5e, 0x18, 0xba, 0x59, 0x06, 0xdc, 0xd3, 0xf5,
	0xb3, 0x82, 0x5e, 0xe9, 0xba, 0x8e, 0xe2, 0x4a, 0x09, 0x53, 0x54, 0x74, 0xb9, 0x0c, 0xf8, 0x50,
	0xd7, 0x27, 0x16, 0x08, 0xbe, 0x86, 0x29, 0x5e, 0xf1, 0x17, 0x3a, 0xbe, 0x68, 0x88, 0xba, 0xe1,
	0x5d, 0x8f, 0xfa, 0x56, 0xa2, 0x2e, 0xf2, 0xa6, 0x47, 0x5b, 0x2b, 0x98, 0xc3, 0x34, 0x39, 0xae,
	0xa2, 0x45, 0x29, 0xf1, 0xe5, 0x88, 0xcf, 0xc7, 0x9b, 0x22, 0xad, 0x29, 0x62, 0x6b, 0x43, 0x11,
	0x2b, 0x2f, 0xda, 0xee, 0xea, 0x8b, 0x36, 0x98, 0xc2, 0x84, 0x1e, 0x25, 0x95, 0xc6, 0xa7, 0x4e,
	0x91, 0x04, 0x9f, 0x02, 0x48, 0x71, 0x1d, 0xc5, 0x2f, 0x45, 0x9e, 0x28, 0x14, 0xbd, 0x1d, 0x45,
	0x59, 0x91, 0x9b, 0x97, 0xb4, 0xea, 0x80, 0x8f, 0x2c, 0xf6, 0x1d, 0x42, 0xcf, 0xe0, 0xa7, 0xf6,
	0x77, 0xd1, 0x79, 0x8f, 0x46, 0x4f, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x0a, 0x61, 0xb2, 0xa9,
	0x38, 0x0d, 0x00, 0x00,
}
